/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a partner account (pending approval) */
        post: operations["authRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: operations["authMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset (always 202; token returned in dev) */
        post: operations["authPasswordResetRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm password reset */
        post: operations["authPasswordResetConfirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cabinet/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Partner dashboard summary */
        get: operations["cabinetSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cabinet/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Offer catalog with partner access state */
        get: operations["cabinetOffersList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cabinet/offers/{offerId}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join an active offer, creating a tracking link */
        post: operations["cabinetOfferJoin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cabinet/offers/{offerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Offer statistics (joined offers only) */
        get: operations["cabinetOfferStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cabinet/offers/{offerId}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List traffic sources for a joined offer */
        get: operations["cabinetOfferSourcesList"];
        put?: never;
        /** Create a traffic source for a joined offer */
        post: operations["cabinetOfferSourceCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cabinet/offers/{offerId}/sources/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a traffic source (only if it has no clicks) */
        delete: operations["cabinetOfferSourceDelete"];
        options?: never;
        head?: never;
        /** Update a traffic source */
        patch: operations["cabinetOfferSourceUpdate"];
        trace?: never;
    };
    "/cabinet/source-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List partner's source groups */
        get: operations["cabinetSourceGroupsList"];
        put?: never;
        /** Create a source group */
        post: operations["cabinetSourceGroupCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cabinet/source-groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an empty source group */
        delete: operations["cabinetSourceGroupDelete"];
        options?: never;
        head?: never;
        /** Update a source group */
        patch: operations["cabinetSourceGroupUpdate"];
        trace?: never;
    };
    "/cabinet/payouts/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Payout configuration */
        get: operations["cabinetPayoutsConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cabinet/payouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Balance, withdrawal requests and ledger history */
        get: operations["cabinetPayoutsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cabinet/payouts/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a withdrawal */
        post: operations["cabinetPayoutRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cabinet/payouts/requests/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel own pending withdrawal request */
        post: operations["cabinetPayoutCancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cabinet/referrals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Referral program info */
        get: operations["cabinetReferrals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cabinet/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notifications with unread counter */
        get: operations["cabinetNotificationsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cabinet/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark all notifications read */
        post: operations["cabinetNotificationsReadAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cabinet/notifications/{type}/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a single notification read */
        post: operations["cabinetNotificationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cabinet/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update own profile */
        put: operations["cabinetProfileUpdate"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/partners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List partners */
        get: operations["adminPartnersList"];
        put?: never;
        /** Create a partner (active immediately) */
        post: operations["adminPartnerCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/partners/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Partner detail with balance, ledger, withdrawals, accesses */
        get: operations["adminPartnerGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update partner (approve/block/rename) */
        patch: operations["adminPartnerUpdate"];
        trace?: never;
    };
    "/admin/partners/{id}/rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set partner's personal rate for an offer */
        post: operations["adminPartnerRate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["adminProjectsList"];
        put?: never;
        /** Create project */
        post: operations["adminProjectCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update project */
        patch: operations["adminProjectUpdate"];
        trace?: never;
    };
    "/admin/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List offers */
        get: operations["adminOffersList"];
        put?: never;
        /** Create offer (creates terms v1) */
        post: operations["adminOfferCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/offers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update offer card */
        patch: operations["adminOfferUpdate"];
        trace?: never;
    };
    "/admin/offers/{id}/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add new offer terms version (rate change) */
        post: operations["adminOfferTerms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/integration-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List integration keys (no secrets) */
        get: operations["adminIntegrationKeysList"];
        put?: never;
        /** Create integration key (secret shown once) */
        post: operations["adminIntegrationKeyCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/integration-keys/{keyId}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate integration key (secret shown once) */
        post: operations["adminIntegrationKeyRotate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/integration-keys/{keyId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate integration key */
        post: operations["adminIntegrationKeyDeactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/withdrawals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List withdrawal requests */
        get: operations["adminWithdrawalsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/withdrawals/{id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve or reject a pending withdrawal */
        post: operations["adminWithdrawalDecide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/withdrawals/{id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark approved withdrawal as paid */
        post: operations["adminWithdrawalPay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/finance/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Payout rules */
        get: operations["adminFinanceRulesGet"];
        /** Update payout rules */
        put: operations["adminFinanceRulesPut"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/finance/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wallet ledger (all partners) */
        get: operations["adminFinanceLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/finance/earnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Commission earnings */
        get: operations["adminFinanceEarnings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List announcements (including deleted) */
        get: operations["adminAnnouncementsList"];
        put?: never;
        /** Create announcement */
        post: operations["adminAnnouncementCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/announcements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft-delete announcement */
        delete: operations["adminAnnouncementDelete"];
        options?: never;
        head?: never;
        /** Update announcement (published included) */
        patch: operations["adminAnnouncementUpdate"];
        trace?: never;
    };
    "/admin/platform/branding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform branding */
        get: operations["adminBrandingGet"];
        /** Update platform branding */
        put: operations["adminBrandingPut"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit log */
        get: operations["adminAuditList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a signed project event */
        post: operations["integrationsEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            message: string;
        };
        RegisterRequest: {
            name: string;
            email: string;
            password: string;
            referral_code?: string;
        };
        UserMe: {
            id?: string;
            email?: string;
            name?: string;
            /** @enum {string} */
            role?: "partner" | "staff";
            is_approved?: boolean;
            is_blocked?: boolean;
            partner?: {
                referral_code?: string;
                /** Format: int64 */
                telegram_user_id?: number | null;
            } | null;
            staff?: {
                roles?: string[];
            } | null;
        };
        Balance: {
            /** Format: int64 */
            available_kopecks?: number;
            /** Format: int64 */
            reserved_kopecks?: number;
        };
        DayStats: {
            date?: string;
            clicks?: number;
            unique_clicks?: number;
            registrations?: number;
            first_payments?: number;
            /** Format: int64 */
            income_kopecks?: number;
        };
        SummaryResponse: {
            balance?: components["schemas"]["Balance"];
            income?: {
                /** Format: int64 */
                today_kopecks?: number;
                /** Format: int64 */
                week_kopecks?: number;
                /** Format: int64 */
                month_kopecks?: number;
                /** Format: int64 */
                all_kopecks?: number;
            };
            funnel?: {
                clicks?: number;
                unique_clicks?: number;
                registrations?: number;
                first_payments?: number;
                /** Format: int64 */
                income_kopecks?: number;
            };
            chart?: components["schemas"]["DayStats"][];
            active_offers?: {
                offer_id?: string;
                name?: string;
                rate_bps?: number;
                tracking_url?: string;
                clicks?: number;
                registrations?: number;
                /** Format: int64 */
                income_kopecks?: number;
            }[];
            revshare_percent_bps?: number;
            telegram?: {
                connected?: boolean;
            };
        };
        CabinetOffer: {
            offer_id?: string;
            project_id?: string;
            project_name?: string;
            project_logo_url?: string | null;
            name?: string;
            category?: string | null;
            description?: string | null;
            /** @enum {string} */
            status?: "active" | "available" | "pending" | "coming_soon";
            my_rate_bps?: number | null;
            epc?: number | null;
            cr?: number | null;
            my_tracking_url?: string | null;
        };
        OfferAgg: {
            /** Format: int64 */
            income_kopecks?: number;
            clicks?: number;
            unique_clicks?: number;
            registrations?: number;
            first_payments?: number;
        };
        HistoryItem: {
            id?: string;
            /** @enum {string} */
            kind?: "click" | "registration" | "payment" | "earning" | "reversal";
            /** Format: int64 */
            amount_kopecks?: number | null;
            /** Format: date-time */
            occurred_at?: string;
        };
        OfferStatsResponse: {
            offer?: components["schemas"]["OfferCard"];
            tracking_url?: string;
            summary?: {
                today?: components["schemas"]["OfferAgg"];
                week?: components["schemas"]["OfferAgg"];
                month?: components["schemas"]["OfferAgg"];
                all?: components["schemas"]["OfferAgg"];
            };
            chart?: components["schemas"]["DayStats"][];
            history?: components["schemas"]["HistoryItem"][];
        };
        SourceTotals: {
            /** Format: int64 */
            clicks?: number;
            /** Format: int64 */
            unique_clicks?: number;
            /** Format: int64 */
            registrations?: number;
            /** Format: int64 */
            first_payments?: number;
            /** Format: int64 */
            income_kopecks?: number;
        };
        Source: {
            id?: string;
            code?: string;
            name?: string;
            comment?: string | null;
            group_id?: string | null;
            group_name?: string | null;
            is_default?: boolean;
            is_active?: boolean;
            url?: string;
            totals?: components["schemas"]["SourceTotals"];
            totals_30d?: components["schemas"]["SourceTotals"];
            /** Format: date-time */
            created_at?: string;
        };
        SourceInput: {
            name: string;
            code?: string | null;
            comment?: string | null;
            group_id?: string | null;
            is_default?: boolean;
        };
        SourceUpdate: {
            name: string;
            code?: string | null;
            comment?: string | null;
            group_id?: string | null;
            is_active?: boolean;
            is_default?: boolean;
        };
        SourceGroup: {
            id?: string;
            name?: string;
            comment?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SourceGroupInput: {
            name: string;
            comment?: string | null;
        };
        WithdrawalRequest: {
            id?: string;
            partner_id?: string;
            /** Format: int64 */
            amount_kopecks?: number;
            /** @enum {string} */
            method?: "usdt" | "sbp";
            requisites?: string;
            bank?: string | null;
            /** Format: int64 */
            fee_kopecks?: number;
            usdt_amount?: number | null;
            rate?: number | null;
            /** @enum {string} */
            status?: "pending" | "approved" | "paid" | "rejected" | "cancelled";
            comment?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        LedgerEntry: {
            id?: string;
            type?: string;
            /** Format: int64 */
            amount_kopecks?: number;
            /** Format: int64 */
            balance_after_kopecks?: number;
            /** Format: date-time */
            created_at?: string;
        };
        PayoutRules: {
            /** Format: int64 */
            min_withdraw_kopecks?: number;
            usdt_rate?: number;
            /** Format: int64 */
            sbp_fee_flat_kopecks?: number;
            sbp_fee_percent_bps?: number;
            /** Format: date-time */
            updated_at?: string;
        };
        ReferralItem: {
            partner_id?: string;
            name?: string;
            email?: string | null;
            /** Format: date-time */
            joined_at?: string;
            /** Format: int64 */
            reward_kopecks?: number;
        };
        ReferralsResponse: {
            referral_code?: string;
            invite_url?: string;
            total_invited?: number;
            /** Format: int64 */
            total_reward_kopecks?: number;
            items?: components["schemas"]["ReferralItem"][];
        };
        NotificationItem: {
            id?: string;
            /** @enum {string} */
            type?: "announcement" | "personal";
            title?: string;
            body?: string;
            /** Format: date-time */
            created_at?: string;
            read?: boolean;
        };
        AdminPartner: {
            id?: string;
            name?: string;
            email?: string;
            is_approved?: boolean;
            is_blocked?: boolean;
            /** Format: int64 */
            balance_kopecks?: number;
            revshare_percent_bps?: number;
            rates?: {
                offer_id?: string;
                rate_bps?: number;
            }[];
            /** Format: date-time */
            created_at?: string;
        };
        AdminPartnerDetail: {
            partner?: components["schemas"]["AdminPartner"];
            balance?: components["schemas"]["Balance"];
            ledger?: components["schemas"]["LedgerEntry"][];
            withdrawals?: components["schemas"]["WithdrawalRequest"][];
            accesses?: {
                offer_id?: string;
                offer_name?: string;
                rate_bps?: number;
                status?: string;
            }[];
        };
        ProjectCard: {
            id?: string;
            slug?: string;
            name?: string;
            description?: string | null;
            destination_url?: string;
            is_active?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        OfferCard: {
            id?: string;
            project_id?: string;
            project_name?: string;
            name?: string;
            category?: string | null;
            description?: string | null;
            destination_url?: string | null;
            status?: string;
            current_rate_bps?: number;
            version?: number;
            /** Format: date-time */
            created_at?: string;
        };
        IntegrationKey: {
            key_id?: string;
            is_active?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            last_used_at?: string | null;
            secret_hint?: string;
        };
        IntegrationKeySecret: {
            key_id?: string;
            secret?: string;
        };
        AdminWithdrawal: components["schemas"]["WithdrawalRequest"] & {
            partner_name?: string;
            partner_email?: string;
        };
        AdminLedgerEntry: components["schemas"]["LedgerEntry"] & {
            partner_id?: string;
            partner_name?: string;
            comment?: string | null;
        };
        AdminEarning: {
            id?: string;
            partner_id?: string;
            offer_id?: string;
            /** Format: int64 */
            conversion_event_id?: number;
            rate_bps?: number;
            /** Format: int64 */
            amount_kopecks?: number;
            external_user_id?: string;
            reversed?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        Announcement: {
            id?: string;
            title?: string;
            body?: string;
            audience?: string;
            is_published?: boolean;
            /** Format: date-time */
            published_at?: string | null;
            /** Format: date-time */
            deleted_at?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        AnnouncementInput: {
            title?: string;
            body?: string;
            /** @enum {string} */
            audience?: "all" | "partners" | "staff" | "specific_partner";
            partner_ids?: string[];
        };
        Branding: {
            name?: string;
            telegram_url?: string | null;
            avatar_url?: string | null;
        };
        AuditEntry: {
            id?: string;
            actor_email?: string | null;
            action?: string;
            entity_type?: string;
            entity_id?: string;
            changes?: Record<string, never> | null;
            /** Format: date-time */
            created_at?: string;
        };
        EventInput: {
            event_id: string;
            /** @enum {string} */
            type: "registration.created" | "revenue.confirmed" | "revenue.reversed";
            /** Format: date-time */
            occurred_at: string;
            external_user_id: string;
            click_token?: string;
            external_payment_id?: string;
            /** Format: int64 */
            amount_kopecks?: number;
            /** @default RUB */
            currency: string;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Id: string;
        OfferId: string;
        SourceId: string;
        GroupId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user?: components["schemas"]["UserMe"];
                    };
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    authMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user?: components["schemas"]["UserMe"];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    authPasswordResetRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                };
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        reset_token?: string | null;
                    };
                };
            };
        };
    };
    authPasswordResetConfirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    new_password: string;
                };
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
        };
    };
    cabinetSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    cabinetOffersList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["CabinetOffer"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    cabinetOfferJoin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Joined */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        offer_id?: string;
                        rate_bps?: number;
                        tracking_url?: string;
                    };
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    cabinetOfferStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferStatsResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    cabinetOfferSourcesList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Source"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    cabinetOfferSourceCreate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: components["parameters"]["OfferId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    cabinetOfferSourceDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: components["parameters"]["OfferId"];
                sourceId: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    cabinetOfferSourceUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: components["parameters"]["OfferId"];
                sourceId: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    cabinetSourceGroupsList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["SourceGroup"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    cabinetSourceGroupCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceGroupInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceGroup"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    cabinetSourceGroupDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    cabinetSourceGroupUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceGroupInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceGroup"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    cabinetPayoutsConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoutRules"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    cabinetPayoutsList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        balance?: components["schemas"]["Balance"];
                        requests?: components["schemas"]["WithdrawalRequest"][];
                        history?: components["schemas"]["LedgerEntry"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    cabinetPayoutRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    method: "usdt" | "sbp";
                    /** Format: int64 */
                    amount_kopecks: number;
                    requisites: string;
                    bank?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawalRequest"];
                };
            };
            400: components["responses"]["Error"];
            402: components["responses"]["Error"];
        };
    };
    cabinetPayoutCancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawalRequest"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    cabinetReferrals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralsResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    cabinetNotificationsList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        unread_count?: number;
                        items?: components["schemas"]["NotificationItem"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    cabinetNotificationsReadAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    cabinetNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: "announcement" | "personal";
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    cabinetProfileUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    /** Format: int64 */
                    telegram_user_id?: number;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user?: components["schemas"]["UserMe"];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    adminPartnersList: {
        parameters: {
            query?: {
                search?: string;
                status?: "pending" | "active" | "blocked";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total?: number;
                        items?: components["schemas"]["AdminPartner"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    adminPartnerCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    email: string;
                    password: string;
                    commission_bps?: number;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        name?: string;
                        email?: string;
                    };
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    adminPartnerGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPartnerDetail"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    adminPartnerUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    email?: string;
                    password?: string;
                    is_approved?: boolean;
                    is_blocked?: boolean;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPartner"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    adminPartnerRate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    offer_id: string;
                    rate_bps: number;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        offer_id?: string;
                        rate_bps?: number;
                    };
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    adminProjectsList: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total?: number;
                        items?: components["schemas"]["ProjectCard"][];
                    };
                };
            };
        };
    };
    adminProjectCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    slug: string;
                    name: string;
                    description?: string;
                    destination_url: string;
                    is_active?: boolean;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectCard"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    adminProjectUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    description?: string;
                    destination_url?: string;
                    is_active?: boolean;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectCard"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    adminOffersList: {
        parameters: {
            query?: {
                project_id?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total?: number;
                        items?: components["schemas"]["OfferCard"][];
                    };
                };
            };
        };
    };
    adminOfferCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    project_id: string;
                    name: string;
                    category?: string;
                    description?: string;
                    destination_url?: string;
                    /**
                     * @default pending
                     * @enum {string}
                     */
                    status?: "active" | "available" | "pending" | "coming_soon";
                    rate_bps: number;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferCard"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    adminOfferUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    category?: string;
                    description?: string;
                    destination_url?: string;
                    /** @enum {string} */
                    status?: "active" | "available" | "pending" | "coming_soon";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferCard"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    adminOfferTerms: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    rate_bps: number;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version?: number;
                        rate_bps?: number;
                        /** Format: date-time */
                        effective_from?: string;
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    adminIntegrationKeysList: {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["IntegrationKey"][];
                    };
                };
            };
        };
    };
    adminIntegrationKeyCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    project_id: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationKeySecret"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    adminIntegrationKeyRotate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationKeySecret"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    adminIntegrationKeyDeactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    adminWithdrawalsList: {
        parameters: {
            query?: {
                status?: string;
                partner_id?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total?: number;
                        items?: components["schemas"]["AdminWithdrawal"][];
                    };
                };
            };
        };
    };
    adminWithdrawalDecide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "approved" | "rejected";
                    comment?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawalRequest"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    adminWithdrawalPay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    external_tx_id?: string;
                    comment?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawalRequest"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    adminFinanceRulesGet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoutRules"];
                };
            };
        };
    };
    adminFinanceRulesPut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    min_withdraw_kopecks?: number;
                    usdt_rate?: number;
                    /** Format: int64 */
                    sbp_fee_flat_kopecks?: number;
                    sbp_fee_percent_bps?: number;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoutRules"];
                };
            };
        };
    };
    adminFinanceLedger: {
        parameters: {
            query?: {
                partner_id?: string;
                from?: string;
                to?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total?: number;
                        items?: components["schemas"]["AdminLedgerEntry"][];
                    };
                };
            };
        };
    };
    adminFinanceEarnings: {
        parameters: {
            query?: {
                partner_id?: string;
                offer_id?: string;
                from?: string;
                to?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total?: number;
                        items?: components["schemas"]["AdminEarning"][];
                    };
                };
            };
        };
    };
    adminAnnouncementsList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Announcement"][];
                    };
                };
            };
        };
    };
    adminAnnouncementCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnouncementInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Announcement"];
                };
            };
        };
    };
    adminAnnouncementDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    adminAnnouncementUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnouncementInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Announcement"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    adminBrandingGet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branding"];
                };
            };
        };
    };
    adminBrandingPut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    telegram_url?: string;
                    avatar_url?: string | null;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branding"];
                };
            };
        };
    };
    adminAuditList: {
        parameters: {
            query?: {
                entity_type?: string;
                entity_id?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total?: number;
                        items?: components["schemas"]["AuditEntry"][];
                    };
                };
            };
        };
    };
    integrationsEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventInput"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "accepted" | "duplicate" | "ignored";
                        reason?: string | null;
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
}
