// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPartnerProfilesAdmin = `-- name: CountPartnerProfilesAdmin :one
SELECT count(*) FROM partner_profiles p
JOIN users u ON u.id = p.user_id
WHERE ($1 = '' OR u.name ILIKE '%' || $1 || '%' OR u.email ILIKE '%' || $1 || '%')
  AND ($2 = 'pending' OR $2 = '' OR ($2 = 'blocked' AND p.is_blocked) OR ($2 = 'active' AND NOT p.is_blocked AND p.is_approved))
`

type CountPartnerProfilesAdminParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) CountPartnerProfilesAdmin(ctx context.Context, arg CountPartnerProfilesAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPartnerProfilesAdmin, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReferralsByReferrer = `-- name: CountReferralsByReferrer :one
SELECT count(*) FROM partner_referrals WHERE referrer_partner_id = $1
`

func (q *Queries) CountReferralsByReferrer(ctx context.Context, referrerPartnerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countReferralsByReferrer, referrerPartnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPartnerProfile = `-- name: CreatePartnerProfile :one
INSERT INTO partner_profiles (user_id, referral_code, referred_by)
VALUES ($1, $2, $3) RETURNING id, user_id, referral_code, referred_by, is_approved, is_blocked, is_owner, is_admin, revshare_percent_bps, telegram_user_id, comment, legacy_kazik_partner_id, created_at, updated_at
`

type CreatePartnerProfileParams struct {
	UserID       string      `json:"user_id"`
	ReferralCode string      `json:"referral_code"`
	ReferredBy   pgtype.UUID `json:"referred_by"`
}

func (q *Queries) CreatePartnerProfile(ctx context.Context, arg CreatePartnerProfileParams) (PartnerProfile, error) {
	row := q.db.QueryRow(ctx, createPartnerProfile, arg.UserID, arg.ReferralCode, arg.ReferredBy)
	var i PartnerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.IsApproved,
		&i.IsBlocked,
		&i.IsOwner,
		&i.IsAdmin,
		&i.RevsharePercentBps,
		&i.TelegramUserID,
		&i.Comment,
		&i.LegacyKazikPartnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPartnerReferral = `-- name: CreatePartnerReferral :one
INSERT INTO partner_referrals (referrer_partner_id, invited_partner_id, referral_rate_bps)
VALUES ($1, $2, $3) RETURNING id, referrer_partner_id, invited_partner_id, referral_rate_bps, created_at
`

type CreatePartnerReferralParams struct {
	ReferrerPartnerID string `json:"referrer_partner_id"`
	InvitedPartnerID  string `json:"invited_partner_id"`
	ReferralRateBps   int32  `json:"referral_rate_bps"`
}

func (q *Queries) CreatePartnerReferral(ctx context.Context, arg CreatePartnerReferralParams) (PartnerReferral, error) {
	row := q.db.QueryRow(ctx, createPartnerReferral, arg.ReferrerPartnerID, arg.InvitedPartnerID, arg.ReferralRateBps)
	var i PartnerReferral
	err := row.Scan(
		&i.ID,
		&i.ReferrerPartnerID,
		&i.InvitedPartnerID,
		&i.ReferralRateBps,
		&i.CreatedAt,
	)
	return i, err
}

const createPartnerReferralClick = `-- name: CreatePartnerReferralClick :exec
INSERT INTO partner_referral_clicks (referrer_partner_id, ip, user_agent, referrer)
VALUES ($1, $2::inet, $3, $4)
`

type CreatePartnerReferralClickParams struct {
	ReferrerPartnerID string      `json:"referrer_partner_id"`
	Column2           string      `json:"column_2"`
	UserAgent         pgtype.Text `json:"user_agent"`
	Referrer          pgtype.Text `json:"referrer"`
}

func (q *Queries) CreatePartnerReferralClick(ctx context.Context, arg CreatePartnerReferralClickParams) error {
	_, err := q.db.Exec(ctx, createPartnerReferralClick,
		arg.ReferrerPartnerID,
		arg.Column2,
		arg.UserAgent,
		arg.Referrer,
	)
	return err
}

const createStaffRoleAssignment = `-- name: CreateStaffRoleAssignment :exec
INSERT INTO staff_role_assignments (user_id, role, project_id) VALUES ($1, $2, $3)
`

type CreateStaffRoleAssignmentParams struct {
	UserID    string      `json:"user_id"`
	Role      string      `json:"role"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) CreateStaffRoleAssignment(ctx context.Context, arg CreateStaffRoleAssignmentParams) error {
	_, err := q.db.Exec(ctx, createStaffRoleAssignment, arg.UserID, arg.Role, arg.ProjectID)
	return err
}

const getPartnerProfileByID = `-- name: GetPartnerProfileByID :one
SELECT id, user_id, referral_code, referred_by, is_approved, is_blocked, is_owner, is_admin, revshare_percent_bps, telegram_user_id, comment, legacy_kazik_partner_id, created_at, updated_at FROM partner_profiles WHERE id = $1
`

func (q *Queries) GetPartnerProfileByID(ctx context.Context, id string) (PartnerProfile, error) {
	row := q.db.QueryRow(ctx, getPartnerProfileByID, id)
	var i PartnerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.IsApproved,
		&i.IsBlocked,
		&i.IsOwner,
		&i.IsAdmin,
		&i.RevsharePercentBps,
		&i.TelegramUserID,
		&i.Comment,
		&i.LegacyKazikPartnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartnerProfileByReferralCode = `-- name: GetPartnerProfileByReferralCode :one
SELECT id, user_id, referral_code, referred_by, is_approved, is_blocked, is_owner, is_admin, revshare_percent_bps, telegram_user_id, comment, legacy_kazik_partner_id, created_at, updated_at FROM partner_profiles WHERE referral_code = $1
`

func (q *Queries) GetPartnerProfileByReferralCode(ctx context.Context, referralCode string) (PartnerProfile, error) {
	row := q.db.QueryRow(ctx, getPartnerProfileByReferralCode, referralCode)
	var i PartnerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.IsApproved,
		&i.IsBlocked,
		&i.IsOwner,
		&i.IsAdmin,
		&i.RevsharePercentBps,
		&i.TelegramUserID,
		&i.Comment,
		&i.LegacyKazikPartnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartnerProfileByUserID = `-- name: GetPartnerProfileByUserID :one
SELECT id, user_id, referral_code, referred_by, is_approved, is_blocked, is_owner, is_admin, revshare_percent_bps, telegram_user_id, comment, legacy_kazik_partner_id, created_at, updated_at FROM partner_profiles WHERE user_id = $1
`

func (q *Queries) GetPartnerProfileByUserID(ctx context.Context, userID string) (PartnerProfile, error) {
	row := q.db.QueryRow(ctx, getPartnerProfileByUserID, userID)
	var i PartnerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.IsApproved,
		&i.IsBlocked,
		&i.IsOwner,
		&i.IsAdmin,
		&i.RevsharePercentBps,
		&i.TelegramUserID,
		&i.Comment,
		&i.LegacyKazikPartnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartnerReferralByInvited = `-- name: GetPartnerReferralByInvited :one
SELECT id, referrer_partner_id, invited_partner_id, referral_rate_bps, created_at
FROM partner_referrals WHERE invited_partner_id = $1
`

func (q *Queries) GetPartnerReferralByInvited(ctx context.Context, invitedPartnerID string) (PartnerReferral, error) {
	row := q.db.QueryRow(ctx, getPartnerReferralByInvited, invitedPartnerID)
	var i PartnerReferral
	err := row.Scan(
		&i.ID,
		&i.ReferrerPartnerID,
		&i.InvitedPartnerID,
		&i.ReferralRateBps,
		&i.CreatedAt,
	)
	return i, err
}

const getStaffRolesByUserID = `-- name: GetStaffRolesByUserID :many
SELECT role, project_id FROM staff_role_assignments WHERE user_id = $1
`

type GetStaffRolesByUserIDRow struct {
	Role      string      `json:"role"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) GetStaffRolesByUserID(ctx context.Context, userID string) ([]GetStaffRolesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getStaffRolesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStaffRolesByUserIDRow
	for rows.Next() {
		var i GetStaffRolesByUserIDRow
		if err := rows.Scan(&i.Role, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, role, is_active, created_at, updated_at FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID        string             `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Role      string             `json:"role"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPartnerID = `-- name: GetUserByPartnerID :one
SELECT u.id, u.email, u.name, u.role, u.is_active, u.created_at, u.updated_at
FROM users u JOIN partner_profiles p ON p.user_id = u.id WHERE p.id = $1
`

type GetUserByPartnerIDRow struct {
	ID        string             `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Role      string             `json:"role"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByPartnerID(ctx context.Context, id string) (GetUserByPartnerIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByPartnerID, id)
	var i GetUserByPartnerIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserIDByPartnerID = `-- name: GetUserIDByPartnerID :one
SELECT user_id FROM partner_profiles WHERE id = $1
`

func (q *Queries) GetUserIDByPartnerID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getUserIDByPartnerID, id)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const listAccessRatesAll = `-- name: ListAccessRatesAll :many
SELECT a.id, a.partner_id, a.offer_id, a.rate_bps, a.status
FROM partner_offer_accesses a
ORDER BY a.created_at
`

type ListAccessRatesAllRow struct {
	ID        string `json:"id"`
	PartnerID string `json:"partner_id"`
	OfferID   string `json:"offer_id"`
	RateBps   int32  `json:"rate_bps"`
	Status    string `json:"status"`
}

func (q *Queries) ListAccessRatesAll(ctx context.Context) ([]ListAccessRatesAllRow, error) {
	rows, err := q.db.Query(ctx, listAccessRatesAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccessRatesAllRow
	for rows.Next() {
		var i ListAccessRatesAllRow
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.OfferID,
			&i.RateBps,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerProfilesAdmin = `-- name: ListPartnerProfilesAdmin :many
SELECT p.id, p.user_id, p.referral_code, p.is_approved, p.is_blocked, p.revshare_percent_bps, p.telegram_user_id, p.comment, p.created_at,
       u.email, u.name,
       w.available_kopecks, w.reserved_kopecks
FROM partner_profiles p
JOIN users u ON u.id = p.user_id
JOIN wallets w ON w.partner_id = p.id
WHERE ($1 = '' OR u.name ILIKE '%' || $1 || '%' OR u.email ILIKE '%' || $1 || '%')
  AND ($2 = 'pending' OR $2 = '' OR ($2 = 'blocked' AND p.is_blocked) OR ($2 = 'active' AND NOT p.is_blocked AND p.is_approved))
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $4
`

type ListPartnerProfilesAdminParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListPartnerProfilesAdminRow struct {
	ID                 string             `json:"id"`
	UserID             string             `json:"user_id"`
	ReferralCode       string             `json:"referral_code"`
	IsApproved         bool               `json:"is_approved"`
	IsBlocked          bool               `json:"is_blocked"`
	RevsharePercentBps int32              `json:"revshare_percent_bps"`
	TelegramUserID     pgtype.Int8        `json:"telegram_user_id"`
	Comment            pgtype.Text        `json:"comment"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Email              string             `json:"email"`
	Name               string             `json:"name"`
	AvailableKopecks   int64              `json:"available_kopecks"`
	ReservedKopecks    int64              `json:"reserved_kopecks"`
}

func (q *Queries) ListPartnerProfilesAdmin(ctx context.Context, arg ListPartnerProfilesAdminParams) ([]ListPartnerProfilesAdminRow, error) {
	rows, err := q.db.Query(ctx, listPartnerProfilesAdmin,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartnerProfilesAdminRow
	for rows.Next() {
		var i ListPartnerProfilesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ReferralCode,
			&i.IsApproved,
			&i.IsBlocked,
			&i.RevsharePercentBps,
			&i.TelegramUserID,
			&i.Comment,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
			&i.AvailableKopecks,
			&i.ReservedKopecks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferralsByReferrer = `-- name: ListReferralsByReferrer :many
SELECT r.id, r.referrer_partner_id, r.invited_partner_id, r.referral_rate_bps, r.created_at,
       u.name, u.email
FROM partner_referrals r
JOIN partner_profiles p ON p.id = r.invited_partner_id
JOIN users u ON u.id = p.user_id
WHERE r.referrer_partner_id = $1
ORDER BY r.created_at DESC
`

type ListReferralsByReferrerRow struct {
	ID                string             `json:"id"`
	ReferrerPartnerID string             `json:"referrer_partner_id"`
	InvitedPartnerID  string             `json:"invited_partner_id"`
	ReferralRateBps   int32              `json:"referral_rate_bps"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Name              string             `json:"name"`
	Email             string             `json:"email"`
}

func (q *Queries) ListReferralsByReferrer(ctx context.Context, referrerPartnerID string) ([]ListReferralsByReferrerRow, error) {
	rows, err := q.db.Query(ctx, listReferralsByReferrer, referrerPartnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReferralsByReferrerRow
	for rows.Next() {
		var i ListReferralsByReferrerRow
		if err := rows.Scan(
			&i.ID,
			&i.ReferrerPartnerID,
			&i.InvitedPartnerID,
			&i.ReferralRateBps,
			&i.CreatedAt,
			&i.Name,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPartnerRevShare = `-- name: SetPartnerRevShare :exec
UPDATE partner_profiles SET revshare_percent_bps = $2, updated_at = now() WHERE id = $1
`

type SetPartnerRevShareParams struct {
	ID                 string `json:"id"`
	RevsharePercentBps int32  `json:"revshare_percent_bps"`
}

func (q *Queries) SetPartnerRevShare(ctx context.Context, arg SetPartnerRevShareParams) error {
	_, err := q.db.Exec(ctx, setPartnerRevShare, arg.ID, arg.RevsharePercentBps)
	return err
}

const updatePartnerProfile = `-- name: UpdatePartnerProfile :one
UPDATE partner_profiles
SET is_approved = COALESCE($1, is_approved),
    is_blocked = COALESCE($2, is_blocked),
    revshare_percent_bps = COALESCE($3, revshare_percent_bps),
    telegram_user_id = COALESCE($4, telegram_user_id),
    comment = COALESCE($5, comment),
    updated_at = now()
WHERE id = $6
RETURNING id, user_id, referral_code, referred_by, is_approved, is_blocked, is_owner, is_admin, revshare_percent_bps, telegram_user_id, comment, legacy_kazik_partner_id, created_at, updated_at
`

type UpdatePartnerProfileParams struct {
	IsApproved         pgtype.Bool `json:"is_approved"`
	IsBlocked          pgtype.Bool `json:"is_blocked"`
	RevsharePercentBps pgtype.Int4 `json:"revshare_percent_bps"`
	TelegramUserID     pgtype.Int8 `json:"telegram_user_id"`
	Comment            pgtype.Text `json:"comment"`
	ID                 string      `json:"id"`
}

func (q *Queries) UpdatePartnerProfile(ctx context.Context, arg UpdatePartnerProfileParams) (PartnerProfile, error) {
	row := q.db.QueryRow(ctx, updatePartnerProfile,
		arg.IsApproved,
		arg.IsBlocked,
		arg.RevsharePercentBps,
		arg.TelegramUserID,
		arg.Comment,
		arg.ID,
	)
	var i PartnerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.IsApproved,
		&i.IsBlocked,
		&i.IsOwner,
		&i.IsAdmin,
		&i.RevsharePercentBps,
		&i.TelegramUserID,
		&i.Comment,
		&i.LegacyKazikPartnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = COALESCE($1, name),
    email = COALESCE($2, email),
    is_active = COALESCE($3, is_active),
    updated_at = now()
WHERE id = $4
RETURNING id, email, name, role, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	Name     pgtype.Text `json:"name"`
	Email    pgtype.Text `json:"email"`
	IsActive pgtype.Bool `json:"is_active"`
	ID       string      `json:"id"`
}

type UpdateUserRow struct {
	ID        string             `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Role      string             `json:"role"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.IsActive,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password = $2, updated_at = now() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       string      `json:"id"`
	Password pgtype.Text `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}
