// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadUserNotifications = `-- name: CountUnreadUserNotifications :one
SELECT count(*) FROM user_notifications WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadUserNotifications(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadUserNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAnnouncement = `-- name: GetAnnouncement :one
SELECT id, title, body, audience, is_published, published_at, created_by, created_at, updated_at, deleted_at
FROM announcements WHERE id = $1
`

func (q *Queries) GetAnnouncement(ctx context.Context, id string) (Announcement, error) {
	row := q.db.QueryRow(ctx, getAnnouncement, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Audience,
		&i.IsPublished,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAnnouncementRead = `-- name: GetAnnouncementRead :one
SELECT id, announcement_id, reader_user_id, read_at FROM announcement_reads WHERE announcement_id = $1 AND reader_user_id = $2
`

type GetAnnouncementReadParams struct {
	AnnouncementID string `json:"announcement_id"`
	ReaderUserID   string `json:"reader_user_id"`
}

func (q *Queries) GetAnnouncementRead(ctx context.Context, arg GetAnnouncementReadParams) (AnnouncementRead, error) {
	row := q.db.QueryRow(ctx, getAnnouncementRead, arg.AnnouncementID, arg.ReaderUserID)
	var i AnnouncementRead
	err := row.Scan(
		&i.ID,
		&i.AnnouncementID,
		&i.ReaderUserID,
		&i.ReadAt,
	)
	return i, err
}

const insertAnnouncement = `-- name: InsertAnnouncement :one
INSERT INTO announcements (title, body, audience, created_by)
VALUES ($1, $2, $3, $4) RETURNING id, title, body, audience, is_published, published_at, created_by, created_at, updated_at, deleted_at
`

type InsertAnnouncementParams struct {
	Title     string      `json:"title"`
	Body      string      `json:"body"`
	Audience  string      `json:"audience"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) InsertAnnouncement(ctx context.Context, arg InsertAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, insertAnnouncement,
		arg.Title,
		arg.Body,
		arg.Audience,
		arg.CreatedBy,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Audience,
		&i.IsPublished,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertAnnouncementAudience = `-- name: InsertAnnouncementAudience :exec
INSERT INTO announcement_audiences (announcement_id, partner_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type InsertAnnouncementAudienceParams struct {
	AnnouncementID string      `json:"announcement_id"`
	PartnerID      pgtype.UUID `json:"partner_id"`
}

func (q *Queries) InsertAnnouncementAudience(ctx context.Context, arg InsertAnnouncementAudienceParams) error {
	_, err := q.db.Exec(ctx, insertAnnouncementAudience, arg.AnnouncementID, arg.PartnerID)
	return err
}

const insertAnnouncementRead = `-- name: InsertAnnouncementRead :exec
INSERT INTO announcement_reads (announcement_id, reader_user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type InsertAnnouncementReadParams struct {
	AnnouncementID string `json:"announcement_id"`
	ReaderUserID   string `json:"reader_user_id"`
}

func (q *Queries) InsertAnnouncementRead(ctx context.Context, arg InsertAnnouncementReadParams) error {
	_, err := q.db.Exec(ctx, insertAnnouncementRead, arg.AnnouncementID, arg.ReaderUserID)
	return err
}

const insertUserNotification = `-- name: InsertUserNotification :exec
INSERT INTO user_notifications (user_id, type, title, body, metadata)
VALUES ($1, $2, $3, $4, $5)
`

type InsertUserNotificationParams struct {
	UserID   string `json:"user_id"`
	Type     string `json:"type"`
	Title    string `json:"title"`
	Body     string `json:"body"`
	Metadata []byte `json:"metadata"`
}

func (q *Queries) InsertUserNotification(ctx context.Context, arg InsertUserNotificationParams) error {
	_, err := q.db.Exec(ctx, insertUserNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Metadata,
	)
	return err
}

const listAnnouncementAudiencePartnerIDs = `-- name: ListAnnouncementAudiencePartnerIDs :many
SELECT partner_id FROM announcement_audiences WHERE announcement_id = $1
`

func (q *Queries) ListAnnouncementAudiencePartnerIDs(ctx context.Context, announcementID string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAnnouncementAudiencePartnerIDs, announcementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var partner_id pgtype.UUID
		if err := rows.Scan(&partner_id); err != nil {
			return nil, err
		}
		items = append(items, partner_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT id, title, body, audience, is_published, published_at, created_by, created_at, updated_at, deleted_at
FROM announcements ORDER BY created_at DESC
`

func (q *Queries) ListAnnouncements(ctx context.Context) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listAnnouncements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Announcement
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Audience,
			&i.IsPublished,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNotifications = `-- name: ListUserNotifications :many
SELECT id, user_id, type, title, body, metadata, read_at, created_at
FROM user_notifications WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListUserNotificationsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]UserNotification, error) {
	rows, err := q.db.Query(ctx, listUserNotifications, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserNotification
	for rows.Next() {
		var i UserNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Metadata,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleAnnouncements = `-- name: ListVisibleAnnouncements :many
SELECT id, title, body, audience, is_published, published_at, created_by, created_at, updated_at, deleted_at
FROM announcements
WHERE is_published AND deleted_at IS NULL
ORDER BY published_at DESC LIMIT 100
`

func (q *Queries) ListVisibleAnnouncements(ctx context.Context) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listVisibleAnnouncements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Announcement
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Audience,
			&i.IsPublished,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllUserNotificationsRead = `-- name: MarkAllUserNotificationsRead :exec
UPDATE user_notifications SET read_at = now() WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllUserNotificationsRead(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markAllUserNotificationsRead, userID)
	return err
}

const markUserNotificationRead = `-- name: MarkUserNotificationRead :exec
UPDATE user_notifications SET read_at = now() WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkUserNotificationReadParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) MarkUserNotificationRead(ctx context.Context, arg MarkUserNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markUserNotificationRead, arg.ID, arg.UserID)
	return err
}

const markVisibleAnnouncementsRead = `-- name: MarkVisibleAnnouncementsRead :exec
INSERT INTO announcement_reads (announcement_id, reader_user_id)
SELECT a.id, $1::uuid FROM announcements a
WHERE a.is_published AND a.deleted_at IS NULL
  AND (a.audience IN ('all', 'partners', 'staff') OR
       EXISTS (SELECT 1 FROM announcement_audiences aa WHERE aa.announcement_id = a.id AND aa.partner_id = $2::uuid))
ON CONFLICT DO NOTHING
`

type MarkVisibleAnnouncementsReadParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) MarkVisibleAnnouncementsRead(ctx context.Context, arg MarkVisibleAnnouncementsReadParams) error {
	_, err := q.db.Exec(ctx, markVisibleAnnouncementsRead, arg.Column1, arg.Column2)
	return err
}

const publishAnnouncement = `-- name: PublishAnnouncement :one
UPDATE announcements SET is_published = true, published_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, title, body, audience, is_published, published_at, created_by, created_at, updated_at, deleted_at
`

func (q *Queries) PublishAnnouncement(ctx context.Context, id string) (Announcement, error) {
	row := q.db.QueryRow(ctx, publishAnnouncement, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Audience,
		&i.IsPublished,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const replaceAnnouncementAudiences = `-- name: ReplaceAnnouncementAudiences :exec
DELETE FROM announcement_audiences WHERE announcement_id = $1
`

func (q *Queries) ReplaceAnnouncementAudiences(ctx context.Context, announcementID string) error {
	_, err := q.db.Exec(ctx, replaceAnnouncementAudiences, announcementID)
	return err
}

const softDeleteAnnouncement = `-- name: SoftDeleteAnnouncement :exec
UPDATE announcements SET deleted_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteAnnouncement(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteAnnouncement, id)
	return err
}

const updateAnnouncement = `-- name: UpdateAnnouncement :one
UPDATE announcements
SET title = COALESCE($1, title),
    body = COALESCE($2, body),
    audience = COALESCE($3, audience),
    updated_at = now()
WHERE id = $4
RETURNING id, title, body, audience, is_published, published_at, created_by, created_at, updated_at, deleted_at
`

type UpdateAnnouncementParams struct {
	Title    pgtype.Text `json:"title"`
	Body     pgtype.Text `json:"body"`
	Audience pgtype.Text `json:"audience"`
	ID       string      `json:"id"`
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, updateAnnouncement,
		arg.Title,
		arg.Body,
		arg.Audience,
		arg.ID,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Audience,
		&i.IsPublished,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
