// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeReserve = `-- name: ConsumeReserve :one
UPDATE wallets
SET reserved_kopecks = reserved_kopecks - $2, updated_at = now()
WHERE id = $1 AND reserved_kopecks >= $2
RETURNING id, partner_id, available_kopecks, reserved_kopecks, updated_at
`

type ConsumeReserveParams struct {
	ID              string `json:"id"`
	ReservedKopecks int64  `json:"reserved_kopecks"`
}

type ConsumeReserveRow struct {
	ID               string             `json:"id"`
	PartnerID        string             `json:"partner_id"`
	AvailableKopecks int64              `json:"available_kopecks"`
	ReservedKopecks  int64              `json:"reserved_kopecks"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ConsumeReserve(ctx context.Context, arg ConsumeReserveParams) (ConsumeReserveRow, error) {
	row := q.db.QueryRow(ctx, consumeReserve, arg.ID, arg.ReservedKopecks)
	var i ConsumeReserveRow
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AvailableKopecks,
		&i.ReservedKopecks,
		&i.UpdatedAt,
	)
	return i, err
}

const countEarningsAdmin = `-- name: CountEarningsAdmin :one
SELECT count(*) FROM commission_earnings e
WHERE ($1 = '' OR e.partner_id = $1::uuid)
  AND ($2 = '' OR e.offer_id = $2::uuid)
  AND ($3::timestamptz IS NULL OR e.created_at >= $3)
  AND ($4::timestamptz IS NULL OR e.created_at <= $4)
`

type CountEarningsAdminParams struct {
	Column1 interface{}        `json:"column_1"`
	Column2 interface{}        `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
	Column4 pgtype.Timestamptz `json:"column_4"`
}

func (q *Queries) CountEarningsAdmin(ctx context.Context, arg CountEarningsAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEarningsAdmin,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLedgerAdmin = `-- name: CountLedgerAdmin :one
SELECT count(*) FROM wallet_ledger_entries l
JOIN wallets w ON w.id = l.wallet_id
WHERE ($1 = '' OR w.partner_id = $1::uuid)
  AND ($2::timestamptz IS NULL OR l.created_at >= $2)
  AND ($3::timestamptz IS NULL OR l.created_at <= $3)
`

type CountLedgerAdminParams struct {
	Column1 interface{}        `json:"column_1"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
}

func (q *Queries) CountLedgerAdmin(ctx context.Context, arg CountLedgerAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLedgerAdmin, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (partner_id) VALUES ($1) RETURNING id, partner_id, available_kopecks, reserved_kopecks, created_at, updated_at
`

func (q *Queries) CreateWallet(ctx context.Context, partnerID string) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, partnerID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AvailableKopecks,
		&i.ReservedKopecks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const creditWallet = `-- name: CreditWallet :one
UPDATE wallets
SET available_kopecks = available_kopecks + $2, updated_at = now()
WHERE id = $1
RETURNING id, partner_id, available_kopecks, reserved_kopecks, updated_at
`

type CreditWalletParams struct {
	ID               string `json:"id"`
	AvailableKopecks int64  `json:"available_kopecks"`
}

type CreditWalletRow struct {
	ID               string             `json:"id"`
	PartnerID        string             `json:"partner_id"`
	AvailableKopecks int64              `json:"available_kopecks"`
	ReservedKopecks  int64              `json:"reserved_kopecks"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreditWallet(ctx context.Context, arg CreditWalletParams) (CreditWalletRow, error) {
	row := q.db.QueryRow(ctx, creditWallet, arg.ID, arg.AvailableKopecks)
	var i CreditWalletRow
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AvailableKopecks,
		&i.ReservedKopecks,
		&i.UpdatedAt,
	)
	return i, err
}

const getEarningByConversion = `-- name: GetEarningByConversion :one
SELECT id, conversion_event_id, partner_id, offer_id, tracking_link_id, rate_bps, amount_kopecks, external_user_id, reversed_at, created_at
FROM commission_earnings WHERE conversion_event_id = $1
`

func (q *Queries) GetEarningByConversion(ctx context.Context, conversionEventID int64) (CommissionEarning, error) {
	row := q.db.QueryRow(ctx, getEarningByConversion, conversionEventID)
	var i CommissionEarning
	err := row.Scan(
		&i.ID,
		&i.ConversionEventID,
		&i.PartnerID,
		&i.OfferID,
		&i.TrackingLinkID,
		&i.RateBps,
		&i.AmountKopecks,
		&i.ExternalUserID,
		&i.ReversedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRewardByEarning = `-- name: GetRewardByEarning :one
SELECT id, commission_earning_id, partner_referral_id, referrer_partner_id, invited_partner_id, referral_rate_bps, amount_kopecks, reversed_at, created_at
FROM referral_rewards WHERE commission_earning_id = $1
`

func (q *Queries) GetRewardByEarning(ctx context.Context, commissionEarningID string) (ReferralReward, error) {
	row := q.db.QueryRow(ctx, getRewardByEarning, commissionEarningID)
	var i ReferralReward
	err := row.Scan(
		&i.ID,
		&i.CommissionEarningID,
		&i.PartnerReferralID,
		&i.ReferrerPartnerID,
		&i.InvitedPartnerID,
		&i.ReferralRateBps,
		&i.AmountKopecks,
		&i.ReversedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletByID = `-- name: GetWalletByID :one
SELECT id, partner_id, available_kopecks, reserved_kopecks, created_at, updated_at FROM wallets WHERE id = $1
`

func (q *Queries) GetWalletByID(ctx context.Context, id string) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByID, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AvailableKopecks,
		&i.ReservedKopecks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByPartnerID = `-- name: GetWalletByPartnerID :one
SELECT id, partner_id, available_kopecks, reserved_kopecks, created_at, updated_at FROM wallets WHERE partner_id = $1
`

func (q *Queries) GetWalletByPartnerID(ctx context.Context, partnerID string) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByPartnerID, partnerID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AvailableKopecks,
		&i.ReservedKopecks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCommissionEarning = `-- name: InsertCommissionEarning :one
INSERT INTO commission_earnings (conversion_event_id, partner_id, offer_id, tracking_link_id, rate_bps, amount_kopecks, external_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, conversion_event_id, partner_id, offer_id, tracking_link_id, rate_bps, amount_kopecks, external_user_id, reversed_at, created_at
`

type InsertCommissionEarningParams struct {
	ConversionEventID int64       `json:"conversion_event_id"`
	PartnerID         string      `json:"partner_id"`
	OfferID           string      `json:"offer_id"`
	TrackingLinkID    pgtype.UUID `json:"tracking_link_id"`
	RateBps           int32       `json:"rate_bps"`
	AmountKopecks     int64       `json:"amount_kopecks"`
	ExternalUserID    string      `json:"external_user_id"`
}

func (q *Queries) InsertCommissionEarning(ctx context.Context, arg InsertCommissionEarningParams) (CommissionEarning, error) {
	row := q.db.QueryRow(ctx, insertCommissionEarning,
		arg.ConversionEventID,
		arg.PartnerID,
		arg.OfferID,
		arg.TrackingLinkID,
		arg.RateBps,
		arg.AmountKopecks,
		arg.ExternalUserID,
	)
	var i CommissionEarning
	err := row.Scan(
		&i.ID,
		&i.ConversionEventID,
		&i.PartnerID,
		&i.OfferID,
		&i.TrackingLinkID,
		&i.RateBps,
		&i.AmountKopecks,
		&i.ExternalUserID,
		&i.ReversedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
INSERT INTO wallet_ledger_entries (wallet_id, type, amount_kopecks, balance_after_kopecks, ref_conversion_event_id, ref_withdrawal_id, ref_referral_reward_id, comment)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, wallet_id, type, amount_kopecks, balance_after_kopecks, created_at
`

type InsertLedgerEntryParams struct {
	WalletID             string      `json:"wallet_id"`
	Type                 string      `json:"type"`
	AmountKopecks        int64       `json:"amount_kopecks"`
	BalanceAfterKopecks  int64       `json:"balance_after_kopecks"`
	RefConversionEventID pgtype.Int8 `json:"ref_conversion_event_id"`
	RefWithdrawalID      pgtype.UUID `json:"ref_withdrawal_id"`
	RefReferralRewardID  pgtype.UUID `json:"ref_referral_reward_id"`
	Comment              pgtype.Text `json:"comment"`
}

type InsertLedgerEntryRow struct {
	ID                  int64              `json:"id"`
	WalletID            string             `json:"wallet_id"`
	Type                string             `json:"type"`
	AmountKopecks       int64              `json:"amount_kopecks"`
	BalanceAfterKopecks int64              `json:"balance_after_kopecks"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (InsertLedgerEntryRow, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.WalletID,
		arg.Type,
		arg.AmountKopecks,
		arg.BalanceAfterKopecks,
		arg.RefConversionEventID,
		arg.RefWithdrawalID,
		arg.RefReferralRewardID,
		arg.Comment,
	)
	var i InsertLedgerEntryRow
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Type,
		&i.AmountKopecks,
		&i.BalanceAfterKopecks,
		&i.CreatedAt,
	)
	return i, err
}

const insertReferralReward = `-- name: InsertReferralReward :one
INSERT INTO referral_rewards (commission_earning_id, partner_referral_id, referrer_partner_id, invited_partner_id, referral_rate_bps, amount_kopecks)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, commission_earning_id, partner_referral_id, referrer_partner_id, invited_partner_id, referral_rate_bps, amount_kopecks, reversed_at, created_at
`

type InsertReferralRewardParams struct {
	CommissionEarningID string `json:"commission_earning_id"`
	PartnerReferralID   string `json:"partner_referral_id"`
	ReferrerPartnerID   string `json:"referrer_partner_id"`
	InvitedPartnerID    string `json:"invited_partner_id"`
	ReferralRateBps     int32  `json:"referral_rate_bps"`
	AmountKopecks       int64  `json:"amount_kopecks"`
}

func (q *Queries) InsertReferralReward(ctx context.Context, arg InsertReferralRewardParams) (ReferralReward, error) {
	row := q.db.QueryRow(ctx, insertReferralReward,
		arg.CommissionEarningID,
		arg.PartnerReferralID,
		arg.ReferrerPartnerID,
		arg.InvitedPartnerID,
		arg.ReferralRateBps,
		arg.AmountKopecks,
	)
	var i ReferralReward
	err := row.Scan(
		&i.ID,
		&i.CommissionEarningID,
		&i.PartnerReferralID,
		&i.ReferrerPartnerID,
		&i.InvitedPartnerID,
		&i.ReferralRateBps,
		&i.AmountKopecks,
		&i.ReversedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listEarningsAdmin = `-- name: ListEarningsAdmin :many
SELECT e.id, e.conversion_event_id, e.partner_id, e.offer_id, e.tracking_link_id, e.rate_bps, e.amount_kopecks, e.external_user_id, e.reversed_at, e.created_at
FROM commission_earnings e
WHERE ($1 = '' OR e.partner_id = $1::uuid)
  AND ($2 = '' OR e.offer_id = $2::uuid)
  AND ($3::timestamptz IS NULL OR e.created_at >= $3)
  AND ($4::timestamptz IS NULL OR e.created_at <= $4)
ORDER BY e.created_at DESC LIMIT $5 OFFSET $6
`

type ListEarningsAdminParams struct {
	Column1 interface{}        `json:"column_1"`
	Column2 interface{}        `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
	Column4 pgtype.Timestamptz `json:"column_4"`
	Limit   int32              `json:"limit"`
	Offset  int32              `json:"offset"`
}

func (q *Queries) ListEarningsAdmin(ctx context.Context, arg ListEarningsAdminParams) ([]CommissionEarning, error) {
	rows, err := q.db.Query(ctx, listEarningsAdmin,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommissionEarning
	for rows.Next() {
		var i CommissionEarning
		if err := rows.Scan(
			&i.ID,
			&i.ConversionEventID,
			&i.PartnerID,
			&i.OfferID,
			&i.TrackingLinkID,
			&i.RateBps,
			&i.AmountKopecks,
			&i.ExternalUserID,
			&i.ReversedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerAdmin = `-- name: ListLedgerAdmin :many
SELECT l.id, l.wallet_id, l.type, l.amount_kopecks, l.balance_after_kopecks, l.comment, l.created_at,
       w.partner_id, u.name AS partner_name
FROM wallet_ledger_entries l
JOIN wallets w ON w.id = l.wallet_id
JOIN partner_profiles p ON p.id = w.partner_id
JOIN users u ON u.id = p.user_id
WHERE ($1 = '' OR w.partner_id = $1::uuid)
  AND ($2::timestamptz IS NULL OR l.created_at >= $2)
  AND ($3::timestamptz IS NULL OR l.created_at <= $3)
ORDER BY l.created_at DESC LIMIT $4 OFFSET $5
`

type ListLedgerAdminParams struct {
	Column1 interface{}        `json:"column_1"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
	Limit   int32              `json:"limit"`
	Offset  int32              `json:"offset"`
}

type ListLedgerAdminRow struct {
	ID                  int64              `json:"id"`
	WalletID            string             `json:"wallet_id"`
	Type                string             `json:"type"`
	AmountKopecks       int64              `json:"amount_kopecks"`
	BalanceAfterKopecks int64              `json:"balance_after_kopecks"`
	Comment             pgtype.Text        `json:"comment"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	PartnerID           string             `json:"partner_id"`
	PartnerName         string             `json:"partner_name"`
}

func (q *Queries) ListLedgerAdmin(ctx context.Context, arg ListLedgerAdminParams) ([]ListLedgerAdminRow, error) {
	rows, err := q.db.Query(ctx, listLedgerAdmin,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLedgerAdminRow
	for rows.Next() {
		var i ListLedgerAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Type,
			&i.AmountKopecks,
			&i.BalanceAfterKopecks,
			&i.Comment,
			&i.CreatedAt,
			&i.PartnerID,
			&i.PartnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerByWallet = `-- name: ListLedgerByWallet :many
SELECT id, wallet_id, type, amount_kopecks, balance_after_kopecks, ref_conversion_event_id, ref_withdrawal_id, ref_referral_reward_id, comment, created_at
FROM wallet_ledger_entries WHERE wallet_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListLedgerByWalletParams struct {
	WalletID string `json:"wallet_id"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) ListLedgerByWallet(ctx context.Context, arg ListLedgerByWalletParams) ([]WalletLedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerByWallet, arg.WalletID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalletLedgerEntry
	for rows.Next() {
		var i WalletLedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Type,
			&i.AmountKopecks,
			&i.BalanceAfterKopecks,
			&i.RefConversionEventID,
			&i.RefWithdrawalID,
			&i.RefReferralRewardID,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseReserve = `-- name: ReleaseReserve :one
UPDATE wallets
SET available_kopecks = available_kopecks + $2, reserved_kopecks = reserved_kopecks - $2, updated_at = now()
WHERE id = $1 AND reserved_kopecks >= $2
RETURNING id, partner_id, available_kopecks, reserved_kopecks, updated_at
`

type ReleaseReserveParams struct {
	ID               string `json:"id"`
	AvailableKopecks int64  `json:"available_kopecks"`
}

type ReleaseReserveRow struct {
	ID               string             `json:"id"`
	PartnerID        string             `json:"partner_id"`
	AvailableKopecks int64              `json:"available_kopecks"`
	ReservedKopecks  int64              `json:"reserved_kopecks"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ReleaseReserve(ctx context.Context, arg ReleaseReserveParams) (ReleaseReserveRow, error) {
	row := q.db.QueryRow(ctx, releaseReserve, arg.ID, arg.AvailableKopecks)
	var i ReleaseReserveRow
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AvailableKopecks,
		&i.ReservedKopecks,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveWithdrawal = `-- name: ReserveWithdrawal :one
UPDATE wallets
SET available_kopecks = available_kopecks - $2, reserved_kopecks = reserved_kopecks + $2, updated_at = now()
WHERE id = $1 AND available_kopecks >= $2
RETURNING id, partner_id, available_kopecks, reserved_kopecks, updated_at
`

type ReserveWithdrawalParams struct {
	ID               string `json:"id"`
	AvailableKopecks int64  `json:"available_kopecks"`
}

type ReserveWithdrawalRow struct {
	ID               string             `json:"id"`
	PartnerID        string             `json:"partner_id"`
	AvailableKopecks int64              `json:"available_kopecks"`
	ReservedKopecks  int64              `json:"reserved_kopecks"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ReserveWithdrawal(ctx context.Context, arg ReserveWithdrawalParams) (ReserveWithdrawalRow, error) {
	row := q.db.QueryRow(ctx, reserveWithdrawal, arg.ID, arg.AvailableKopecks)
	var i ReserveWithdrawalRow
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AvailableKopecks,
		&i.ReservedKopecks,
		&i.UpdatedAt,
	)
	return i, err
}

const reverseEarning = `-- name: ReverseEarning :one
UPDATE commission_earnings SET reversed_at = now()
WHERE id = $1 AND reversed_at IS NULL
RETURNING id, conversion_event_id, partner_id, offer_id, tracking_link_id, rate_bps, amount_kopecks, external_user_id, reversed_at, created_at
`

func (q *Queries) ReverseEarning(ctx context.Context, id string) (CommissionEarning, error) {
	row := q.db.QueryRow(ctx, reverseEarning, id)
	var i CommissionEarning
	err := row.Scan(
		&i.ID,
		&i.ConversionEventID,
		&i.PartnerID,
		&i.OfferID,
		&i.TrackingLinkID,
		&i.RateBps,
		&i.AmountKopecks,
		&i.ExternalUserID,
		&i.ReversedAt,
		&i.CreatedAt,
	)
	return i, err
}

const reverseReward = `-- name: ReverseReward :one
UPDATE referral_rewards SET reversed_at = now()
WHERE id = $1 AND reversed_at IS NULL
RETURNING id, commission_earning_id, partner_referral_id, referrer_partner_id, invited_partner_id, referral_rate_bps, amount_kopecks, reversed_at, created_at
`

func (q *Queries) ReverseReward(ctx context.Context, id string) (ReferralReward, error) {
	row := q.db.QueryRow(ctx, reverseReward, id)
	var i ReferralReward
	err := row.Scan(
		&i.ID,
		&i.CommissionEarningID,
		&i.PartnerReferralID,
		&i.ReferrerPartnerID,
		&i.InvitedPartnerID,
		&i.ReferralRateBps,
		&i.AmountKopecks,
		&i.ReversedAt,
		&i.CreatedAt,
	)
	return i, err
}

const sumRewardsByInvited = `-- name: SumRewardsByInvited :one
SELECT COALESCE(sum(amount_kopecks), 0)::bigint FROM referral_rewards WHERE invited_partner_id = $1 AND reversed_at IS NULL
`

func (q *Queries) SumRewardsByInvited(ctx context.Context, invitedPartnerID string) (int64, error) {
	row := q.db.QueryRow(ctx, sumRewardsByInvited, invitedPartnerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumRewardsByReferrer = `-- name: SumRewardsByReferrer :one
SELECT COALESCE(sum(amount_kopecks), 0)::bigint FROM referral_rewards WHERE referrer_partner_id = $1 AND reversed_at IS NULL
`

func (q *Queries) SumRewardsByReferrer(ctx context.Context, referrerPartnerID string) (int64, error) {
	row := q.db.QueryRow(ctx, sumRewardsByReferrer, referrerPartnerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
