// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Announcement struct {
	ID          string             `json:"id"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	Audience    string             `json:"audience"`
	IsPublished bool               `json:"is_published"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type AnnouncementAudience struct {
	ID             string      `json:"id"`
	AnnouncementID string      `json:"announcement_id"`
	PartnerID      pgtype.UUID `json:"partner_id"`
}

type AnnouncementRead struct {
	ID             int64              `json:"id"`
	AnnouncementID string             `json:"announcement_id"`
	ReaderUserID   string             `json:"reader_user_id"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
}

type AuditLog struct {
	ID          int64              `json:"id"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    string             `json:"entity_id"`
	Changes     []byte             `json:"changes"`
	Ip          *netip.Addr        `json:"ip"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CommissionEarning struct {
	ID                string             `json:"id"`
	ConversionEventID int64              `json:"conversion_event_id"`
	PartnerID         string             `json:"partner_id"`
	OfferID           string             `json:"offer_id"`
	TrackingLinkID    pgtype.UUID        `json:"tracking_link_id"`
	RateBps           int32              `json:"rate_bps"`
	AmountKopecks     int64              `json:"amount_kopecks"`
	ExternalUserID    string             `json:"external_user_id"`
	ReversedAt        pgtype.Timestamptz `json:"reversed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ConversionEvent struct {
	ID                int64              `json:"id"`
	ProjectID         string             `json:"project_id"`
	ExternalEventID   string             `json:"external_event_id"`
	ExternalPaymentID string             `json:"external_payment_id"`
	ExternalUserID    string             `json:"external_user_id"`
	AttributionID     int64              `json:"attribution_id"`
	AmountKopecks     int64              `json:"amount_kopecks"`
	Currency          string             `json:"currency"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	ProcessingNote    pgtype.Text        `json:"processing_note"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ConversionEvents202608 struct {
	ID                int64              `json:"id"`
	ProjectID         string             `json:"project_id"`
	ExternalEventID   string             `json:"external_event_id"`
	ExternalPaymentID string             `json:"external_payment_id"`
	ExternalUserID    string             `json:"external_user_id"`
	AttributionID     int64              `json:"attribution_id"`
	AmountKopecks     int64              `json:"amount_kopecks"`
	Currency          string             `json:"currency"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	ProcessingNote    pgtype.Text        `json:"processing_note"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type DailyPartnerOfferStat struct {
	PartnerID     string      `json:"partner_id"`
	OfferID       string      `json:"offer_id"`
	Day           pgtype.Date `json:"day"`
	Clicks        int32       `json:"clicks"`
	UniqueClicks  int32       `json:"unique_clicks"`
	Registrations int32       `json:"registrations"`
	FirstPayments int32       `json:"first_payments"`
	IncomeKopecks int64       `json:"income_kopecks"`
}

type DailyTrackingLinkStat struct {
	TrackingLinkID string      `json:"tracking_link_id"`
	Day            pgtype.Date `json:"day"`
	Clicks         int32       `json:"clicks"`
	UniqueClicks   int32       `json:"unique_clicks"`
	Registrations  int32       `json:"registrations"`
	FirstPayments  int32       `json:"first_payments"`
	IncomeKopecks  int64       `json:"income_kopecks"`
}

type ExternalUserAttribution struct {
	ID              int64              `json:"id"`
	ProjectID       string             `json:"project_id"`
	TrackingClickID pgtype.Int8        `json:"tracking_click_id"`
	PartnerID       pgtype.UUID        `json:"partner_id"`
	OfferID         pgtype.UUID        `json:"offer_id"`
	ExternalUserID  string             `json:"external_user_id"`
	FirstSeenAt     pgtype.Timestamptz `json:"first_seen_at"`
}

type IncomingEvent struct {
	ID              int64              `json:"id"`
	ProjectID       string             `json:"project_id"`
	ExternalEventID string             `json:"external_event_id"`
	Type            string             `json:"type"`
	Payload         []byte             `json:"payload"`
	Status          string             `json:"status"`
	Reason          pgtype.Text        `json:"reason"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
}

type IncomingEvents202608 struct {
	ID              int64              `json:"id"`
	ProjectID       string             `json:"project_id"`
	ExternalEventID string             `json:"external_event_id"`
	Type            string             `json:"type"`
	Payload         []byte             `json:"payload"`
	Status          string             `json:"status"`
	Reason          pgtype.Text        `json:"reason"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
}

type IntegrationKey struct {
	ID               string             `json:"id"`
	ProjectID        string             `json:"project_id"`
	KeyID            string             `json:"key_id"`
	SecretCiphertext []byte             `json:"secret_ciphertext"`
	SecretHint       string             `json:"secret_hint"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	RotatedAt        pgtype.Timestamptz `json:"rotated_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
}

type MediaAsset struct {
	ID          string             `json:"id"`
	Bucket      string             `json:"bucket"`
	Key         string             `json:"key"`
	ContentType string             `json:"content_type"`
	SizeBytes   int64              `json:"size_bytes"`
	UploadedBy  pgtype.UUID        `json:"uploaded_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Offer struct {
	ID             string             `json:"id"`
	ProjectID      string             `json:"project_id"`
	Name           string             `json:"name"`
	Category       pgtype.Text        `json:"category"`
	Description    pgtype.Text        `json:"description"`
	LogoMediaID    pgtype.UUID        `json:"logo_media_id"`
	DestinationUrl pgtype.Text        `json:"destination_url"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OfferTermsVersion struct {
	ID            string             `json:"id"`
	OfferID       string             `json:"offer_id"`
	Version       int32              `json:"version"`
	RateBps       int32              `json:"rate_bps"`
	EffectiveFrom pgtype.Timestamptz `json:"effective_from"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type OutboxMessage struct {
	ID            int64              `json:"id"`
	Topic         string             `json:"topic"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SentAt        pgtype.Timestamptz `json:"sent_at"`
}

type PartnerDomain struct {
	ID                  string             `json:"id"`
	Url                 string             `json:"url"`
	IsActive            bool               `json:"is_active"`
	Comment             pgtype.Text        `json:"comment"`
	LegacyKazikDomainID pgtype.Text        `json:"legacy_kazik_domain_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type PartnerOfferAccess struct {
	ID        string             `json:"id"`
	PartnerID string             `json:"partner_id"`
	OfferID   string             `json:"offer_id"`
	RateBps   int32              `json:"rate_bps"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PartnerProfile struct {
	ID                   string             `json:"id"`
	UserID               string             `json:"user_id"`
	ReferralCode         string             `json:"referral_code"`
	ReferredBy           pgtype.UUID        `json:"referred_by"`
	IsApproved           bool               `json:"is_approved"`
	IsBlocked            bool               `json:"is_blocked"`
	IsOwner              bool               `json:"is_owner"`
	IsAdmin              bool               `json:"is_admin"`
	RevsharePercentBps   int32              `json:"revshare_percent_bps"`
	TelegramUserID       pgtype.Int8        `json:"telegram_user_id"`
	Comment              pgtype.Text        `json:"comment"`
	LegacyKazikPartnerID pgtype.Text        `json:"legacy_kazik_partner_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type PartnerReferral struct {
	ID                string             `json:"id"`
	ReferrerPartnerID string             `json:"referrer_partner_id"`
	InvitedPartnerID  string             `json:"invited_partner_id"`
	ReferralRateBps   int32              `json:"referral_rate_bps"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type PartnerReferralClick struct {
	ID                int64              `json:"id"`
	ReferrerPartnerID string             `json:"referrer_partner_id"`
	Ip                *netip.Addr        `json:"ip"`
	UserAgent         pgtype.Text        `json:"user_agent"`
	Referrer          pgtype.Text        `json:"referrer"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type PayoutRequisite struct {
	ID        string             `json:"id"`
	PartnerID string             `json:"partner_id"`
	Method    string             `json:"method"`
	Value     string             `json:"value"`
	Bank      pgtype.Text        `json:"bank"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PayoutRule struct {
	ID                 string             `json:"id"`
	MinWithdrawKopecks int64              `json:"min_withdraw_kopecks"`
	UsdtRate           pgtype.Numeric     `json:"usdt_rate"`
	SbpFeeFlatKopecks  int64              `json:"sbp_fee_flat_kopecks"`
	SbpFeePercentBps   int32              `json:"sbp_fee_percent_bps"`
	UpdatedBy          pgtype.UUID        `json:"updated_by"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type PayoutTransfer struct {
	ID                  string             `json:"id"`
	WithdrawalRequestID string             `json:"withdrawal_request_id"`
	ExternalTxID        pgtype.Text        `json:"external_tx_id"`
	AmountKopecks       int64              `json:"amount_kopecks"`
	FeeKopecks          int64              `json:"fee_kopecks"`
	TransferredAt       pgtype.Timestamptz `json:"transferred_at"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	Comment             pgtype.Text        `json:"comment"`
}

type PlatformSetting struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID             string             `json:"id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	LogoMediaID    pgtype.UUID        `json:"logo_media_id"`
	DestinationUrl string             `json:"destination_url"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ProjectSetting struct {
	ProjectID        string             `json:"project_id"`
	AllowNewPartners bool               `json:"allow_new_partners"`
	Comment          pgtype.Text        `json:"comment"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type RedirectPool struct {
	ID                    string             `json:"id"`
	Name                  string             `json:"name"`
	Comment               pgtype.Text        `json:"comment"`
	LegacyKazikRedirectID pgtype.Text        `json:"legacy_kazik_redirect_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type RedirectPoolUrl struct {
	ID         string             `json:"id"`
	RedirectID string             `json:"redirect_id"`
	Url        string             `json:"url"`
	Weight     int32              `json:"weight"`
	IsActive   bool               `json:"is_active"`
	SortOrder  int32              `json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ReferralReward struct {
	ID                  string             `json:"id"`
	CommissionEarningID string             `json:"commission_earning_id"`
	PartnerReferralID   string             `json:"partner_referral_id"`
	ReferrerPartnerID   string             `json:"referrer_partner_id"`
	InvitedPartnerID    string             `json:"invited_partner_id"`
	ReferralRateBps     int32              `json:"referral_rate_bps"`
	AmountKopecks       int64              `json:"amount_kopecks"`
	ReversedAt          pgtype.Timestamptz `json:"reversed_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID         string             `json:"id"`
	Token      string             `json:"token"`
	UserID     string             `json:"user_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastAccess pgtype.Timestamptz `json:"last_access"`
	Metadata   []byte             `json:"metadata"`
}

type SourceGroup struct {
	ID                 string             `json:"id"`
	PartnerID          string             `json:"partner_id"`
	Name               string             `json:"name"`
	Comment            pgtype.Text        `json:"comment"`
	LegacyKazikGroupID pgtype.Text        `json:"legacy_kazik_group_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type StaffRoleAssignment struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Role      string             `json:"role"`
	ProjectID pgtype.UUID        `json:"project_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TrackingClick struct {
	ID             int64              `json:"id"`
	TrackingLinkID string             `json:"tracking_link_id"`
	Ip             *netip.Addr        `json:"ip"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referrer       pgtype.Text        `json:"referrer"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type TrackingClicks202608 struct {
	ID             int64              `json:"id"`
	TrackingLinkID string             `json:"tracking_link_id"`
	Ip             *netip.Addr        `json:"ip"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referrer       pgtype.Text        `json:"referrer"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type TrackingLink struct {
	ID                   string             `json:"id"`
	PartnerOfferAccessID string             `json:"partner_offer_access_id"`
	Code                 string             `json:"code"`
	Name                 string             `json:"name"`
	Comment              pgtype.Text        `json:"comment"`
	GroupID              pgtype.UUID        `json:"group_id"`
	IsDefault            bool               `json:"is_default"`
	IsActive             bool               `json:"is_active"`
	Type                 string             `json:"type"`
	RegistrationBonus    pgtype.Int4        `json:"registration_bonus"`
	Domain               pgtype.Text        `json:"domain"`
	RedirectID           pgtype.UUID        `json:"redirect_id"`
	LegacyKazikSourceID  pgtype.Text        `json:"legacy_kazik_source_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	Name            string             `json:"name"`
	Role            string             `json:"role"`
	IsActive        bool               `json:"is_active"`
	Password        pgtype.Text        `json:"password"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserNotification struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Metadata  []byte             `json:"metadata"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Verification struct {
	ID        string             `json:"id"`
	Subject   string             `json:"subject"`
	Value     string             `json:"value"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Wallet struct {
	ID                 string             `json:"id"`
	PartnerID          string             `json:"partner_id"`
	AvailableKopecks   int64              `json:"available_kopecks"`
	ReservedKopecks    int64              `json:"reserved_kopecks"`
	LegacyKazikBalance pgtype.Int4        `json:"legacy_kazik_balance"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type WalletLedgerEntry struct {
	ID                   int64              `json:"id"`
	WalletID             string             `json:"wallet_id"`
	Type                 string             `json:"type"`
	AmountKopecks        int64              `json:"amount_kopecks"`
	BalanceAfterKopecks  int64              `json:"balance_after_kopecks"`
	RefConversionEventID pgtype.Int8        `json:"ref_conversion_event_id"`
	RefWithdrawalID      pgtype.UUID        `json:"ref_withdrawal_id"`
	RefReferralRewardID  pgtype.UUID        `json:"ref_referral_reward_id"`
	Comment              pgtype.Text        `json:"comment"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type WithdrawalRequest struct {
	ID                      string             `json:"id"`
	PartnerID               string             `json:"partner_id"`
	AmountKopecks           int64              `json:"amount_kopecks"`
	Method                  string             `json:"method"`
	Requisites              string             `json:"requisites"`
	Bank                    pgtype.Text        `json:"bank"`
	FeeKopecks              int64              `json:"fee_kopecks"`
	UsdtAmount              pgtype.Numeric     `json:"usdt_amount"`
	Rate                    pgtype.Numeric     `json:"rate"`
	Status                  string             `json:"status"`
	Comment                 pgtype.Text        `json:"comment"`
	DecidedAt               pgtype.Timestamptz `json:"decided_at"`
	PaidAt                  pgtype.Timestamptz `json:"paid_at"`
	LegacyKazikWithdrawalID pgtype.Text        `json:"legacy_kazik_withdrawal_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}
