// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offers.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultTrackingLinks = `-- name: ClearDefaultTrackingLinks :exec
UPDATE tracking_links SET is_default = false, updated_at = now()
WHERE partner_offer_access_id = $1
`

func (q *Queries) ClearDefaultTrackingLinks(ctx context.Context, partnerOfferAccessID string) error {
	_, err := q.db.Exec(ctx, clearDefaultTrackingLinks, partnerOfferAccessID)
	return err
}

const countActiveLinksByAccess = `-- name: CountActiveLinksByAccess :one
SELECT count(*) FROM tracking_links WHERE partner_offer_access_id = $1 AND is_active = true
`

func (q *Queries) CountActiveLinksByAccess(ctx context.Context, partnerOfferAccessID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveLinksByAccess, partnerOfferAccessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countClicksByLink = `-- name: CountClicksByLink :one
SELECT count(*) FROM tracking_clicks WHERE tracking_link_id = $1
`

func (q *Queries) CountClicksByLink(ctx context.Context, trackingLinkID string) (int64, error) {
	row := q.db.QueryRow(ctx, countClicksByLink, trackingLinkID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOfferTerms = `-- name: CountOfferTerms :one
SELECT count(*) FROM offer_terms_versions WHERE offer_id = $1
`

func (q *Queries) CountOfferTerms(ctx context.Context, offerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOfferTerms, offerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOffers = `-- name: CountOffers :one
SELECT count(*) FROM offers WHERE ($1 = '' OR project_id = $1::uuid)
`

func (q *Queries) CountOffers(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countOffers, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSourcesInGroup = `-- name: CountSourcesInGroup :one
SELECT count(*) FROM tracking_links WHERE group_id = $1
`

func (q *Queries) CountSourcesInGroup(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSourcesInGroup, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrackingLinksByPartner = `-- name: CountTrackingLinksByPartner :one
SELECT count(*) FROM tracking_links tl
JOIN partner_offer_accesses a ON a.id = tl.partner_offer_access_id
WHERE a.partner_id = $1
`

func (q *Queries) CountTrackingLinksByPartner(ctx context.Context, partnerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTrackingLinksByPartner, partnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOffer = `-- name: CreateOffer :one
INSERT INTO offers (project_id, name, category, description, destination_url, status)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, project_id, name, category, description, destination_url, status, created_at, updated_at
`

type CreateOfferParams struct {
	ProjectID      string      `json:"project_id"`
	Name           string      `json:"name"`
	Category       pgtype.Text `json:"category"`
	Description    pgtype.Text `json:"description"`
	DestinationUrl pgtype.Text `json:"destination_url"`
	Status         string      `json:"status"`
}

type CreateOfferRow struct {
	ID             string             `json:"id"`
	ProjectID      string             `json:"project_id"`
	Name           string             `json:"name"`
	Category       pgtype.Text        `json:"category"`
	Description    pgtype.Text        `json:"description"`
	DestinationUrl pgtype.Text        `json:"destination_url"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOffer(ctx context.Context, arg CreateOfferParams) (CreateOfferRow, error) {
	row := q.db.QueryRow(ctx, createOffer,
		arg.ProjectID,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.DestinationUrl,
		arg.Status,
	)
	var i CreateOfferRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.DestinationUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOfferTerms = `-- name: CreateOfferTerms :one
INSERT INTO offer_terms_versions (offer_id, version, rate_bps, effective_from)
VALUES ($1, $2, $3, $4) RETURNING id, offer_id, version, rate_bps, effective_from, created_at
`

type CreateOfferTermsParams struct {
	OfferID       string             `json:"offer_id"`
	Version       int32              `json:"version"`
	RateBps       int32              `json:"rate_bps"`
	EffectiveFrom pgtype.Timestamptz `json:"effective_from"`
}

func (q *Queries) CreateOfferTerms(ctx context.Context, arg CreateOfferTermsParams) (OfferTermsVersion, error) {
	row := q.db.QueryRow(ctx, createOfferTerms,
		arg.OfferID,
		arg.Version,
		arg.RateBps,
		arg.EffectiveFrom,
	)
	var i OfferTermsVersion
	err := row.Scan(
		&i.ID,
		&i.OfferID,
		&i.Version,
		&i.RateBps,
		&i.EffectiveFrom,
		&i.CreatedAt,
	)
	return i, err
}

const createPartnerAccess = `-- name: CreatePartnerAccess :one
INSERT INTO partner_offer_accesses (partner_id, offer_id, rate_bps, status)
VALUES ($1, $2, $3, 'active') RETURNING id, partner_id, offer_id, rate_bps, status, created_at, updated_at
`

type CreatePartnerAccessParams struct {
	PartnerID string `json:"partner_id"`
	OfferID   string `json:"offer_id"`
	RateBps   int32  `json:"rate_bps"`
}

func (q *Queries) CreatePartnerAccess(ctx context.Context, arg CreatePartnerAccessParams) (PartnerOfferAccess, error) {
	row := q.db.QueryRow(ctx, createPartnerAccess, arg.PartnerID, arg.OfferID, arg.RateBps)
	var i PartnerOfferAccess
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.OfferID,
		&i.RateBps,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSourceGroup = `-- name: CreateSourceGroup :one
INSERT INTO source_groups (partner_id, name, comment)
VALUES ($1, $2, $3) RETURNING id, partner_id, name, comment, legacy_kazik_group_id, created_at, updated_at
`

type CreateSourceGroupParams struct {
	PartnerID string      `json:"partner_id"`
	Name      string      `json:"name"`
	Comment   pgtype.Text `json:"comment"`
}

func (q *Queries) CreateSourceGroup(ctx context.Context, arg CreateSourceGroupParams) (SourceGroup, error) {
	row := q.db.QueryRow(ctx, createSourceGroup, arg.PartnerID, arg.Name, arg.Comment)
	var i SourceGroup
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.Name,
		&i.Comment,
		&i.LegacyKazikGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTrackingLink = `-- name: CreateTrackingLink :one
INSERT INTO tracking_links (partner_offer_access_id, code, name, comment, group_id, is_default)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, partner_offer_access_id, code, name, comment, group_id, is_default, is_active, type, registration_bonus, domain, redirect_id, legacy_kazik_source_id, created_at, updated_at
`

type CreateTrackingLinkParams struct {
	PartnerOfferAccessID string      `json:"partner_offer_access_id"`
	Code                 string      `json:"code"`
	Name                 string      `json:"name"`
	Comment              pgtype.Text `json:"comment"`
	GroupID              pgtype.UUID `json:"group_id"`
	IsDefault            bool        `json:"is_default"`
}

func (q *Queries) CreateTrackingLink(ctx context.Context, arg CreateTrackingLinkParams) (TrackingLink, error) {
	row := q.db.QueryRow(ctx, createTrackingLink,
		arg.PartnerOfferAccessID,
		arg.Code,
		arg.Name,
		arg.Comment,
		arg.GroupID,
		arg.IsDefault,
	)
	var i TrackingLink
	err := row.Scan(
		&i.ID,
		&i.PartnerOfferAccessID,
		&i.Code,
		&i.Name,
		&i.Comment,
		&i.GroupID,
		&i.IsDefault,
		&i.IsActive,
		&i.Type,
		&i.RegistrationBonus,
		&i.Domain,
		&i.RedirectID,
		&i.LegacyKazikSourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTrackingLinkFull = `-- name: CreateTrackingLinkFull :one
INSERT INTO tracking_links (partner_offer_access_id, code, name, comment, group_id, is_default, is_active, type, registration_bonus, domain, redirect_id, legacy_kazik_source_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, COALESCE($8::text, 'link'), $9, $10, $11, $12)
RETURNING id, partner_offer_access_id, code, name, comment, group_id, is_default, is_active, type, registration_bonus, domain, redirect_id, legacy_kazik_source_id, created_at, updated_at
`

type CreateTrackingLinkFullParams struct {
	PartnerOfferAccessID string      `json:"partner_offer_access_id"`
	Code                 string      `json:"code"`
	Name                 string      `json:"name"`
	Comment              pgtype.Text `json:"comment"`
	GroupID              pgtype.UUID `json:"group_id"`
	IsDefault            bool        `json:"is_default"`
	IsActive             bool        `json:"is_active"`
	Type                 pgtype.Text `json:"type"`
	RegistrationBonus    pgtype.Int4 `json:"registration_bonus"`
	Domain               pgtype.Text `json:"domain"`
	RedirectID           pgtype.UUID `json:"redirect_id"`
	LegacyKazikSourceID  pgtype.Text `json:"legacy_kazik_source_id"`
}

func (q *Queries) CreateTrackingLinkFull(ctx context.Context, arg CreateTrackingLinkFullParams) (TrackingLink, error) {
	row := q.db.QueryRow(ctx, createTrackingLinkFull,
		arg.PartnerOfferAccessID,
		arg.Code,
		arg.Name,
		arg.Comment,
		arg.GroupID,
		arg.IsDefault,
		arg.IsActive,
		arg.Type,
		arg.RegistrationBonus,
		arg.Domain,
		arg.RedirectID,
		arg.LegacyKazikSourceID,
	)
	var i TrackingLink
	err := row.Scan(
		&i.ID,
		&i.PartnerOfferAccessID,
		&i.Code,
		&i.Name,
		&i.Comment,
		&i.GroupID,
		&i.IsDefault,
		&i.IsActive,
		&i.Type,
		&i.RegistrationBonus,
		&i.Domain,
		&i.RedirectID,
		&i.LegacyKazikSourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSourceGroup = `-- name: DeleteSourceGroup :exec
DELETE FROM source_groups WHERE id = $1
`

func (q *Queries) DeleteSourceGroup(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSourceGroup, id)
	return err
}

const deleteTrackingLink = `-- name: DeleteTrackingLink :exec
DELETE FROM tracking_links WHERE id = $1
`

func (q *Queries) DeleteTrackingLink(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTrackingLink, id)
	return err
}

const getAccessByID = `-- name: GetAccessByID :one
SELECT id, partner_id, offer_id, rate_bps, status, created_at, updated_at FROM partner_offer_accesses WHERE id = $1
`

func (q *Queries) GetAccessByID(ctx context.Context, id string) (PartnerOfferAccess, error) {
	row := q.db.QueryRow(ctx, getAccessByID, id)
	var i PartnerOfferAccess
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.OfferID,
		&i.RateBps,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentTerms = `-- name: GetCurrentTerms :one
SELECT id, offer_id, version, rate_bps, effective_from, created_at
FROM offer_terms_versions WHERE offer_id = $1 ORDER BY version DESC LIMIT 1
`

func (q *Queries) GetCurrentTerms(ctx context.Context, offerID string) (OfferTermsVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentTerms, offerID)
	var i OfferTermsVersion
	err := row.Scan(
		&i.ID,
		&i.OfferID,
		&i.Version,
		&i.RateBps,
		&i.EffectiveFrom,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaultTrackingLinkByAccessID = `-- name: GetDefaultTrackingLinkByAccessID :one
SELECT id, partner_offer_access_id, code, name, comment, group_id, is_default, is_active, type, registration_bonus, domain, redirect_id, legacy_kazik_source_id, created_at, updated_at FROM tracking_links
WHERE partner_offer_access_id = $1
ORDER BY is_default DESC, created_at
LIMIT 1
`

func (q *Queries) GetDefaultTrackingLinkByAccessID(ctx context.Context, partnerOfferAccessID string) (TrackingLink, error) {
	row := q.db.QueryRow(ctx, getDefaultTrackingLinkByAccessID, partnerOfferAccessID)
	var i TrackingLink
	err := row.Scan(
		&i.ID,
		&i.PartnerOfferAccessID,
		&i.Code,
		&i.Name,
		&i.Comment,
		&i.GroupID,
		&i.IsDefault,
		&i.IsActive,
		&i.Type,
		&i.RegistrationBonus,
		&i.Domain,
		&i.RedirectID,
		&i.LegacyKazikSourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOfferByID = `-- name: GetOfferByID :one
SELECT id, project_id, name, category, description, destination_url, status, created_at, updated_at FROM offers WHERE id = $1
`

type GetOfferByIDRow struct {
	ID             string             `json:"id"`
	ProjectID      string             `json:"project_id"`
	Name           string             `json:"name"`
	Category       pgtype.Text        `json:"category"`
	Description    pgtype.Text        `json:"description"`
	DestinationUrl pgtype.Text        `json:"destination_url"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOfferByID(ctx context.Context, id string) (GetOfferByIDRow, error) {
	row := q.db.QueryRow(ctx, getOfferByID, id)
	var i GetOfferByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.DestinationUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOfferWithProject = `-- name: GetOfferWithProject :one
SELECT o.id, o.project_id, o.name, o.category, o.description, o.destination_url, o.status, o.created_at, o.updated_at,
       p.name AS project_name, p.logo_media_id, p.destination_url AS project_destination_url
FROM offers o JOIN projects p ON p.id = o.project_id
WHERE o.id = $1
`

type GetOfferWithProjectRow struct {
	ID                    string             `json:"id"`
	ProjectID             string             `json:"project_id"`
	Name                  string             `json:"name"`
	Category              pgtype.Text        `json:"category"`
	Description           pgtype.Text        `json:"description"`
	DestinationUrl        pgtype.Text        `json:"destination_url"`
	Status                string             `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ProjectName           string             `json:"project_name"`
	LogoMediaID           pgtype.UUID        `json:"logo_media_id"`
	ProjectDestinationUrl string             `json:"project_destination_url"`
}

func (q *Queries) GetOfferWithProject(ctx context.Context, id string) (GetOfferWithProjectRow, error) {
	row := q.db.QueryRow(ctx, getOfferWithProject, id)
	var i GetOfferWithProjectRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.DestinationUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectName,
		&i.LogoMediaID,
		&i.ProjectDestinationUrl,
	)
	return i, err
}

const getPartnerAccess = `-- name: GetPartnerAccess :one
SELECT id, partner_id, offer_id, rate_bps, status, created_at, updated_at
FROM partner_offer_accesses WHERE partner_id = $1 AND offer_id = $2
`

type GetPartnerAccessParams struct {
	PartnerID string `json:"partner_id"`
	OfferID   string `json:"offer_id"`
}

func (q *Queries) GetPartnerAccess(ctx context.Context, arg GetPartnerAccessParams) (PartnerOfferAccess, error) {
	row := q.db.QueryRow(ctx, getPartnerAccess, arg.PartnerID, arg.OfferID)
	var i PartnerOfferAccess
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.OfferID,
		&i.RateBps,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegistrationBonusByCode = `-- name: GetRegistrationBonusByCode :one
SELECT registration_bonus FROM tracking_links WHERE code = $1 AND is_active = true LIMIT 1
`

func (q *Queries) GetRegistrationBonusByCode(ctx context.Context, code string) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getRegistrationBonusByCode, code)
	var registration_bonus pgtype.Int4
	err := row.Scan(&registration_bonus)
	return registration_bonus, err
}

const getSourceGroupByID = `-- name: GetSourceGroupByID :one
SELECT id, partner_id, name, comment, legacy_kazik_group_id, created_at, updated_at FROM source_groups WHERE id = $1
`

func (q *Queries) GetSourceGroupByID(ctx context.Context, id string) (SourceGroup, error) {
	row := q.db.QueryRow(ctx, getSourceGroupByID, id)
	var i SourceGroup
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.Name,
		&i.Comment,
		&i.LegacyKazikGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrackingLinkByCode = `-- name: GetTrackingLinkByCode :one
SELECT tl.id, tl.partner_offer_access_id, tl.code, tl.is_active, tl.type, tl.domain, tl.redirect_id, tl.registration_bonus, tl.created_at,
       a.partner_id, a.offer_id, a.status AS access_status,
       o.destination_url AS offer_destination_url,
       p.destination_url AS project_destination_url,
       (tl.domain IS NOT NULL AND EXISTS (
           SELECT 1 FROM offer_domains od
           WHERE od.offer_id = a.offer_id AND od.url = tl.domain AND od.is_active
       )) AS domain_active
FROM tracking_links tl
JOIN partner_offer_accesses a ON a.id = tl.partner_offer_access_id
JOIN offers o ON o.id = a.offer_id
JOIN projects p ON p.id = o.project_id
WHERE tl.code = $1
`

type GetTrackingLinkByCodeRow struct {
	ID                    string             `json:"id"`
	PartnerOfferAccessID  string             `json:"partner_offer_access_id"`
	Code                  string             `json:"code"`
	IsActive              bool               `json:"is_active"`
	Type                  string             `json:"type"`
	Domain                pgtype.Text        `json:"domain"`
	RedirectID            pgtype.UUID        `json:"redirect_id"`
	RegistrationBonus     pgtype.Int4        `json:"registration_bonus"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	PartnerID             string             `json:"partner_id"`
	OfferID               string             `json:"offer_id"`
	AccessStatus          string             `json:"access_status"`
	OfferDestinationUrl   pgtype.Text        `json:"offer_destination_url"`
	ProjectDestinationUrl string             `json:"project_destination_url"`
	DomainActive          pgtype.Bool        `json:"domain_active"`
}

func (q *Queries) GetTrackingLinkByCode(ctx context.Context, code string) (GetTrackingLinkByCodeRow, error) {
	row := q.db.QueryRow(ctx, getTrackingLinkByCode, code)
	var i GetTrackingLinkByCodeRow
	err := row.Scan(
		&i.ID,
		&i.PartnerOfferAccessID,
		&i.Code,
		&i.IsActive,
		&i.Type,
		&i.Domain,
		&i.RedirectID,
		&i.RegistrationBonus,
		&i.CreatedAt,
		&i.PartnerID,
		&i.OfferID,
		&i.AccessStatus,
		&i.OfferDestinationUrl,
		&i.ProjectDestinationUrl,
		&i.DomainActive,
	)
	return i, err
}

const getTrackingLinkByCodeExtended = `-- name: GetTrackingLinkByCodeExtended :one
SELECT id, partner_offer_access_id, code, name, comment, group_id, is_default, is_active, type, registration_bonus, domain, redirect_id, legacy_kazik_source_id, created_at, updated_at FROM tracking_links WHERE code = $1
`

func (q *Queries) GetTrackingLinkByCodeExtended(ctx context.Context, code string) (TrackingLink, error) {
	row := q.db.QueryRow(ctx, getTrackingLinkByCodeExtended, code)
	var i TrackingLink
	err := row.Scan(
		&i.ID,
		&i.PartnerOfferAccessID,
		&i.Code,
		&i.Name,
		&i.Comment,
		&i.GroupID,
		&i.IsDefault,
		&i.IsActive,
		&i.Type,
		&i.RegistrationBonus,
		&i.Domain,
		&i.RedirectID,
		&i.LegacyKazikSourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrackingLinkByCodeForProject = `-- name: GetTrackingLinkByCodeForProject :one
SELECT tl.id, tl.code, tl.name, tl.type, tl.is_active, tl.registration_bonus,
       a.partner_id, a.offer_id, a.status AS access_status
FROM tracking_links tl
JOIN partner_offer_accesses a ON a.id = tl.partner_offer_access_id
JOIN offers o ON o.id = a.offer_id
WHERE tl.code = $1 AND o.project_id = $2
ORDER BY tl.is_active DESC, tl.created_at
LIMIT 1
`

type GetTrackingLinkByCodeForProjectParams struct {
	Code      string `json:"code"`
	ProjectID string `json:"project_id"`
}

type GetTrackingLinkByCodeForProjectRow struct {
	ID                string      `json:"id"`
	Code              string      `json:"code"`
	Name              string      `json:"name"`
	Type              string      `json:"type"`
	IsActive          bool        `json:"is_active"`
	RegistrationBonus pgtype.Int4 `json:"registration_bonus"`
	PartnerID         string      `json:"partner_id"`
	OfferID           string      `json:"offer_id"`
	AccessStatus      string      `json:"access_status"`
}

// Resolve a source (tracking link) by its code within one project's scope.
// Used by the integrations API: promo-code attribution (registration.created
// with source_code instead of click_token) and the source lookup endpoint.
func (q *Queries) GetTrackingLinkByCodeForProject(ctx context.Context, arg GetTrackingLinkByCodeForProjectParams) (GetTrackingLinkByCodeForProjectRow, error) {
	row := q.db.QueryRow(ctx, getTrackingLinkByCodeForProject, arg.Code, arg.ProjectID)
	var i GetTrackingLinkByCodeForProjectRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.IsActive,
		&i.RegistrationBonus,
		&i.PartnerID,
		&i.OfferID,
		&i.AccessStatus,
	)
	return i, err
}

const getTrackingLinkByID = `-- name: GetTrackingLinkByID :one
SELECT id, partner_offer_access_id, code, name, comment, group_id, is_default, is_active, type, registration_bonus, domain, redirect_id, legacy_kazik_source_id, created_at, updated_at FROM tracking_links WHERE id = $1
`

func (q *Queries) GetTrackingLinkByID(ctx context.Context, id string) (TrackingLink, error) {
	row := q.db.QueryRow(ctx, getTrackingLinkByID, id)
	var i TrackingLink
	err := row.Scan(
		&i.ID,
		&i.PartnerOfferAccessID,
		&i.Code,
		&i.Name,
		&i.Comment,
		&i.GroupID,
		&i.IsDefault,
		&i.IsActive,
		&i.Type,
		&i.RegistrationBonus,
		&i.Domain,
		&i.RedirectID,
		&i.LegacyKazikSourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllActiveAccesses = `-- name: ListAllActiveAccesses :many
SELECT a.id, a.partner_id, a.offer_id, a.rate_bps, a.status
FROM partner_offer_accesses a WHERE a.status = 'active'
`

type ListAllActiveAccessesRow struct {
	ID        string `json:"id"`
	PartnerID string `json:"partner_id"`
	OfferID   string `json:"offer_id"`
	RateBps   int32  `json:"rate_bps"`
	Status    string `json:"status"`
}

func (q *Queries) ListAllActiveAccesses(ctx context.Context) ([]ListAllActiveAccessesRow, error) {
	rows, err := q.db.Query(ctx, listAllActiveAccesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllActiveAccessesRow
	for rows.Next() {
		var i ListAllActiveAccessesRow
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.OfferID,
			&i.RateBps,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOffers = `-- name: ListOffers :many
SELECT o.id, o.project_id, o.name, o.category, o.description, o.destination_url, o.status, o.created_at, o.updated_at,
       p.name AS project_name
FROM offers o JOIN projects p ON p.id = o.project_id
WHERE ($1 = '' OR o.project_id = $1::uuid)
ORDER BY o.created_at DESC LIMIT $2 OFFSET $3
`

type ListOffersParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListOffersRow struct {
	ID             string             `json:"id"`
	ProjectID      string             `json:"project_id"`
	Name           string             `json:"name"`
	Category       pgtype.Text        `json:"category"`
	Description    pgtype.Text        `json:"description"`
	DestinationUrl pgtype.Text        `json:"destination_url"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ProjectName    string             `json:"project_name"`
}

func (q *Queries) ListOffers(ctx context.Context, arg ListOffersParams) ([]ListOffersRow, error) {
	rows, err := q.db.Query(ctx, listOffers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOffersRow
	for rows.Next() {
		var i ListOffersRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.DestinationUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOffersByProject = `-- name: ListOffersByProject :many
SELECT id, project_id, name, category, description, destination_url, status, created_at, updated_at
FROM offers WHERE project_id = $1 ORDER BY created_at DESC
`

type ListOffersByProjectRow struct {
	ID             string             `json:"id"`
	ProjectID      string             `json:"project_id"`
	Name           string             `json:"name"`
	Category       pgtype.Text        `json:"category"`
	Description    pgtype.Text        `json:"description"`
	DestinationUrl pgtype.Text        `json:"destination_url"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListOffersByProject(ctx context.Context, projectID string) ([]ListOffersByProjectRow, error) {
	rows, err := q.db.Query(ctx, listOffersByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOffersByProjectRow
	for rows.Next() {
		var i ListOffersByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.DestinationUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerAccesses = `-- name: ListPartnerAccesses :many
SELECT id, partner_id, offer_id, rate_bps, status, created_at, updated_at
FROM partner_offer_accesses WHERE partner_id = $1 ORDER BY created_at
`

func (q *Queries) ListPartnerAccesses(ctx context.Context, partnerID string) ([]PartnerOfferAccess, error) {
	rows, err := q.db.Query(ctx, listPartnerAccesses, partnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerOfferAccess
	for rows.Next() {
		var i PartnerOfferAccess
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.OfferID,
			&i.RateBps,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerAccessesWithOffer = `-- name: ListPartnerAccessesWithOffer :many
SELECT a.id, a.partner_id, a.offer_id, a.rate_bps, a.status, a.created_at, a.updated_at,
       o.name AS offer_name, o.project_id, o.status AS offer_status
FROM partner_offer_accesses a JOIN offers o ON o.id = a.offer_id
WHERE a.partner_id = $1 ORDER BY a.created_at
`

type ListPartnerAccessesWithOfferRow struct {
	ID          string             `json:"id"`
	PartnerID   string             `json:"partner_id"`
	OfferID     string             `json:"offer_id"`
	RateBps     int32              `json:"rate_bps"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	OfferName   string             `json:"offer_name"`
	ProjectID   string             `json:"project_id"`
	OfferStatus string             `json:"offer_status"`
}

func (q *Queries) ListPartnerAccessesWithOffer(ctx context.Context, partnerID string) ([]ListPartnerAccessesWithOfferRow, error) {
	rows, err := q.db.Query(ctx, listPartnerAccessesWithOffer, partnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartnerAccessesWithOfferRow
	for rows.Next() {
		var i ListPartnerAccessesWithOfferRow
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.OfferID,
			&i.RateBps,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OfferName,
			&i.ProjectID,
			&i.OfferStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceGroupsByPartner = `-- name: ListSourceGroupsByPartner :many
SELECT id, partner_id, name, comment, legacy_kazik_group_id, created_at, updated_at FROM source_groups WHERE partner_id = $1 ORDER BY name
`

func (q *Queries) ListSourceGroupsByPartner(ctx context.Context, partnerID string) ([]SourceGroup, error) {
	rows, err := q.db.Query(ctx, listSourceGroupsByPartner, partnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceGroup
	for rows.Next() {
		var i SourceGroup
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.Name,
			&i.Comment,
			&i.LegacyKazikGroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackingLinksByAccessID = `-- name: ListTrackingLinksByAccessID :many
SELECT tl.id, tl.partner_offer_access_id, tl.code, tl.name, tl.comment, tl.group_id, tl.is_default, tl.is_active, tl.type, tl.registration_bonus, tl.domain, tl.redirect_id, tl.legacy_kazik_source_id, tl.created_at, tl.updated_at, g.name AS group_name
FROM tracking_links tl
LEFT JOIN source_groups g ON g.id = tl.group_id
WHERE tl.partner_offer_access_id = $1
ORDER BY tl.is_default DESC, tl.created_at
`

type ListTrackingLinksByAccessIDRow struct {
	ID                   string             `json:"id"`
	PartnerOfferAccessID string             `json:"partner_offer_access_id"`
	Code                 string             `json:"code"`
	Name                 string             `json:"name"`
	Comment              pgtype.Text        `json:"comment"`
	GroupID              pgtype.UUID        `json:"group_id"`
	IsDefault            bool               `json:"is_default"`
	IsActive             bool               `json:"is_active"`
	Type                 string             `json:"type"`
	RegistrationBonus    pgtype.Int4        `json:"registration_bonus"`
	Domain               pgtype.Text        `json:"domain"`
	RedirectID           pgtype.UUID        `json:"redirect_id"`
	LegacyKazikSourceID  pgtype.Text        `json:"legacy_kazik_source_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	GroupName            pgtype.Text        `json:"group_name"`
}

func (q *Queries) ListTrackingLinksByAccessID(ctx context.Context, partnerOfferAccessID string) ([]ListTrackingLinksByAccessIDRow, error) {
	rows, err := q.db.Query(ctx, listTrackingLinksByAccessID, partnerOfferAccessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrackingLinksByAccessIDRow
	for rows.Next() {
		var i ListTrackingLinksByAccessIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PartnerOfferAccessID,
			&i.Code,
			&i.Name,
			&i.Comment,
			&i.GroupID,
			&i.IsDefault,
			&i.IsActive,
			&i.Type,
			&i.RegistrationBonus,
			&i.Domain,
			&i.RedirectID,
			&i.LegacyKazikSourceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackingLinksByPartner = `-- name: ListTrackingLinksByPartner :many
SELECT tl.id, tl.partner_offer_access_id, tl.code, tl.name, tl.comment, tl.group_id, tl.is_default, tl.is_active, tl.type, tl.registration_bonus, tl.domain, tl.redirect_id, tl.legacy_kazik_source_id, tl.created_at, tl.updated_at FROM tracking_links tl
JOIN partner_offer_accesses a ON a.id = tl.partner_offer_access_id
WHERE a.partner_id = $1
ORDER BY tl.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTrackingLinksByPartnerParams struct {
	PartnerID string `json:"partner_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListTrackingLinksByPartner(ctx context.Context, arg ListTrackingLinksByPartnerParams) ([]TrackingLink, error) {
	rows, err := q.db.Query(ctx, listTrackingLinksByPartner, arg.PartnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackingLink
	for rows.Next() {
		var i TrackingLink
		if err := rows.Scan(
			&i.ID,
			&i.PartnerOfferAccessID,
			&i.Code,
			&i.Name,
			&i.Comment,
			&i.GroupID,
			&i.IsDefault,
			&i.IsActive,
			&i.Type,
			&i.RegistrationBonus,
			&i.Domain,
			&i.RedirectID,
			&i.LegacyKazikSourceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolvePromoCode = `-- name: ResolvePromoCode :one
SELECT id, partner_offer_access_id, code, name, comment, group_id, is_default, is_active, type, registration_bonus, domain, redirect_id, legacy_kazik_source_id, created_at, updated_at FROM tracking_links WHERE code = $1 AND type = 'promo' AND is_active = true LIMIT 1
`

func (q *Queries) ResolvePromoCode(ctx context.Context, code string) (TrackingLink, error) {
	row := q.db.QueryRow(ctx, resolvePromoCode, code)
	var i TrackingLink
	err := row.Scan(
		&i.ID,
		&i.PartnerOfferAccessID,
		&i.Code,
		&i.Name,
		&i.Comment,
		&i.GroupID,
		&i.IsDefault,
		&i.IsActive,
		&i.Type,
		&i.RegistrationBonus,
		&i.Domain,
		&i.RedirectID,
		&i.LegacyKazikSourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchTrackingLinks = `-- name: SearchTrackingLinks :many
SELECT tl.id, tl.partner_offer_access_id, tl.code, tl.name, tl.comment, tl.group_id, tl.is_default, tl.is_active, tl.type, tl.registration_bonus, tl.domain, tl.redirect_id, tl.legacy_kazik_source_id, tl.created_at, tl.updated_at FROM tracking_links tl
JOIN partner_offer_accesses a ON a.id = tl.partner_offer_access_id
WHERE a.partner_id = $1
  AND ($2 = '' OR tl.name ILIKE '%' || $2 || '%' OR tl.code ILIKE '%' || $2 || '%')
  AND ($3 = '' OR tl.type = $3)
  AND ($4::uuid IS NULL OR tl.group_id = $4)
  AND ($5::uuid IS NULL OR tl.redirect_id = $5)
ORDER BY tl.created_at DESC
LIMIT $6 OFFSET $7
`

type SearchTrackingLinksParams struct {
	PartnerID string      `json:"partner_id"`
	Column2   interface{} `json:"column_2"`
	Column3   interface{} `json:"column_3"`
	Column4   string      `json:"column_4"`
	Column5   string      `json:"column_5"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) SearchTrackingLinks(ctx context.Context, arg SearchTrackingLinksParams) ([]TrackingLink, error) {
	rows, err := q.db.Query(ctx, searchTrackingLinks,
		arg.PartnerID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackingLink
	for rows.Next() {
		var i TrackingLink
		if err := rows.Scan(
			&i.ID,
			&i.PartnerOfferAccessID,
			&i.Code,
			&i.Name,
			&i.Comment,
			&i.GroupID,
			&i.IsDefault,
			&i.IsActive,
			&i.Type,
			&i.RegistrationBonus,
			&i.Domain,
			&i.RedirectID,
			&i.LegacyKazikSourceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultTrackingLink = `-- name: SetDefaultTrackingLink :exec
UPDATE tracking_links SET is_default = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) SetDefaultTrackingLink(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setDefaultTrackingLink, id)
	return err
}

const updateAllAccessRatesByPartner = `-- name: UpdateAllAccessRatesByPartner :exec
UPDATE partner_offer_accesses SET rate_bps = $2, updated_at = now() WHERE partner_id = $1
`

type UpdateAllAccessRatesByPartnerParams struct {
	PartnerID string `json:"partner_id"`
	RateBps   int32  `json:"rate_bps"`
}

func (q *Queries) UpdateAllAccessRatesByPartner(ctx context.Context, arg UpdateAllAccessRatesByPartnerParams) error {
	_, err := q.db.Exec(ctx, updateAllAccessRatesByPartner, arg.PartnerID, arg.RateBps)
	return err
}

const updateOffer = `-- name: UpdateOffer :one
UPDATE offers
SET name = COALESCE($1, name),
    category = COALESCE($2, category),
    description = COALESCE($3, description),
    destination_url = COALESCE($4, destination_url),
    status = COALESCE($5, status),
    updated_at = now()
WHERE id = $6
RETURNING id, project_id, name, category, description, destination_url, status, created_at, updated_at
`

type UpdateOfferParams struct {
	Name           pgtype.Text `json:"name"`
	Category       pgtype.Text `json:"category"`
	Description    pgtype.Text `json:"description"`
	DestinationUrl pgtype.Text `json:"destination_url"`
	Status         pgtype.Text `json:"status"`
	ID             string      `json:"id"`
}

type UpdateOfferRow struct {
	ID             string             `json:"id"`
	ProjectID      string             `json:"project_id"`
	Name           string             `json:"name"`
	Category       pgtype.Text        `json:"category"`
	Description    pgtype.Text        `json:"description"`
	DestinationUrl pgtype.Text        `json:"destination_url"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOffer(ctx context.Context, arg UpdateOfferParams) (UpdateOfferRow, error) {
	row := q.db.QueryRow(ctx, updateOffer,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.DestinationUrl,
		arg.Status,
		arg.ID,
	)
	var i UpdateOfferRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.DestinationUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePartnerAccessRate = `-- name: UpdatePartnerAccessRate :one
UPDATE partner_offer_accesses SET rate_bps = $3, updated_at = now()
WHERE partner_id = $1 AND offer_id = $2
RETURNING id, partner_id, offer_id, rate_bps, status, created_at, updated_at
`

type UpdatePartnerAccessRateParams struct {
	PartnerID string `json:"partner_id"`
	OfferID   string `json:"offer_id"`
	RateBps   int32  `json:"rate_bps"`
}

func (q *Queries) UpdatePartnerAccessRate(ctx context.Context, arg UpdatePartnerAccessRateParams) (PartnerOfferAccess, error) {
	row := q.db.QueryRow(ctx, updatePartnerAccessRate, arg.PartnerID, arg.OfferID, arg.RateBps)
	var i PartnerOfferAccess
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.OfferID,
		&i.RateBps,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSourceGroup = `-- name: UpdateSourceGroup :one
UPDATE source_groups SET name = $2, comment = $3, updated_at = now()
WHERE id = $1 RETURNING id, partner_id, name, comment, legacy_kazik_group_id, created_at, updated_at
`

type UpdateSourceGroupParams struct {
	ID      string      `json:"id"`
	Name    string      `json:"name"`
	Comment pgtype.Text `json:"comment"`
}

func (q *Queries) UpdateSourceGroup(ctx context.Context, arg UpdateSourceGroupParams) (SourceGroup, error) {
	row := q.db.QueryRow(ctx, updateSourceGroup, arg.ID, arg.Name, arg.Comment)
	var i SourceGroup
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.Name,
		&i.Comment,
		&i.LegacyKazikGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTrackingLink = `-- name: UpdateTrackingLink :one
UPDATE tracking_links
SET name = $2,
    code = $3,
    comment = $4,
    group_id = $5,
    is_active = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, partner_offer_access_id, code, name, comment, group_id, is_default, is_active, type, registration_bonus, domain, redirect_id, legacy_kazik_source_id, created_at, updated_at
`

type UpdateTrackingLinkParams struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	Code     string      `json:"code"`
	Comment  pgtype.Text `json:"comment"`
	GroupID  pgtype.UUID `json:"group_id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateTrackingLink(ctx context.Context, arg UpdateTrackingLinkParams) (TrackingLink, error) {
	row := q.db.QueryRow(ctx, updateTrackingLink,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Comment,
		arg.GroupID,
		arg.IsActive,
	)
	var i TrackingLink
	err := row.Scan(
		&i.ID,
		&i.PartnerOfferAccessID,
		&i.Code,
		&i.Name,
		&i.Comment,
		&i.GroupID,
		&i.IsDefault,
		&i.IsActive,
		&i.Type,
		&i.RegistrationBonus,
		&i.Domain,
		&i.RedirectID,
		&i.LegacyKazikSourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTrackingLinkFull = `-- name: UpdateTrackingLinkFull :one
UPDATE tracking_links
SET name = COALESCE($1, name),
    code = COALESCE($2, code),
    comment = COALESCE($3, comment),
    group_id = COALESCE($4, group_id),
    is_active = COALESCE($5, is_active),
    type = COALESCE($6, type),
    registration_bonus = COALESCE($7, registration_bonus),
    domain = COALESCE($8, domain),
    redirect_id = COALESCE($9, redirect_id),
    updated_at = now()
WHERE id = $10
RETURNING id, partner_offer_access_id, code, name, comment, group_id, is_default, is_active, type, registration_bonus, domain, redirect_id, legacy_kazik_source_id, created_at, updated_at
`

type UpdateTrackingLinkFullParams struct {
	Name              pgtype.Text `json:"name"`
	Code              pgtype.Text `json:"code"`
	Comment           pgtype.Text `json:"comment"`
	GroupID           pgtype.UUID `json:"group_id"`
	IsActive          pgtype.Bool `json:"is_active"`
	Type              pgtype.Text `json:"type"`
	RegistrationBonus pgtype.Int4 `json:"registration_bonus"`
	Domain            pgtype.Text `json:"domain"`
	RedirectID        pgtype.UUID `json:"redirect_id"`
	ID                string      `json:"id"`
}

func (q *Queries) UpdateTrackingLinkFull(ctx context.Context, arg UpdateTrackingLinkFullParams) (TrackingLink, error) {
	row := q.db.QueryRow(ctx, updateTrackingLinkFull,
		arg.Name,
		arg.Code,
		arg.Comment,
		arg.GroupID,
		arg.IsActive,
		arg.Type,
		arg.RegistrationBonus,
		arg.Domain,
		arg.RedirectID,
		arg.ID,
	)
	var i TrackingLink
	err := row.Scan(
		&i.ID,
		&i.PartnerOfferAccessID,
		&i.Code,
		&i.Name,
		&i.Comment,
		&i.GroupID,
		&i.IsDefault,
		&i.IsActive,
		&i.Type,
		&i.RegistrationBonus,
		&i.Domain,
		&i.RedirectID,
		&i.LegacyKazikSourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
