// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offer_domains.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearMainOfferDomain = `-- name: ClearMainOfferDomain :exec
UPDATE offer_domains SET is_main = false, updated_at = now()
WHERE offer_id = $1 AND is_main = true
`

func (q *Queries) ClearMainOfferDomain(ctx context.Context, offerID string) error {
	_, err := q.db.Exec(ctx, clearMainOfferDomain, offerID)
	return err
}

const countOfferDomains = `-- name: CountOfferDomains :one
SELECT count(*) FROM offer_domains WHERE offer_id = $1
`

func (q *Queries) CountOfferDomains(ctx context.Context, offerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOfferDomains, offerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOfferDomain = `-- name: CreateOfferDomain :one
INSERT INTO offer_domains (offer_id, url, is_main, is_active, comment)
VALUES ($1, $2, $3, $4, $5) RETURNING id, offer_id, url, is_main, is_active, comment, created_at, updated_at
`

type CreateOfferDomainParams struct {
	OfferID  string      `json:"offer_id"`
	Url      string      `json:"url"`
	IsMain   bool        `json:"is_main"`
	IsActive bool        `json:"is_active"`
	Comment  pgtype.Text `json:"comment"`
}

func (q *Queries) CreateOfferDomain(ctx context.Context, arg CreateOfferDomainParams) (OfferDomain, error) {
	row := q.db.QueryRow(ctx, createOfferDomain,
		arg.OfferID,
		arg.Url,
		arg.IsMain,
		arg.IsActive,
		arg.Comment,
	)
	var i OfferDomain
	err := row.Scan(
		&i.ID,
		&i.OfferID,
		&i.Url,
		&i.IsMain,
		&i.IsActive,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOfferDomain = `-- name: DeleteOfferDomain :exec
DELETE FROM offer_domains WHERE id = $1
`

func (q *Queries) DeleteOfferDomain(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteOfferDomain, id)
	return err
}

const getMainOfferDomain = `-- name: GetMainOfferDomain :one
SELECT id, offer_id, url, is_main, is_active, comment, created_at, updated_at FROM offer_domains WHERE offer_id = $1 AND is_main = true AND is_active = true LIMIT 1
`

func (q *Queries) GetMainOfferDomain(ctx context.Context, offerID string) (OfferDomain, error) {
	row := q.db.QueryRow(ctx, getMainOfferDomain, offerID)
	var i OfferDomain
	err := row.Scan(
		&i.ID,
		&i.OfferID,
		&i.Url,
		&i.IsMain,
		&i.IsActive,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOfferDomainByID = `-- name: GetOfferDomainByID :one
SELECT id, offer_id, url, is_main, is_active, comment, created_at, updated_at FROM offer_domains WHERE id = $1
`

func (q *Queries) GetOfferDomainByID(ctx context.Context, id string) (OfferDomain, error) {
	row := q.db.QueryRow(ctx, getOfferDomainByID, id)
	var i OfferDomain
	err := row.Scan(
		&i.ID,
		&i.OfferID,
		&i.Url,
		&i.IsMain,
		&i.IsActive,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOfferDomainByOfferAndID = `-- name: GetOfferDomainByOfferAndID :one
SELECT id, offer_id, url, is_main, is_active, comment, created_at, updated_at FROM offer_domains WHERE id = $1 AND offer_id = $2
`

type GetOfferDomainByOfferAndIDParams struct {
	ID      string `json:"id"`
	OfferID string `json:"offer_id"`
}

func (q *Queries) GetOfferDomainByOfferAndID(ctx context.Context, arg GetOfferDomainByOfferAndIDParams) (OfferDomain, error) {
	row := q.db.QueryRow(ctx, getOfferDomainByOfferAndID, arg.ID, arg.OfferID)
	var i OfferDomain
	err := row.Scan(
		&i.ID,
		&i.OfferID,
		&i.Url,
		&i.IsMain,
		&i.IsActive,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveOfferDomains = `-- name: ListActiveOfferDomains :many
SELECT id, offer_id, url, is_main, is_active, comment, created_at, updated_at FROM offer_domains WHERE offer_id = $1 AND is_active = true ORDER BY is_main DESC, created_at
`

func (q *Queries) ListActiveOfferDomains(ctx context.Context, offerID string) ([]OfferDomain, error) {
	rows, err := q.db.Query(ctx, listActiveOfferDomains, offerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OfferDomain
	for rows.Next() {
		var i OfferDomain
		if err := rows.Scan(
			&i.ID,
			&i.OfferID,
			&i.Url,
			&i.IsMain,
			&i.IsActive,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfferDomains = `-- name: ListOfferDomains :many
SELECT id, offer_id, url, is_main, is_active, comment, created_at, updated_at FROM offer_domains WHERE offer_id = $1 ORDER BY is_main DESC, created_at
`

func (q *Queries) ListOfferDomains(ctx context.Context, offerID string) ([]OfferDomain, error) {
	rows, err := q.db.Query(ctx, listOfferDomains, offerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OfferDomain
	for rows.Next() {
		var i OfferDomain
		if err := rows.Scan(
			&i.ID,
			&i.OfferID,
			&i.Url,
			&i.IsMain,
			&i.IsActive,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOfferDomainMain = `-- name: SetOfferDomainMain :exec
UPDATE offer_domains SET is_main = $2, updated_at = now() WHERE id = $1
`

type SetOfferDomainMainParams struct {
	ID     string `json:"id"`
	IsMain bool   `json:"is_main"`
}

func (q *Queries) SetOfferDomainMain(ctx context.Context, arg SetOfferDomainMainParams) error {
	_, err := q.db.Exec(ctx, setOfferDomainMain, arg.ID, arg.IsMain)
	return err
}

const updateOfferDomain = `-- name: UpdateOfferDomain :one
UPDATE offer_domains
SET url = COALESCE($1, url),
    is_active = COALESCE($2, is_active),
    comment = COALESCE($3, comment),
    updated_at = now()
WHERE id = $4 RETURNING id, offer_id, url, is_main, is_active, comment, created_at, updated_at
`

type UpdateOfferDomainParams struct {
	Url      pgtype.Text `json:"url"`
	IsActive pgtype.Bool `json:"is_active"`
	Comment  pgtype.Text `json:"comment"`
	ID       string      `json:"id"`
}

func (q *Queries) UpdateOfferDomain(ctx context.Context, arg UpdateOfferDomainParams) (OfferDomain, error) {
	row := q.db.QueryRow(ctx, updateOfferDomain,
		arg.Url,
		arg.IsActive,
		arg.Comment,
		arg.ID,
	)
	var i OfferDomain
	err := row.Scan(
		&i.ID,
		&i.OfferID,
		&i.Url,
		&i.IsMain,
		&i.IsActive,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
