// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: partner_domains.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPartnerDomain = `-- name: CreatePartnerDomain :one
INSERT INTO partner_domains (url, is_active, comment, legacy_kazik_domain_id)
VALUES ($1, $2, $3, $4) RETURNING id, url, is_active, comment, legacy_kazik_domain_id, created_at, updated_at
`

type CreatePartnerDomainParams struct {
	Url                 string      `json:"url"`
	IsActive            bool        `json:"is_active"`
	Comment             pgtype.Text `json:"comment"`
	LegacyKazikDomainID pgtype.Text `json:"legacy_kazik_domain_id"`
}

func (q *Queries) CreatePartnerDomain(ctx context.Context, arg CreatePartnerDomainParams) (PartnerDomain, error) {
	row := q.db.QueryRow(ctx, createPartnerDomain,
		arg.Url,
		arg.IsActive,
		arg.Comment,
		arg.LegacyKazikDomainID,
	)
	var i PartnerDomain
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.IsActive,
		&i.Comment,
		&i.LegacyKazikDomainID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePartnerDomain = `-- name: DeletePartnerDomain :exec
DELETE FROM partner_domains WHERE id = $1
`

func (q *Queries) DeletePartnerDomain(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePartnerDomain, id)
	return err
}

const getPartnerDomainByID = `-- name: GetPartnerDomainByID :one
SELECT id, url, is_active, comment, legacy_kazik_domain_id, created_at, updated_at FROM partner_domains WHERE id = $1
`

func (q *Queries) GetPartnerDomainByID(ctx context.Context, id string) (PartnerDomain, error) {
	row := q.db.QueryRow(ctx, getPartnerDomainByID, id)
	var i PartnerDomain
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.IsActive,
		&i.Comment,
		&i.LegacyKazikDomainID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartnerDomainByLegacyID = `-- name: GetPartnerDomainByLegacyID :one
SELECT id, url, is_active, comment, legacy_kazik_domain_id, created_at, updated_at FROM partner_domains WHERE legacy_kazik_domain_id = $1
`

func (q *Queries) GetPartnerDomainByLegacyID(ctx context.Context, legacyKazikDomainID pgtype.Text) (PartnerDomain, error) {
	row := q.db.QueryRow(ctx, getPartnerDomainByLegacyID, legacyKazikDomainID)
	var i PartnerDomain
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.IsActive,
		&i.Comment,
		&i.LegacyKazikDomainID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartnerDomainByURL = `-- name: GetPartnerDomainByURL :one
SELECT id, url, is_active, comment, legacy_kazik_domain_id, created_at, updated_at FROM partner_domains WHERE url = $1
`

func (q *Queries) GetPartnerDomainByURL(ctx context.Context, url string) (PartnerDomain, error) {
	row := q.db.QueryRow(ctx, getPartnerDomainByURL, url)
	var i PartnerDomain
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.IsActive,
		&i.Comment,
		&i.LegacyKazikDomainID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePartnerDomains = `-- name: ListActivePartnerDomains :many
SELECT id, url, is_active, comment, legacy_kazik_domain_id, created_at, updated_at FROM partner_domains WHERE is_active = true ORDER BY created_at DESC
`

func (q *Queries) ListActivePartnerDomains(ctx context.Context) ([]PartnerDomain, error) {
	rows, err := q.db.Query(ctx, listActivePartnerDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerDomain
	for rows.Next() {
		var i PartnerDomain
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.IsActive,
			&i.Comment,
			&i.LegacyKazikDomainID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerDomains = `-- name: ListPartnerDomains :many
SELECT id, url, is_active, comment, legacy_kazik_domain_id, created_at, updated_at FROM partner_domains ORDER BY created_at DESC
`

func (q *Queries) ListPartnerDomains(ctx context.Context) ([]PartnerDomain, error) {
	rows, err := q.db.Query(ctx, listPartnerDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerDomain
	for rows.Next() {
		var i PartnerDomain
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.IsActive,
			&i.Comment,
			&i.LegacyKazikDomainID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePartnerDomain = `-- name: UpdatePartnerDomain :one
UPDATE partner_domains
SET url = COALESCE($1, url),
    is_active = COALESCE($2, is_active),
    comment = COALESCE($3, comment),
    updated_at = now()
WHERE id = $4 RETURNING id, url, is_active, comment, legacy_kazik_domain_id, created_at, updated_at
`

type UpdatePartnerDomainParams struct {
	Url      pgtype.Text `json:"url"`
	IsActive pgtype.Bool `json:"is_active"`
	Comment  pgtype.Text `json:"comment"`
	ID       string      `json:"id"`
}

func (q *Queries) UpdatePartnerDomain(ctx context.Context, arg UpdatePartnerDomainParams) (PartnerDomain, error) {
	row := q.db.QueryRow(ctx, updatePartnerDomain,
		arg.Url,
		arg.IsActive,
		arg.Comment,
		arg.ID,
	)
	var i PartnerDomain
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.IsActive,
		&i.Comment,
		&i.LegacyKazikDomainID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
