// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payouts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWithdrawalsAdmin = `-- name: CountWithdrawalsAdmin :one
SELECT count(*) FROM withdrawal_requests w
WHERE ($1 = '' OR w.status = $1)
  AND ($2 = '' OR w.partner_id = $2::uuid)
`

type CountWithdrawalsAdminParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) CountWithdrawalsAdmin(ctx context.Context, arg CountWithdrawalsAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWithdrawalsAdmin, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const decideWithdrawal = `-- name: DecideWithdrawal :one
UPDATE withdrawal_requests
SET status = $2, comment = COALESCE($3, comment), decided_at = now(), updated_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, partner_id, amount_kopecks, method, requisites, bank, fee_kopecks, usdt_amount, rate, status, comment, decided_at, paid_at, created_at, updated_at
`

type DecideWithdrawalParams struct {
	ID      string      `json:"id"`
	Status  string      `json:"status"`
	Comment pgtype.Text `json:"comment"`
}

func (q *Queries) DecideWithdrawal(ctx context.Context, arg DecideWithdrawalParams) (WithdrawalRequest, error) {
	row := q.db.QueryRow(ctx, decideWithdrawal, arg.ID, arg.Status, arg.Comment)
	var i WithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AmountKopecks,
		&i.Method,
		&i.Requisites,
		&i.Bank,
		&i.FeeKopecks,
		&i.UsdtAmount,
		&i.Rate,
		&i.Status,
		&i.Comment,
		&i.DecidedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayoutRules = `-- name: GetPayoutRules :one
SELECT id, min_withdraw_kopecks, usdt_rate, sbp_fee_flat_kopecks, sbp_fee_percent_bps, updated_by, updated_at
FROM payout_rules WHERE id = '00000000-0000-0000-0000-000000000001'
`

func (q *Queries) GetPayoutRules(ctx context.Context) (PayoutRule, error) {
	row := q.db.QueryRow(ctx, getPayoutRules)
	var i PayoutRule
	err := row.Scan(
		&i.ID,
		&i.MinWithdrawKopecks,
		&i.UsdtRate,
		&i.SbpFeeFlatKopecks,
		&i.SbpFeePercentBps,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getWithdrawalRequest = `-- name: GetWithdrawalRequest :one
SELECT id, partner_id, amount_kopecks, method, requisites, bank, fee_kopecks, usdt_amount, rate, status, comment, decided_at, paid_at, created_at, updated_at
FROM withdrawal_requests WHERE id = $1
`

func (q *Queries) GetWithdrawalRequest(ctx context.Context, id string) (WithdrawalRequest, error) {
	row := q.db.QueryRow(ctx, getWithdrawalRequest, id)
	var i WithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AmountKopecks,
		&i.Method,
		&i.Requisites,
		&i.Bank,
		&i.FeeKopecks,
		&i.UsdtAmount,
		&i.Rate,
		&i.Status,
		&i.Comment,
		&i.DecidedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPayoutTransfer = `-- name: InsertPayoutTransfer :one
INSERT INTO payout_transfers (withdrawal_request_id, external_tx_id, amount_kopecks, fee_kopecks, created_by, comment)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, withdrawal_request_id, external_tx_id, amount_kopecks, fee_kopecks, transferred_at, created_by, comment
`

type InsertPayoutTransferParams struct {
	WithdrawalRequestID string      `json:"withdrawal_request_id"`
	ExternalTxID        pgtype.Text `json:"external_tx_id"`
	AmountKopecks       int64       `json:"amount_kopecks"`
	FeeKopecks          int64       `json:"fee_kopecks"`
	CreatedBy           pgtype.UUID `json:"created_by"`
	Comment             pgtype.Text `json:"comment"`
}

func (q *Queries) InsertPayoutTransfer(ctx context.Context, arg InsertPayoutTransferParams) (PayoutTransfer, error) {
	row := q.db.QueryRow(ctx, insertPayoutTransfer,
		arg.WithdrawalRequestID,
		arg.ExternalTxID,
		arg.AmountKopecks,
		arg.FeeKopecks,
		arg.CreatedBy,
		arg.Comment,
	)
	var i PayoutTransfer
	err := row.Scan(
		&i.ID,
		&i.WithdrawalRequestID,
		&i.ExternalTxID,
		&i.AmountKopecks,
		&i.FeeKopecks,
		&i.TransferredAt,
		&i.CreatedBy,
		&i.Comment,
	)
	return i, err
}

const insertWithdrawalRequest = `-- name: InsertWithdrawalRequest :one
INSERT INTO withdrawal_requests (partner_id, amount_kopecks, method, requisites, bank, fee_kopecks, usdt_amount, rate)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, partner_id, amount_kopecks, method, requisites, bank, fee_kopecks, usdt_amount, rate, status, comment, decided_at, paid_at, created_at, updated_at
`

type InsertWithdrawalRequestParams struct {
	PartnerID     string         `json:"partner_id"`
	AmountKopecks int64          `json:"amount_kopecks"`
	Method        string         `json:"method"`
	Requisites    string         `json:"requisites"`
	Bank          pgtype.Text    `json:"bank"`
	FeeKopecks    int64          `json:"fee_kopecks"`
	UsdtAmount    pgtype.Numeric `json:"usdt_amount"`
	Rate          pgtype.Numeric `json:"rate"`
}

func (q *Queries) InsertWithdrawalRequest(ctx context.Context, arg InsertWithdrawalRequestParams) (WithdrawalRequest, error) {
	row := q.db.QueryRow(ctx, insertWithdrawalRequest,
		arg.PartnerID,
		arg.AmountKopecks,
		arg.Method,
		arg.Requisites,
		arg.Bank,
		arg.FeeKopecks,
		arg.UsdtAmount,
		arg.Rate,
	)
	var i WithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AmountKopecks,
		&i.Method,
		&i.Requisites,
		&i.Bank,
		&i.FeeKopecks,
		&i.UsdtAmount,
		&i.Rate,
		&i.Status,
		&i.Comment,
		&i.DecidedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWithdrawalsAdmin = `-- name: ListWithdrawalsAdmin :many
SELECT w.id, w.partner_id, w.amount_kopecks, w.method, w.requisites, w.bank, w.fee_kopecks, w.usdt_amount, w.rate, w.status, w.comment, w.decided_at, w.paid_at, w.created_at, w.updated_at,
       u.name AS partner_name, u.email AS partner_email
FROM withdrawal_requests w
JOIN partner_profiles p ON p.id = w.partner_id
JOIN users u ON u.id = p.user_id
WHERE ($1 = '' OR w.status = $1)
  AND ($2 = '' OR w.partner_id = $2::uuid)
ORDER BY w.created_at DESC LIMIT $3 OFFSET $4
`

type ListWithdrawalsAdminParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListWithdrawalsAdminRow struct {
	ID            string             `json:"id"`
	PartnerID     string             `json:"partner_id"`
	AmountKopecks int64              `json:"amount_kopecks"`
	Method        string             `json:"method"`
	Requisites    string             `json:"requisites"`
	Bank          pgtype.Text        `json:"bank"`
	FeeKopecks    int64              `json:"fee_kopecks"`
	UsdtAmount    pgtype.Numeric     `json:"usdt_amount"`
	Rate          pgtype.Numeric     `json:"rate"`
	Status        string             `json:"status"`
	Comment       pgtype.Text        `json:"comment"`
	DecidedAt     pgtype.Timestamptz `json:"decided_at"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	PartnerName   string             `json:"partner_name"`
	PartnerEmail  string             `json:"partner_email"`
}

func (q *Queries) ListWithdrawalsAdmin(ctx context.Context, arg ListWithdrawalsAdminParams) ([]ListWithdrawalsAdminRow, error) {
	rows, err := q.db.Query(ctx, listWithdrawalsAdmin,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWithdrawalsAdminRow
	for rows.Next() {
		var i ListWithdrawalsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.AmountKopecks,
			&i.Method,
			&i.Requisites,
			&i.Bank,
			&i.FeeKopecks,
			&i.UsdtAmount,
			&i.Rate,
			&i.Status,
			&i.Comment,
			&i.DecidedAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PartnerName,
			&i.PartnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawalsByPartner = `-- name: ListWithdrawalsByPartner :many
SELECT id, partner_id, amount_kopecks, method, requisites, bank, fee_kopecks, usdt_amount, rate, status, comment, decided_at, paid_at, created_at, updated_at
FROM withdrawal_requests WHERE partner_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListWithdrawalsByPartnerParams struct {
	PartnerID string `json:"partner_id"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListWithdrawalsByPartner(ctx context.Context, arg ListWithdrawalsByPartnerParams) ([]WithdrawalRequest, error) {
	rows, err := q.db.Query(ctx, listWithdrawalsByPartner, arg.PartnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WithdrawalRequest
	for rows.Next() {
		var i WithdrawalRequest
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.AmountKopecks,
			&i.Method,
			&i.Requisites,
			&i.Bank,
			&i.FeeKopecks,
			&i.UsdtAmount,
			&i.Rate,
			&i.Status,
			&i.Comment,
			&i.DecidedAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWithdrawalPaid = `-- name: MarkWithdrawalPaid :one
UPDATE withdrawal_requests
SET status = 'paid', comment = COALESCE($2, comment), paid_at = now(), updated_at = now()
WHERE id = $1 AND status = 'approved'
RETURNING id, partner_id, amount_kopecks, method, requisites, bank, fee_kopecks, usdt_amount, rate, status, comment, decided_at, paid_at, created_at, updated_at
`

type MarkWithdrawalPaidParams struct {
	ID      string      `json:"id"`
	Comment pgtype.Text `json:"comment"`
}

func (q *Queries) MarkWithdrawalPaid(ctx context.Context, arg MarkWithdrawalPaidParams) (WithdrawalRequest, error) {
	row := q.db.QueryRow(ctx, markWithdrawalPaid, arg.ID, arg.Comment)
	var i WithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.AmountKopecks,
		&i.Method,
		&i.Requisites,
		&i.Bank,
		&i.FeeKopecks,
		&i.UsdtAmount,
		&i.Rate,
		&i.Status,
		&i.Comment,
		&i.DecidedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePayoutRules = `-- name: UpdatePayoutRules :one
UPDATE payout_rules
SET min_withdraw_kopecks = $1, usdt_rate = $2, sbp_fee_flat_kopecks = $3, sbp_fee_percent_bps = $4,
    updated_by = $5, updated_at = now()
WHERE id = '00000000-0000-0000-0000-000000000001'
RETURNING id, min_withdraw_kopecks, usdt_rate, sbp_fee_flat_kopecks, sbp_fee_percent_bps, updated_by, updated_at
`

type UpdatePayoutRulesParams struct {
	MinWithdrawKopecks int64          `json:"min_withdraw_kopecks"`
	UsdtRate           pgtype.Numeric `json:"usdt_rate"`
	SbpFeeFlatKopecks  int64          `json:"sbp_fee_flat_kopecks"`
	SbpFeePercentBps   int32          `json:"sbp_fee_percent_bps"`
	UpdatedBy          pgtype.UUID    `json:"updated_by"`
}

func (q *Queries) UpdatePayoutRules(ctx context.Context, arg UpdatePayoutRulesParams) (PayoutRule, error) {
	row := q.db.QueryRow(ctx, updatePayoutRules,
		arg.MinWithdrawKopecks,
		arg.UsdtRate,
		arg.SbpFeeFlatKopecks,
		arg.SbpFeePercentBps,
		arg.UpdatedBy,
	)
	var i PayoutRule
	err := row.Scan(
		&i.ID,
		&i.MinWithdrawKopecks,
		&i.UsdtRate,
		&i.SbpFeeFlatKopecks,
		&i.SbpFeePercentBps,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
