// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjects = `-- name: CountProjects :one
SELECT count(*) FROM projects
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIntegrationKey = `-- name: CreateIntegrationKey :one
INSERT INTO integration_keys (project_id, key_id, secret_ciphertext, secret_hint)
VALUES ($1, $2, $3, $4) RETURNING id, project_id, key_id, is_active, created_at, rotated_at, last_used_at, secret_hint
`

type CreateIntegrationKeyParams struct {
	ProjectID        string `json:"project_id"`
	KeyID            string `json:"key_id"`
	SecretCiphertext []byte `json:"secret_ciphertext"`
	SecretHint       string `json:"secret_hint"`
}

type CreateIntegrationKeyRow struct {
	ID         string             `json:"id"`
	ProjectID  string             `json:"project_id"`
	KeyID      string             `json:"key_id"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	RotatedAt  pgtype.Timestamptz `json:"rotated_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	SecretHint string             `json:"secret_hint"`
}

func (q *Queries) CreateIntegrationKey(ctx context.Context, arg CreateIntegrationKeyParams) (CreateIntegrationKeyRow, error) {
	row := q.db.QueryRow(ctx, createIntegrationKey,
		arg.ProjectID,
		arg.KeyID,
		arg.SecretCiphertext,
		arg.SecretHint,
	)
	var i CreateIntegrationKeyRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.KeyID,
		&i.IsActive,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.LastUsedAt,
		&i.SecretHint,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (slug, name, description, destination_url, is_active)
VALUES ($1, $2, $3, $4, $5) RETURNING id, slug, name, description, destination_url, is_active, created_at, updated_at
`

type CreateProjectParams struct {
	Slug           string      `json:"slug"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	DestinationUrl string      `json:"destination_url"`
	IsActive       bool        `json:"is_active"`
}

type CreateProjectRow struct {
	ID             string             `json:"id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	DestinationUrl string             `json:"destination_url"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.DestinationUrl,
		arg.IsActive,
	)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.DestinationUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateIntegrationKey = `-- name: DeactivateIntegrationKey :exec
UPDATE integration_keys SET is_active = false, rotated_at = COALESCE(rotated_at, now()) WHERE key_id = $1
`

func (q *Queries) DeactivateIntegrationKey(ctx context.Context, keyID string) error {
	_, err := q.db.Exec(ctx, deactivateIntegrationKey, keyID)
	return err
}

const getIntegrationKeyByKeyID = `-- name: GetIntegrationKeyByKeyID :one
SELECT id, project_id, key_id, secret_ciphertext, secret_hint, is_active, created_at, rotated_at, last_used_at
FROM integration_keys WHERE key_id = $1
`

func (q *Queries) GetIntegrationKeyByKeyID(ctx context.Context, keyID string) (IntegrationKey, error) {
	row := q.db.QueryRow(ctx, getIntegrationKeyByKeyID, keyID)
	var i IntegrationKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.KeyID,
		&i.SecretCiphertext,
		&i.SecretHint,
		&i.IsActive,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, slug, name, description, destination_url, is_active, created_at, updated_at FROM projects WHERE id = $1
`

type GetProjectByIDRow struct {
	ID             string             `json:"id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	DestinationUrl string             `json:"destination_url"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProjectByID(ctx context.Context, id string) (GetProjectByIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i GetProjectByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.DestinationUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, slug, name, description, destination_url, is_active, created_at, updated_at FROM projects WHERE slug = $1
`

type GetProjectBySlugRow struct {
	ID             string             `json:"id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	DestinationUrl string             `json:"destination_url"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (GetProjectBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i GetProjectBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.DestinationUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectSettings = `-- name: GetProjectSettings :one
SELECT project_id, allow_new_partners, comment, created_at, updated_at FROM project_settings WHERE project_id = $1
`

func (q *Queries) GetProjectSettings(ctx context.Context, projectID string) (ProjectSetting, error) {
	row := q.db.QueryRow(ctx, getProjectSettings, projectID)
	var i ProjectSetting
	err := row.Scan(
		&i.ProjectID,
		&i.AllowNewPartners,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIntegrationKeysByProject = `-- name: ListIntegrationKeysByProject :many
SELECT id, project_id, key_id, is_active, created_at, rotated_at, last_used_at, secret_hint
FROM integration_keys WHERE project_id = $1 ORDER BY created_at DESC
`

type ListIntegrationKeysByProjectRow struct {
	ID         string             `json:"id"`
	ProjectID  string             `json:"project_id"`
	KeyID      string             `json:"key_id"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	RotatedAt  pgtype.Timestamptz `json:"rotated_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	SecretHint string             `json:"secret_hint"`
}

func (q *Queries) ListIntegrationKeysByProject(ctx context.Context, projectID string) ([]ListIntegrationKeysByProjectRow, error) {
	rows, err := q.db.Query(ctx, listIntegrationKeysByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIntegrationKeysByProjectRow
	for rows.Next() {
		var i ListIntegrationKeysByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.KeyID,
			&i.IsActive,
			&i.CreatedAt,
			&i.RotatedAt,
			&i.LastUsedAt,
			&i.SecretHint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, slug, name, description, destination_url, is_active, created_at, updated_at
FROM projects ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListProjectsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProjectsRow struct {
	ID             string             `json:"id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	DestinationUrl string             `json:"destination_url"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.DestinationUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchIntegrationKey = `-- name: TouchIntegrationKey :exec
UPDATE integration_keys SET last_used_at = now() WHERE key_id = $1
`

func (q *Queries) TouchIntegrationKey(ctx context.Context, keyID string) error {
	_, err := q.db.Exec(ctx, touchIntegrationKey, keyID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    destination_url = COALESCE($3, destination_url),
    is_active = COALESCE($4, is_active),
    updated_at = now()
WHERE id = $5
RETURNING id, slug, name, description, destination_url, is_active, created_at, updated_at
`

type UpdateProjectParams struct {
	Name           pgtype.Text `json:"name"`
	Description    pgtype.Text `json:"description"`
	DestinationUrl pgtype.Text `json:"destination_url"`
	IsActive       pgtype.Bool `json:"is_active"`
	ID             string      `json:"id"`
}

type UpdateProjectRow struct {
	ID             string             `json:"id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	DestinationUrl string             `json:"destination_url"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.DestinationUrl,
		arg.IsActive,
		arg.ID,
	)
	var i UpdateProjectRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.DestinationUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectSettings = `-- name: UpsertProjectSettings :exec
INSERT INTO project_settings (project_id) VALUES ($1) ON CONFLICT (project_id) DO NOTHING
`

func (q *Queries) UpsertProjectSettings(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, upsertProjectSettings, projectID)
	return err
}
