// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Worker aggregation sources.
	AggClicksByDay(ctx context.Context, arg AggClicksByDayParams) ([]AggClicksByDayRow, error)
	AggClicksByLink(ctx context.Context, arg AggClicksByLinkParams) ([]AggClicksByLinkRow, error)
	// NOTE: despite the legacy column name, this counts EVERY deposit event
	// (conversion_events row = one real money top-up, see processConfirmed),
	// not first-ever payments per player. The dashboard "Deposits" cards must
	// reflect the fact of top-up: a repeat deposit by an existing player brings
	// income with no "first payment", so counting only firsts made income and
	// deposits diverge (e.g. income today with 0 deposits).
	AggFirstPaymentsByDay(ctx context.Context, arg AggFirstPaymentsByDayParams) ([]AggFirstPaymentsByDayRow, error)
	// Same as AggFirstPaymentsByDay but per traffic source: counts EVERY deposit
	// event (see note above), resolving the link from the attribution with the
	// click as fallback.
	AggFirstPaymentsByLink(ctx context.Context, arg AggFirstPaymentsByLinkParams) ([]AggFirstPaymentsByLinkRow, error)
	AggIncomeByDay(ctx context.Context, arg AggIncomeByDayParams) ([]AggIncomeByDayRow, error)
	AggIncomeByLink(ctx context.Context, arg AggIncomeByLinkParams) ([]AggIncomeByLinkRow, error)
	AggRegistrationsByDay(ctx context.Context, arg AggRegistrationsByDayParams) ([]AggRegistrationsByDayRow, error)
	AggRegistrationsByLink(ctx context.Context, arg AggRegistrationsByLinkParams) ([]AggRegistrationsByLinkRow, error)
	AggUniqueClicksByDay(ctx context.Context, arg AggUniqueClicksByDayParams) ([]AggUniqueClicksByDayRow, error)
	AggUniqueClicksByLink(ctx context.Context, arg AggUniqueClicksByLinkParams) ([]AggUniqueClicksByLinkRow, error)
	ClaimOutboxMessages(ctx context.Context, limit int32) ([]OutboxMessage, error)
	ClearDefaultTrackingLinks(ctx context.Context, partnerOfferAccessID string) error
	ClearMainOfferDomain(ctx context.Context, offerID string) error
	ConsumeReserve(ctx context.Context, arg ConsumeReserveParams) (ConsumeReserveRow, error)
	CountActiveLinksByAccess(ctx context.Context, partnerOfferAccessID string) (int64, error)
	CountAuditLog(ctx context.Context, arg CountAuditLogParams) (int64, error)
	CountClicksByLink(ctx context.Context, trackingLinkID string) (int64, error)
	CountEarningsAdmin(ctx context.Context, arg CountEarningsAdminParams) (int64, error)
	CountLedgerAdmin(ctx context.Context, arg CountLedgerAdminParams) (int64, error)
	CountOfferDomains(ctx context.Context, offerID string) (int64, error)
	CountOfferTerms(ctx context.Context, offerID string) (int64, error)
	CountOffers(ctx context.Context, dollar_1 interface{}) (int64, error)
	CountPartnerProfilesAdmin(ctx context.Context, arg CountPartnerProfilesAdminParams) (int64, error)
	CountProjects(ctx context.Context) (int64, error)
	CountRedirectPoolURLs(ctx context.Context, redirectID string) (int64, error)
	CountReferralsByReferrer(ctx context.Context, referrerPartnerID string) (int64, error)
	CountSourcesInGroup(ctx context.Context, groupID pgtype.UUID) (int64, error)
	CountTrackingLinksByPartner(ctx context.Context, partnerID string) (int64, error)
	CountUnreadUserNotifications(ctx context.Context, userID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWithdrawalsAdmin(ctx context.Context, arg CountWithdrawalsAdminParams) (int64, error)
	CreateAttribution(ctx context.Context, arg CreateAttributionParams) (ExternalUserAttribution, error)
	CreateIntegrationKey(ctx context.Context, arg CreateIntegrationKeyParams) (CreateIntegrationKeyRow, error)
	CreateOffer(ctx context.Context, arg CreateOfferParams) (CreateOfferRow, error)
	CreateOfferDomain(ctx context.Context, arg CreateOfferDomainParams) (OfferDomain, error)
	CreateOfferTerms(ctx context.Context, arg CreateOfferTermsParams) (OfferTermsVersion, error)
	CreatePartnerAccess(ctx context.Context, arg CreatePartnerAccessParams) (PartnerOfferAccess, error)
	CreatePartnerDomain(ctx context.Context, arg CreatePartnerDomainParams) (PartnerDomain, error)
	CreatePartnerProfile(ctx context.Context, arg CreatePartnerProfileParams) (PartnerProfile, error)
	CreatePartnerReferral(ctx context.Context, arg CreatePartnerReferralParams) (PartnerReferral, error)
	CreatePartnerReferralClick(ctx context.Context, arg CreatePartnerReferralClickParams) error
	CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error)
	CreateRedirectPool(ctx context.Context, arg CreateRedirectPoolParams) (RedirectPool, error)
	CreateRedirectPoolURL(ctx context.Context, arg CreateRedirectPoolURLParams) (RedirectPoolUrl, error)
	CreateSourceGroup(ctx context.Context, arg CreateSourceGroupParams) (SourceGroup, error)
	CreateStaffRoleAssignment(ctx context.Context, arg CreateStaffRoleAssignmentParams) error
	CreateTrackingClick(ctx context.Context, arg CreateTrackingClickParams) (TrackingClick, error)
	CreateTrackingLink(ctx context.Context, arg CreateTrackingLinkParams) (TrackingLink, error)
	CreateTrackingLinkFull(ctx context.Context, arg CreateTrackingLinkFullParams) (TrackingLink, error)
	CreateWallet(ctx context.Context, partnerID string) (CreateWalletRow, error)
	CreditWallet(ctx context.Context, arg CreditWalletParams) (CreditWalletRow, error)
	DeactivateIntegrationKey(ctx context.Context, keyID string) error
	DecideWithdrawal(ctx context.Context, arg DecideWithdrawalParams) (WithdrawalRequest, error)
	DeleteDailyLinkStatsFrom(ctx context.Context, day pgtype.Date) error
	DeleteDailyStatsFrom(ctx context.Context, day pgtype.Date) error
	DeleteOfferDomain(ctx context.Context, id string) error
	DeletePartnerDomain(ctx context.Context, id string) error
	DeleteRedirectPool(ctx context.Context, id string) error
	DeleteRedirectPoolURL(ctx context.Context, arg DeleteRedirectPoolURLParams) error
	DeleteSourceGroup(ctx context.Context, id string) error
	DeleteTrackingLink(ctx context.Context, id string) error
	EventLock(ctx context.Context, hashtextextended string) error
	GetAccessByID(ctx context.Context, id string) (PartnerOfferAccess, error)
	GetAnnouncement(ctx context.Context, id string) (Announcement, error)
	GetAnnouncementRead(ctx context.Context, arg GetAnnouncementReadParams) (AnnouncementRead, error)
	GetAttributionByProjectUser(ctx context.Context, arg GetAttributionByProjectUserParams) (ExternalUserAttribution, error)
	GetClickWithLink(ctx context.Context, id int64) (GetClickWithLinkRow, error)
	GetConversionByEvent(ctx context.Context, arg GetConversionByEventParams) (ConversionEvent, error)
	GetConversionByPayment(ctx context.Context, arg GetConversionByPaymentParams) (ConversionEvent, error)
	GetCurrentTerms(ctx context.Context, offerID string) (OfferTermsVersion, error)
	GetDailyStats(ctx context.Context, arg GetDailyStatsParams) ([]DailyPartnerOfferStat, error)
	GetDailyStatsByOffer(ctx context.Context, arg GetDailyStatsByOfferParams) ([]DailyPartnerOfferStat, error)
	GetDefaultTrackingLinkByAccessID(ctx context.Context, partnerOfferAccessID string) (TrackingLink, error)
	GetEarningByConversion(ctx context.Context, conversionEventID int64) (CommissionEarning, error)
	GetIncomingEvent(ctx context.Context, arg GetIncomingEventParams) (GetIncomingEventRow, error)
	GetIntegrationKeyByKeyID(ctx context.Context, keyID string) (IntegrationKey, error)
	GetMainOfferDomain(ctx context.Context, offerID string) (OfferDomain, error)
	GetOfferByID(ctx context.Context, id string) (GetOfferByIDRow, error)
	GetOfferDomainByID(ctx context.Context, id string) (OfferDomain, error)
	GetOfferDomainByOfferAndID(ctx context.Context, arg GetOfferDomainByOfferAndIDParams) (OfferDomain, error)
	GetOfferWithProject(ctx context.Context, id string) (GetOfferWithProjectRow, error)
	GetPartnerAccess(ctx context.Context, arg GetPartnerAccessParams) (PartnerOfferAccess, error)
	GetPartnerDomainByID(ctx context.Context, id string) (PartnerDomain, error)
	GetPartnerDomainByLegacyID(ctx context.Context, legacyKazikDomainID pgtype.Text) (PartnerDomain, error)
	GetPartnerDomainByURL(ctx context.Context, url string) (PartnerDomain, error)
	GetPartnerProfileByID(ctx context.Context, id string) (PartnerProfile, error)
	GetPartnerProfileByReferralCode(ctx context.Context, referralCode string) (PartnerProfile, error)
	GetPartnerProfileByUserID(ctx context.Context, userID string) (PartnerProfile, error)
	GetPartnerReferralByInvited(ctx context.Context, invitedPartnerID string) (PartnerReferral, error)
	GetPayoutRules(ctx context.Context) (PayoutRule, error)
	GetPlatformSetting(ctx context.Context, key string) (PlatformSetting, error)
	GetProjectByID(ctx context.Context, id string) (GetProjectByIDRow, error)
	GetProjectBySlug(ctx context.Context, slug string) (GetProjectBySlugRow, error)
	GetProjectSettings(ctx context.Context, projectID string) (ProjectSetting, error)
	GetRedirectPoolByID(ctx context.Context, id string) (RedirectPool, error)
	GetRedirectPoolByLegacyID(ctx context.Context, legacyKazikRedirectID pgtype.Text) (RedirectPool, error)
	GetRedirectPoolURL(ctx context.Context, arg GetRedirectPoolURLParams) (RedirectPoolUrl, error)
	GetRegistrationBonusByCode(ctx context.Context, code string) (pgtype.Int4, error)
	GetRewardByEarning(ctx context.Context, commissionEarningID string) (ReferralReward, error)
	GetSourceGroupByID(ctx context.Context, id string) (SourceGroup, error)
	GetStaffRolesByUserID(ctx context.Context, userID string) ([]GetStaffRolesByUserIDRow, error)
	GetTrackingLinkByCode(ctx context.Context, code string) (GetTrackingLinkByCodeRow, error)
	GetTrackingLinkByCodeExtended(ctx context.Context, code string) (TrackingLink, error)
	// Resolve a source (tracking link) by its code within one project's scope.
	// Used by the integrations API: promo-code attribution (registration.created
	// with source_code instead of click_token) and the source lookup endpoint.
	GetTrackingLinkByCodeForProject(ctx context.Context, arg GetTrackingLinkByCodeForProjectParams) (GetTrackingLinkByCodeForProjectRow, error)
	GetTrackingLinkByID(ctx context.Context, id string) (TrackingLink, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserByPartnerID(ctx context.Context, id string) (GetUserByPartnerIDRow, error)
	GetUserIDByPartnerID(ctx context.Context, id string) (string, error)
	GetWalletByID(ctx context.Context, id string) (GetWalletByIDRow, error)
	GetWalletByPartnerID(ctx context.Context, partnerID string) (GetWalletByPartnerIDRow, error)
	GetWithdrawalRequest(ctx context.Context, id string) (WithdrawalRequest, error)
	// a.tracking_link_id populated by 00022/00025 backfill and set on every
	// insert path; filtering on it directly lets Postgres use
	// attributions_link_firstseen_idx (the old COALESCE(click subquery) form
	// forced a full scan of external_user_attributions).
	HistoryAttributionsByLink(ctx context.Context, arg HistoryAttributionsByLinkParams) ([]HistoryAttributionsByLinkRow, error)
	// Cabinet offer history pieces.
	HistoryClicksByLink(ctx context.Context, arg HistoryClicksByLinkParams) ([]HistoryClicksByLinkRow, error)
	HistoryConversionsByLink(ctx context.Context, arg HistoryConversionsByLinkParams) ([]HistoryConversionsByLinkRow, error)
	HistoryEarningsByPartnerOffer(ctx context.Context, arg HistoryEarningsByPartnerOfferParams) ([]HistoryEarningsByPartnerOfferRow, error)
	InsertAnnouncement(ctx context.Context, arg InsertAnnouncementParams) (Announcement, error)
	InsertAnnouncementAudience(ctx context.Context, arg InsertAnnouncementAudienceParams) error
	InsertAnnouncementRead(ctx context.Context, arg InsertAnnouncementReadParams) error
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertCommissionEarning(ctx context.Context, arg InsertCommissionEarningParams) (CommissionEarning, error)
	InsertConversion(ctx context.Context, arg InsertConversionParams) (ConversionEvent, error)
	InsertIncomingEvent(ctx context.Context, arg InsertIncomingEventParams) (InsertIncomingEventRow, error)
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (InsertLedgerEntryRow, error)
	InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) (OutboxMessage, error)
	InsertPayoutTransfer(ctx context.Context, arg InsertPayoutTransferParams) (PayoutTransfer, error)
	InsertReferralReward(ctx context.Context, arg InsertReferralRewardParams) (ReferralReward, error)
	InsertUserNotification(ctx context.Context, arg InsertUserNotificationParams) error
	InsertWithdrawalRequest(ctx context.Context, arg InsertWithdrawalRequestParams) (WithdrawalRequest, error)
	ListAccessRatesAll(ctx context.Context) ([]ListAccessRatesAllRow, error)
	ListActiveOfferDomains(ctx context.Context, offerID string) ([]OfferDomain, error)
	ListActivePartnerDomains(ctx context.Context) ([]PartnerDomain, error)
	ListAllActiveAccesses(ctx context.Context) ([]ListAllActiveAccessesRow, error)
	ListAnnouncementAudiencePartnerIDs(ctx context.Context, announcementID string) ([]pgtype.UUID, error)
	ListAnnouncements(ctx context.Context) ([]Announcement, error)
	ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]ListAuditLogRow, error)
	ListConversionsByAttribution(ctx context.Context, attributionID int64) ([]ConversionEvent, error)
	// Default link per access for all of the partner's accesses (same
	// is_default DESC, created_at preference as GetDefaultTrackingLinkByAccessID)
	// in a single query, instead of one query per offer in Summary/ListOffers.
	ListDefaultTrackingLinksByPartner(ctx context.Context, partnerID string) ([]TrackingLink, error)
	ListEarningsAdmin(ctx context.Context, arg ListEarningsAdminParams) ([]CommissionEarning, error)
	ListIntegrationKeysByProject(ctx context.Context, projectID string) ([]ListIntegrationKeysByProjectRow, error)
	ListLedgerAdmin(ctx context.Context, arg ListLedgerAdminParams) ([]ListLedgerAdminRow, error)
	ListLedgerByWallet(ctx context.Context, arg ListLedgerByWalletParams) ([]WalletLedgerEntry, error)
	// Active main domain per offer for a set of offers (batched form of
	// GetMainOfferDomain, used instead of one query per offer in Summary/ListOffers).
	ListMainOfferDomainsByOffers(ctx context.Context, dollar_1 []string) ([]OfferDomain, error)
	ListOfferDomains(ctx context.Context, offerID string) ([]OfferDomain, error)
	ListOffers(ctx context.Context, arg ListOffersParams) ([]ListOffersRow, error)
	ListOffersByProject(ctx context.Context, projectID string) ([]ListOffersByProjectRow, error)
	ListPartnerAccesses(ctx context.Context, partnerID string) ([]PartnerOfferAccess, error)
	ListPartnerAccessesWithOffer(ctx context.Context, partnerID string) ([]ListPartnerAccessesWithOfferRow, error)
	ListPartnerDomains(ctx context.Context) ([]PartnerDomain, error)
	ListPartnerProfilesAdmin(ctx context.Context, arg ListPartnerProfilesAdminParams) ([]ListPartnerProfilesAdminRow, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error)
	ListRedirectPoolURLs(ctx context.Context, redirectID string) ([]RedirectPoolUrl, error)
	ListRedirectPools(ctx context.Context) ([]RedirectPool, error)
	// Referrals of a partner with per-invited reward totals in a single round
	// trip. Replaces the per-referral SumRewardsByInvited loop. The correlated
	// sum uses the partial covering index referral_rewards_invited_idx
	// (migration 00026): an index-only scan per invited partner, no heap
	// access and no sort of the joined rewards.
	ListReferralsByReferrerWithRewards(ctx context.Context, referrerPartnerID string) ([]ListReferralsByReferrerWithRewardsRow, error)
	ListSourceGroupsByPartner(ctx context.Context, partnerID string) ([]SourceGroup, error)
	ListTrackingLinksByAccessID(ctx context.Context, partnerOfferAccessID string) ([]ListTrackingLinksByAccessIDRow, error)
	ListTrackingLinksByPartner(ctx context.Context, arg ListTrackingLinksByPartnerParams) ([]TrackingLink, error)
	// All tracking links of a partner across every offer they have access to,
	// with the offer id and group name. Backs GET /cabinet/sources (dashboard
	// needs all sources in one round trip instead of one request per offer).
	ListTrackingLinksByPartnerWithOffer(ctx context.Context, partnerID string) ([]ListTrackingLinksByPartnerWithOfferRow, error)
	ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]UserNotification, error)
	ListVisibleAnnouncements(ctx context.Context) ([]Announcement, error)
	ListWithdrawalsAdmin(ctx context.Context, arg ListWithdrawalsAdminParams) ([]ListWithdrawalsAdminRow, error)
	ListWithdrawalsByPartner(ctx context.Context, arg ListWithdrawalsByPartnerParams) ([]WithdrawalRequest, error)
	MarkAllUserNotificationsRead(ctx context.Context, userID string) error
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error
	MarkOutboxSent(ctx context.Context, id int64) error
	MarkUserNotificationRead(ctx context.Context, arg MarkUserNotificationReadParams) error
	MarkVisibleAnnouncementsRead(ctx context.Context, arg MarkVisibleAnnouncementsReadParams) error
	MarkWithdrawalPaid(ctx context.Context, arg MarkWithdrawalPaidParams) (WithdrawalRequest, error)
	PublishAnnouncement(ctx context.Context, id string) (Announcement, error)
	ReleaseReserve(ctx context.Context, arg ReleaseReserveParams) (ReleaseReserveRow, error)
	ReplaceAnnouncementAudiences(ctx context.Context, announcementID string) error
	ReserveWithdrawal(ctx context.Context, arg ReserveWithdrawalParams) (ReserveWithdrawalRow, error)
	ResolvePromoCode(ctx context.Context, code string) (TrackingLink, error)
	ReverseEarning(ctx context.Context, id string) (CommissionEarning, error)
	ReverseReward(ctx context.Context, id string) (ReferralReward, error)
	SearchTrackingLinks(ctx context.Context, arg SearchTrackingLinksParams) ([]TrackingLink, error)
	SetDefaultTrackingLink(ctx context.Context, id string) error
	SetOfferDomainMain(ctx context.Context, arg SetOfferDomainMainParams) error
	SetPartnerRevShare(ctx context.Context, arg SetPartnerRevShareParams) error
	SetPlatformSetting(ctx context.Context, arg SetPlatformSettingParams) (PlatformSetting, error)
	SoftDeleteAnnouncement(ctx context.Context, id string) error
	SumDailyLinkStats(ctx context.Context, arg SumDailyLinkStatsParams) (SumDailyLinkStatsRow, error)
	SumDailyLinkStatsAllTime(ctx context.Context, trackingLinkID string) (SumDailyLinkStatsAllTimeRow, error)
	// Batched per-source totals (all-time + windowed) for a set of links: one
	// index scan per link instead of two queries per link (N+1) in ListSources.
	// day_from is inclusive (start of the 30d window); rows before it count only
	// towards the all-time columns.
	SumDailyLinkStatsByLinks(ctx context.Context, arg SumDailyLinkStatsByLinksParams) ([]SumDailyLinkStatsByLinksRow, error)
	SumDailyStats(ctx context.Context, arg SumDailyStatsParams) (SumDailyStatsRow, error)
	SumDailyStatsAllTime(ctx context.Context, partnerID string) (SumDailyStatsAllTimeRow, error)
	SumDailyStatsByOffer(ctx context.Context, arg SumDailyStatsByOfferParams) (SumDailyStatsByOfferRow, error)
	// Per-offer totals for one partner over a period (used instead of a
	// per-offer loop in ListOffers / Summary).
	SumDailyStatsGroupedByOffer(ctx context.Context, arg SumDailyStatsGroupedByOfferParams) ([]SumDailyStatsGroupedByOfferRow, error)
	SumDailyStatsOfferAllTime(ctx context.Context, arg SumDailyStatsOfferAllTimeParams) (SumDailyStatsOfferAllTimeRow, error)
	SumRewardsByReferrer(ctx context.Context, referrerPartnerID string) (int64, error)
	TouchIntegrationKey(ctx context.Context, keyID string) error
	UpdateAllAccessRatesByPartner(ctx context.Context, arg UpdateAllAccessRatesByPartnerParams) error
	UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error)
	UpdateConversionNote(ctx context.Context, arg UpdateConversionNoteParams) error
	UpdateOffer(ctx context.Context, arg UpdateOfferParams) (UpdateOfferRow, error)
	UpdateOfferDomain(ctx context.Context, arg UpdateOfferDomainParams) (OfferDomain, error)
	UpdatePartnerAccessRate(ctx context.Context, arg UpdatePartnerAccessRateParams) (PartnerOfferAccess, error)
	UpdatePartnerDomain(ctx context.Context, arg UpdatePartnerDomainParams) (PartnerDomain, error)
	UpdatePartnerProfile(ctx context.Context, arg UpdatePartnerProfileParams) (PartnerProfile, error)
	UpdatePayoutRules(ctx context.Context, arg UpdatePayoutRulesParams) (PayoutRule, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error)
	UpdateRedirectPool(ctx context.Context, arg UpdateRedirectPoolParams) (RedirectPool, error)
	UpdateRedirectPoolURL(ctx context.Context, arg UpdateRedirectPoolURLParams) (RedirectPoolUrl, error)
	UpdateSourceGroup(ctx context.Context, arg UpdateSourceGroupParams) (SourceGroup, error)
	UpdateTrackingLink(ctx context.Context, arg UpdateTrackingLinkParams) (TrackingLink, error)
	UpdateTrackingLinkFull(ctx context.Context, arg UpdateTrackingLinkFullParams) (TrackingLink, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Per-source (tracking link) daily stats.
	UpsertDailyLinkStats(ctx context.Context, arg UpsertDailyLinkStatsParams) (DailyTrackingLinkStat, error)
	// Daily stats (worker aggregates and cabinet reads).
	UpsertDailyStats(ctx context.Context, arg UpsertDailyStatsParams) (DailyPartnerOfferStat, error)
	UpsertProjectSettings(ctx context.Context, projectID string) error
}

var _ Querier = (*Queries)(nil)
