// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Worker aggregation sources.
	AggClicksByDay(ctx context.Context, arg AggClicksByDayParams) ([]AggClicksByDayRow, error)
	AggClicksByLink(ctx context.Context, arg AggClicksByLinkParams) ([]AggClicksByLinkRow, error)
	AggFirstPaymentsByDay(ctx context.Context, arg AggFirstPaymentsByDayParams) ([]AggFirstPaymentsByDayRow, error)
	AggFirstPaymentsByLink(ctx context.Context, arg AggFirstPaymentsByLinkParams) ([]AggFirstPaymentsByLinkRow, error)
	AggIncomeByDay(ctx context.Context, arg AggIncomeByDayParams) ([]AggIncomeByDayRow, error)
	AggIncomeByLink(ctx context.Context, arg AggIncomeByLinkParams) ([]AggIncomeByLinkRow, error)
	AggRegistrationsByDay(ctx context.Context, arg AggRegistrationsByDayParams) ([]AggRegistrationsByDayRow, error)
	AggRegistrationsByLink(ctx context.Context, arg AggRegistrationsByLinkParams) ([]AggRegistrationsByLinkRow, error)
	AggUniqueClicksByDay(ctx context.Context, arg AggUniqueClicksByDayParams) ([]AggUniqueClicksByDayRow, error)
	AggUniqueClicksByLink(ctx context.Context, arg AggUniqueClicksByLinkParams) ([]AggUniqueClicksByLinkRow, error)
	ClaimOutboxMessages(ctx context.Context, limit int32) ([]OutboxMessage, error)
	ClearDefaultTrackingLinks(ctx context.Context, partnerOfferAccessID string) error
	ConsumeReserve(ctx context.Context, arg ConsumeReserveParams) (ConsumeReserveRow, error)
	CountActiveLinksByAccess(ctx context.Context, partnerOfferAccessID string) (int64, error)
	CountAuditLog(ctx context.Context, arg CountAuditLogParams) (int64, error)
	CountClicksByLink(ctx context.Context, trackingLinkID string) (int64, error)
	CountEarningsAdmin(ctx context.Context, arg CountEarningsAdminParams) (int64, error)
	CountLedgerAdmin(ctx context.Context, arg CountLedgerAdminParams) (int64, error)
	CountOfferTerms(ctx context.Context, offerID string) (int64, error)
	CountOffers(ctx context.Context, dollar_1 interface{}) (int64, error)
	CountPartnerProfilesAdmin(ctx context.Context, arg CountPartnerProfilesAdminParams) (int64, error)
	CountProjects(ctx context.Context) (int64, error)
	CountReferralsByReferrer(ctx context.Context, referrerPartnerID string) (int64, error)
	CountSourcesInGroup(ctx context.Context, groupID pgtype.UUID) (int64, error)
	CountUnreadUserNotifications(ctx context.Context, userID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWithdrawalsAdmin(ctx context.Context, arg CountWithdrawalsAdminParams) (int64, error)
	CreateAttribution(ctx context.Context, arg CreateAttributionParams) (ExternalUserAttribution, error)
	CreateIntegrationKey(ctx context.Context, arg CreateIntegrationKeyParams) (CreateIntegrationKeyRow, error)
	CreateOffer(ctx context.Context, arg CreateOfferParams) (CreateOfferRow, error)
	CreateOfferTerms(ctx context.Context, arg CreateOfferTermsParams) (OfferTermsVersion, error)
	CreatePartnerAccess(ctx context.Context, arg CreatePartnerAccessParams) (PartnerOfferAccess, error)
	CreatePartnerProfile(ctx context.Context, arg CreatePartnerProfileParams) (PartnerProfile, error)
	CreatePartnerReferral(ctx context.Context, arg CreatePartnerReferralParams) (PartnerReferral, error)
	CreatePartnerReferralClick(ctx context.Context, arg CreatePartnerReferralClickParams) error
	CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error)
	CreateSourceGroup(ctx context.Context, arg CreateSourceGroupParams) (SourceGroup, error)
	CreateStaffRoleAssignment(ctx context.Context, arg CreateStaffRoleAssignmentParams) error
	CreateTrackingClick(ctx context.Context, arg CreateTrackingClickParams) (TrackingClick, error)
	CreateTrackingLink(ctx context.Context, arg CreateTrackingLinkParams) (TrackingLink, error)
	CreateWallet(ctx context.Context, partnerID string) (Wallet, error)
	CreditWallet(ctx context.Context, arg CreditWalletParams) (CreditWalletRow, error)
	DeactivateIntegrationKey(ctx context.Context, keyID string) error
	DecideWithdrawal(ctx context.Context, arg DecideWithdrawalParams) (WithdrawalRequest, error)
	DeleteDailyLinkStatsFrom(ctx context.Context, day pgtype.Date) error
	DeleteDailyStatsFrom(ctx context.Context, day pgtype.Date) error
	DeleteSourceGroup(ctx context.Context, id string) error
	DeleteTrackingLink(ctx context.Context, id string) error
	EventLock(ctx context.Context, hashtextextended string) error
	GetAccessByID(ctx context.Context, id string) (PartnerOfferAccess, error)
	GetAnnouncement(ctx context.Context, id string) (Announcement, error)
	GetAnnouncementRead(ctx context.Context, arg GetAnnouncementReadParams) (AnnouncementRead, error)
	GetAttributionByProjectUser(ctx context.Context, arg GetAttributionByProjectUserParams) (ExternalUserAttribution, error)
	GetClickWithLink(ctx context.Context, id int64) (GetClickWithLinkRow, error)
	GetConversionByEvent(ctx context.Context, arg GetConversionByEventParams) (ConversionEvent, error)
	GetConversionByPayment(ctx context.Context, arg GetConversionByPaymentParams) (ConversionEvent, error)
	GetCurrentTerms(ctx context.Context, offerID string) (OfferTermsVersion, error)
	GetDailyStats(ctx context.Context, arg GetDailyStatsParams) ([]DailyPartnerOfferStat, error)
	GetDailyStatsByOffer(ctx context.Context, arg GetDailyStatsByOfferParams) ([]DailyPartnerOfferStat, error)
	GetDefaultTrackingLinkByAccessID(ctx context.Context, partnerOfferAccessID string) (TrackingLink, error)
	GetEarningByConversion(ctx context.Context, conversionEventID int64) (CommissionEarning, error)
	GetIncomingEvent(ctx context.Context, arg GetIncomingEventParams) (GetIncomingEventRow, error)
	GetIntegrationKeyByKeyID(ctx context.Context, keyID string) (IntegrationKey, error)
	GetOfferByID(ctx context.Context, id string) (GetOfferByIDRow, error)
	GetOfferWithProject(ctx context.Context, id string) (GetOfferWithProjectRow, error)
	GetPartnerAccess(ctx context.Context, arg GetPartnerAccessParams) (PartnerOfferAccess, error)
	GetPartnerProfileByID(ctx context.Context, id string) (PartnerProfile, error)
	GetPartnerProfileByReferralCode(ctx context.Context, referralCode string) (PartnerProfile, error)
	GetPartnerProfileByUserID(ctx context.Context, userID string) (PartnerProfile, error)
	GetPartnerReferralByInvited(ctx context.Context, invitedPartnerID string) (PartnerReferral, error)
	GetPayoutRules(ctx context.Context) (PayoutRule, error)
	GetPlatformSetting(ctx context.Context, key string) (PlatformSetting, error)
	GetProjectByID(ctx context.Context, id string) (GetProjectByIDRow, error)
	GetProjectBySlug(ctx context.Context, slug string) (GetProjectBySlugRow, error)
	GetProjectSettings(ctx context.Context, projectID string) (ProjectSetting, error)
	GetRewardByEarning(ctx context.Context, commissionEarningID string) (ReferralReward, error)
	GetSourceGroupByID(ctx context.Context, id string) (SourceGroup, error)
	GetStaffRolesByUserID(ctx context.Context, userID string) ([]GetStaffRolesByUserIDRow, error)
	GetTrackingLinkByCode(ctx context.Context, code string) (GetTrackingLinkByCodeRow, error)
	GetTrackingLinkByID(ctx context.Context, id string) (TrackingLink, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserByPartnerID(ctx context.Context, id string) (GetUserByPartnerIDRow, error)
	GetUserIDByPartnerID(ctx context.Context, id string) (string, error)
	GetWalletByID(ctx context.Context, id string) (Wallet, error)
	GetWalletByPartnerID(ctx context.Context, partnerID string) (Wallet, error)
	GetWithdrawalRequest(ctx context.Context, id string) (WithdrawalRequest, error)
	HistoryAttributionsByLink(ctx context.Context, arg HistoryAttributionsByLinkParams) ([]HistoryAttributionsByLinkRow, error)
	// Cabinet offer history pieces.
	HistoryClicksByLink(ctx context.Context, arg HistoryClicksByLinkParams) ([]HistoryClicksByLinkRow, error)
	HistoryConversionsByLink(ctx context.Context, arg HistoryConversionsByLinkParams) ([]HistoryConversionsByLinkRow, error)
	HistoryEarningsByPartnerOffer(ctx context.Context, arg HistoryEarningsByPartnerOfferParams) ([]HistoryEarningsByPartnerOfferRow, error)
	InsertAnnouncement(ctx context.Context, arg InsertAnnouncementParams) (Announcement, error)
	InsertAnnouncementAudience(ctx context.Context, arg InsertAnnouncementAudienceParams) error
	InsertAnnouncementRead(ctx context.Context, arg InsertAnnouncementReadParams) error
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertCommissionEarning(ctx context.Context, arg InsertCommissionEarningParams) (CommissionEarning, error)
	InsertConversion(ctx context.Context, arg InsertConversionParams) (ConversionEvent, error)
	InsertIncomingEvent(ctx context.Context, arg InsertIncomingEventParams) (InsertIncomingEventRow, error)
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (InsertLedgerEntryRow, error)
	InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) (OutboxMessage, error)
	InsertPayoutTransfer(ctx context.Context, arg InsertPayoutTransferParams) (PayoutTransfer, error)
	InsertReferralReward(ctx context.Context, arg InsertReferralRewardParams) (ReferralReward, error)
	InsertUserNotification(ctx context.Context, arg InsertUserNotificationParams) error
	InsertWithdrawalRequest(ctx context.Context, arg InsertWithdrawalRequestParams) (WithdrawalRequest, error)
	ListAccessRatesAll(ctx context.Context) ([]ListAccessRatesAllRow, error)
	ListAllActiveAccesses(ctx context.Context) ([]ListAllActiveAccessesRow, error)
	ListAnnouncementAudiencePartnerIDs(ctx context.Context, announcementID string) ([]pgtype.UUID, error)
	ListAnnouncements(ctx context.Context) ([]Announcement, error)
	ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]ListAuditLogRow, error)
	ListConversionsByAttribution(ctx context.Context, attributionID int64) ([]ConversionEvent, error)
	ListEarningsAdmin(ctx context.Context, arg ListEarningsAdminParams) ([]CommissionEarning, error)
	ListIntegrationKeysByProject(ctx context.Context, projectID string) ([]ListIntegrationKeysByProjectRow, error)
	ListLedgerAdmin(ctx context.Context, arg ListLedgerAdminParams) ([]ListLedgerAdminRow, error)
	ListLedgerByWallet(ctx context.Context, arg ListLedgerByWalletParams) ([]WalletLedgerEntry, error)
	ListOffers(ctx context.Context, arg ListOffersParams) ([]ListOffersRow, error)
	ListOffersByProject(ctx context.Context, projectID string) ([]ListOffersByProjectRow, error)
	ListPartnerAccesses(ctx context.Context, partnerID string) ([]PartnerOfferAccess, error)
	ListPartnerAccessesWithOffer(ctx context.Context, partnerID string) ([]ListPartnerAccessesWithOfferRow, error)
	ListPartnerProfilesAdmin(ctx context.Context, arg ListPartnerProfilesAdminParams) ([]ListPartnerProfilesAdminRow, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error)
	ListReferralsByReferrer(ctx context.Context, referrerPartnerID string) ([]ListReferralsByReferrerRow, error)
	ListSourceGroupsByPartner(ctx context.Context, partnerID string) ([]SourceGroup, error)
	ListTrackingLinksByAccessID(ctx context.Context, partnerOfferAccessID string) ([]ListTrackingLinksByAccessIDRow, error)
	ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]UserNotification, error)
	ListVisibleAnnouncements(ctx context.Context) ([]Announcement, error)
	ListWithdrawalsAdmin(ctx context.Context, arg ListWithdrawalsAdminParams) ([]ListWithdrawalsAdminRow, error)
	ListWithdrawalsByPartner(ctx context.Context, arg ListWithdrawalsByPartnerParams) ([]WithdrawalRequest, error)
	MarkAllUserNotificationsRead(ctx context.Context, userID string) error
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error
	MarkOutboxSent(ctx context.Context, id int64) error
	MarkUserNotificationRead(ctx context.Context, arg MarkUserNotificationReadParams) error
	MarkVisibleAnnouncementsRead(ctx context.Context, arg MarkVisibleAnnouncementsReadParams) error
	MarkWithdrawalPaid(ctx context.Context, arg MarkWithdrawalPaidParams) (WithdrawalRequest, error)
	PublishAnnouncement(ctx context.Context, id string) (Announcement, error)
	ReleaseReserve(ctx context.Context, arg ReleaseReserveParams) (ReleaseReserveRow, error)
	ReplaceAnnouncementAudiences(ctx context.Context, announcementID string) error
	ReserveWithdrawal(ctx context.Context, arg ReserveWithdrawalParams) (ReserveWithdrawalRow, error)
	ReverseEarning(ctx context.Context, id string) (CommissionEarning, error)
	ReverseReward(ctx context.Context, id string) (ReferralReward, error)
	SetDefaultTrackingLink(ctx context.Context, id string) error
	SetPartnerRevShare(ctx context.Context, arg SetPartnerRevShareParams) error
	SetPlatformSetting(ctx context.Context, arg SetPlatformSettingParams) (PlatformSetting, error)
	SoftDeleteAnnouncement(ctx context.Context, id string) error
	SumDailyLinkStats(ctx context.Context, arg SumDailyLinkStatsParams) (SumDailyLinkStatsRow, error)
	SumDailyLinkStatsAllTime(ctx context.Context, trackingLinkID string) (SumDailyLinkStatsAllTimeRow, error)
	SumDailyStats(ctx context.Context, arg SumDailyStatsParams) (SumDailyStatsRow, error)
	SumDailyStatsAllTime(ctx context.Context, partnerID string) (SumDailyStatsAllTimeRow, error)
	SumDailyStatsByOffer(ctx context.Context, arg SumDailyStatsByOfferParams) (SumDailyStatsByOfferRow, error)
	SumDailyStatsOfferAllTime(ctx context.Context, arg SumDailyStatsOfferAllTimeParams) (SumDailyStatsOfferAllTimeRow, error)
	SumRewardsByInvited(ctx context.Context, invitedPartnerID string) (int64, error)
	SumRewardsByReferrer(ctx context.Context, referrerPartnerID string) (int64, error)
	TouchIntegrationKey(ctx context.Context, keyID string) error
	UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error)
	UpdateConversionNote(ctx context.Context, arg UpdateConversionNoteParams) error
	UpdateAllAccessRatesByPartner(ctx context.Context, arg UpdateAllAccessRatesByPartnerParams) error
	UpdateOffer(ctx context.Context, arg UpdateOfferParams) (UpdateOfferRow, error)
	UpdatePartnerAccessRate(ctx context.Context, arg UpdatePartnerAccessRateParams) (PartnerOfferAccess, error)
	UpdatePartnerProfile(ctx context.Context, arg UpdatePartnerProfileParams) (PartnerProfile, error)
	UpdatePayoutRules(ctx context.Context, arg UpdatePayoutRulesParams) (PayoutRule, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error)
	UpdateSourceGroup(ctx context.Context, arg UpdateSourceGroupParams) (SourceGroup, error)
	UpdateTrackingLink(ctx context.Context, arg UpdateTrackingLinkParams) (TrackingLink, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Per-source (tracking link) daily stats.
	UpsertDailyLinkStats(ctx context.Context, arg UpsertDailyLinkStatsParams) (DailyTrackingLinkStat, error)
	// Daily stats (worker aggregates and cabinet reads).
	UpsertDailyStats(ctx context.Context, arg UpsertDailyStatsParams) (DailyPartnerOfferStat, error)
	UpsertProjectSettings(ctx context.Context, projectID string) error
}

var _ Querier = (*Queries)(nil)
