// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: redirect_pools.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRedirectPoolURLs = `-- name: CountRedirectPoolURLs :one
SELECT count(*) FROM redirect_pool_urls WHERE redirect_id = $1
`

func (q *Queries) CountRedirectPoolURLs(ctx context.Context, redirectID string) (int64, error) {
	row := q.db.QueryRow(ctx, countRedirectPoolURLs, redirectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRedirectPool = `-- name: CreateRedirectPool :one
INSERT INTO redirect_pools (name, comment, legacy_kazik_redirect_id)
VALUES ($1, $2, $3) RETURNING id, name, comment, legacy_kazik_redirect_id, created_at, updated_at
`

type CreateRedirectPoolParams struct {
	Name                  string      `json:"name"`
	Comment               pgtype.Text `json:"comment"`
	LegacyKazikRedirectID pgtype.Text `json:"legacy_kazik_redirect_id"`
}

func (q *Queries) CreateRedirectPool(ctx context.Context, arg CreateRedirectPoolParams) (RedirectPool, error) {
	row := q.db.QueryRow(ctx, createRedirectPool, arg.Name, arg.Comment, arg.LegacyKazikRedirectID)
	var i RedirectPool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Comment,
		&i.LegacyKazikRedirectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRedirectPoolURL = `-- name: CreateRedirectPoolURL :one
INSERT INTO redirect_pool_urls (redirect_id, url, weight, is_active, sort_order)
VALUES ($1, $2, $3, $4, $5) RETURNING id, redirect_id, url, weight, is_active, sort_order, created_at
`

type CreateRedirectPoolURLParams struct {
	RedirectID string `json:"redirect_id"`
	Url        string `json:"url"`
	Weight     int32  `json:"weight"`
	IsActive   bool   `json:"is_active"`
	SortOrder  int32  `json:"sort_order"`
}

func (q *Queries) CreateRedirectPoolURL(ctx context.Context, arg CreateRedirectPoolURLParams) (RedirectPoolUrl, error) {
	row := q.db.QueryRow(ctx, createRedirectPoolURL,
		arg.RedirectID,
		arg.Url,
		arg.Weight,
		arg.IsActive,
		arg.SortOrder,
	)
	var i RedirectPoolUrl
	err := row.Scan(
		&i.ID,
		&i.RedirectID,
		&i.Url,
		&i.Weight,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRedirectPool = `-- name: DeleteRedirectPool :exec
DELETE FROM redirect_pools WHERE id = $1
`

func (q *Queries) DeleteRedirectPool(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRedirectPool, id)
	return err
}

const deleteRedirectPoolURL = `-- name: DeleteRedirectPoolURL :exec
DELETE FROM redirect_pool_urls WHERE id = $1 AND redirect_id = $2
`

type DeleteRedirectPoolURLParams struct {
	ID         string `json:"id"`
	RedirectID string `json:"redirect_id"`
}

func (q *Queries) DeleteRedirectPoolURL(ctx context.Context, arg DeleteRedirectPoolURLParams) error {
	_, err := q.db.Exec(ctx, deleteRedirectPoolURL, arg.ID, arg.RedirectID)
	return err
}

const getRedirectPoolByID = `-- name: GetRedirectPoolByID :one
SELECT id, name, comment, legacy_kazik_redirect_id, created_at, updated_at FROM redirect_pools WHERE id = $1
`

func (q *Queries) GetRedirectPoolByID(ctx context.Context, id string) (RedirectPool, error) {
	row := q.db.QueryRow(ctx, getRedirectPoolByID, id)
	var i RedirectPool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Comment,
		&i.LegacyKazikRedirectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRedirectPoolByLegacyID = `-- name: GetRedirectPoolByLegacyID :one
SELECT id, name, comment, legacy_kazik_redirect_id, created_at, updated_at FROM redirect_pools WHERE legacy_kazik_redirect_id = $1
`

func (q *Queries) GetRedirectPoolByLegacyID(ctx context.Context, legacyKazikRedirectID pgtype.Text) (RedirectPool, error) {
	row := q.db.QueryRow(ctx, getRedirectPoolByLegacyID, legacyKazikRedirectID)
	var i RedirectPool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Comment,
		&i.LegacyKazikRedirectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRedirectPoolURL = `-- name: GetRedirectPoolURL :one
SELECT id, redirect_id, url, weight, is_active, sort_order, created_at FROM redirect_pool_urls WHERE id = $1 AND redirect_id = $2
`

type GetRedirectPoolURLParams struct {
	ID         string `json:"id"`
	RedirectID string `json:"redirect_id"`
}

func (q *Queries) GetRedirectPoolURL(ctx context.Context, arg GetRedirectPoolURLParams) (RedirectPoolUrl, error) {
	row := q.db.QueryRow(ctx, getRedirectPoolURL, arg.ID, arg.RedirectID)
	var i RedirectPoolUrl
	err := row.Scan(
		&i.ID,
		&i.RedirectID,
		&i.Url,
		&i.Weight,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listRedirectPoolURLs = `-- name: ListRedirectPoolURLs :many
SELECT id, redirect_id, url, weight, is_active, sort_order, created_at FROM redirect_pool_urls WHERE redirect_id = $1 ORDER BY sort_order
`

func (q *Queries) ListRedirectPoolURLs(ctx context.Context, redirectID string) ([]RedirectPoolUrl, error) {
	rows, err := q.db.Query(ctx, listRedirectPoolURLs, redirectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RedirectPoolUrl
	for rows.Next() {
		var i RedirectPoolUrl
		if err := rows.Scan(
			&i.ID,
			&i.RedirectID,
			&i.Url,
			&i.Weight,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRedirectPools = `-- name: ListRedirectPools :many
SELECT id, name, comment, legacy_kazik_redirect_id, created_at, updated_at FROM redirect_pools ORDER BY created_at DESC
`

func (q *Queries) ListRedirectPools(ctx context.Context) ([]RedirectPool, error) {
	rows, err := q.db.Query(ctx, listRedirectPools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RedirectPool
	for rows.Next() {
		var i RedirectPool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Comment,
			&i.LegacyKazikRedirectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRedirectPool = `-- name: UpdateRedirectPool :one
UPDATE redirect_pools
SET name = COALESCE($1, name),
    comment = COALESCE($2, comment),
    updated_at = now()
WHERE id = $3 RETURNING id, name, comment, legacy_kazik_redirect_id, created_at, updated_at
`

type UpdateRedirectPoolParams struct {
	Name    pgtype.Text `json:"name"`
	Comment pgtype.Text `json:"comment"`
	ID      string      `json:"id"`
}

func (q *Queries) UpdateRedirectPool(ctx context.Context, arg UpdateRedirectPoolParams) (RedirectPool, error) {
	row := q.db.QueryRow(ctx, updateRedirectPool, arg.Name, arg.Comment, arg.ID)
	var i RedirectPool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Comment,
		&i.LegacyKazikRedirectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRedirectPoolURL = `-- name: UpdateRedirectPoolURL :one
UPDATE redirect_pool_urls
SET url = COALESCE($1, url),
    weight = COALESCE($2, weight),
    is_active = COALESCE($3, is_active)
WHERE id = $4 AND redirect_id = $5 RETURNING id, redirect_id, url, weight, is_active, sort_order, created_at
`

type UpdateRedirectPoolURLParams struct {
	Url        pgtype.Text `json:"url"`
	Weight     pgtype.Int4 `json:"weight"`
	IsActive   pgtype.Bool `json:"is_active"`
	ID         string      `json:"id"`
	RedirectID string      `json:"redirect_id"`
}

func (q *Queries) UpdateRedirectPoolURL(ctx context.Context, arg UpdateRedirectPoolURLParams) (RedirectPoolUrl, error) {
	row := q.db.QueryRow(ctx, updateRedirectPoolURL,
		arg.Url,
		arg.Weight,
		arg.IsActive,
		arg.ID,
		arg.RedirectID,
	)
	var i RedirectPoolUrl
	err := row.Scan(
		&i.ID,
		&i.RedirectID,
		&i.Url,
		&i.Weight,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
