// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reliability.sql

package repository

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxMessages = `-- name: ClaimOutboxMessages :many
SELECT id, topic, payload, status, attempts, next_attempt_at, last_error, created_at, sent_at
FROM outbox_messages
WHERE status = 'pending' AND next_attempt_at <= now()
ORDER BY id LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimOutboxMessages(ctx context.Context, limit int32) ([]OutboxMessage, error) {
	rows, err := q.db.Query(ctx, claimOutboxMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxMessage
	for rows.Next() {
		var i OutboxMessage
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuditLog = `-- name: CountAuditLog :one
SELECT count(*) FROM audit_log
WHERE ($1 = '' OR entity_type = $1)
  AND ($2 = '' OR entity_id = $2)
`

type CountAuditLogParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) CountAuditLog(ctx context.Context, arg CountAuditLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLog, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPlatformSetting = `-- name: GetPlatformSetting :one
SELECT key, value, updated_at FROM platform_settings WHERE key = $1
`

func (q *Queries) GetPlatformSetting(ctx context.Context, key string) (PlatformSetting, error) {
	row := q.db.QueryRow(ctx, getPlatformSetting, key)
	var i PlatformSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (actor_user_id, action, entity_type, entity_id, changes, ip)
VALUES ($1, $2, $3, $4, $5, NULLIF($6, '')::inet)
`

type InsertAuditLogParams struct {
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Action      string      `json:"action"`
	EntityType  string      `json:"entity_type"`
	EntityID    string      `json:"entity_id"`
	Changes     []byte      `json:"changes"`
	Column6     interface{} `json:"column_6"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Changes,
		arg.Column6,
	)
	return err
}

const insertOutboxMessage = `-- name: InsertOutboxMessage :one
INSERT INTO outbox_messages (topic, payload) VALUES ($1, $2) RETURNING id, topic, payload, status, attempts, next_attempt_at, last_error, created_at, sent_at
`

type InsertOutboxMessageParams struct {
	Topic   string `json:"topic"`
	Payload []byte `json:"payload"`
}

func (q *Queries) InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) (OutboxMessage, error) {
	row := q.db.QueryRow(ctx, insertOutboxMessage, arg.Topic, arg.Payload)
	var i OutboxMessage
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT l.id, l.actor_user_id, l.action, l.entity_type, l.entity_id, l.changes, l.ip, l.created_at,
       u.email AS actor_email
FROM audit_log l
LEFT JOIN users u ON u.id = l.actor_user_id
WHERE ($1 = '' OR l.entity_type = $1)
  AND ($2 = '' OR l.entity_id = $2)
ORDER BY l.created_at DESC LIMIT $3 OFFSET $4
`

type ListAuditLogParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListAuditLogRow struct {
	ID          int64              `json:"id"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    string             `json:"entity_id"`
	Changes     []byte             `json:"changes"`
	Ip          *netip.Addr        `json:"ip"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ActorEmail  pgtype.Text        `json:"actor_email"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]ListAuditLogRow, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogRow
	for rows.Next() {
		var i ListAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Changes,
			&i.Ip,
			&i.CreatedAt,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox_messages
SET status = CASE WHEN attempts >= 10 THEN 'failed' ELSE 'pending' END,
    attempts = attempts + 1,
    next_attempt_at = now() + make_interval(mins => LEAST(60, power(2, attempts)::int)),
    last_error = $2
WHERE id = $1
`

type MarkOutboxFailedParams struct {
	ID        int64       `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, arg.ID, arg.LastError)
	return err
}

const markOutboxSent = `-- name: MarkOutboxSent :exec
UPDATE outbox_messages SET status = 'sent', sent_at = now(), last_error = NULL WHERE id = $1
`

func (q *Queries) MarkOutboxSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxSent, id)
	return err
}

const setPlatformSetting = `-- name: SetPlatformSetting :one
INSERT INTO platform_settings (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
RETURNING key, value, updated_at
`

type SetPlatformSettingParams struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) SetPlatformSetting(ctx context.Context, arg SetPlatformSettingParams) (PlatformSetting, error) {
	row := q.db.QueryRow(ctx, setPlatformSetting, arg.Key, arg.Value)
	var i PlatformSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
