// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracking.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggClicksByDay = `-- name: AggClicksByDay :many

SELECT a.partner_id, a.offer_id, (c.created_at AT TIME ZONE 'Europe/Moscow')::date AS day, count(*)::bigint AS clicks
FROM tracking_clicks c
JOIN tracking_links tl ON tl.id = c.tracking_link_id
JOIN partner_offer_accesses a ON a.id = tl.partner_offer_access_id
WHERE c.created_at >= $1 AND c.created_at < $2
GROUP BY a.partner_id, a.offer_id, day
`

type AggClicksByDayParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type AggClicksByDayRow struct {
	PartnerID string      `json:"partner_id"`
	OfferID   string      `json:"offer_id"`
	Day       pgtype.Date `json:"day"`
	Clicks    int64       `json:"clicks"`
}

// Worker aggregation sources.
func (q *Queries) AggClicksByDay(ctx context.Context, arg AggClicksByDayParams) ([]AggClicksByDayRow, error) {
	rows, err := q.db.Query(ctx, aggClicksByDay, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggClicksByDayRow
	for rows.Next() {
		var i AggClicksByDayRow
		if err := rows.Scan(
			&i.PartnerID,
			&i.OfferID,
			&i.Day,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggClicksByLink = `-- name: AggClicksByLink :many
SELECT tracking_link_id, (created_at AT TIME ZONE 'Europe/Moscow')::date AS day, count(*)::bigint AS clicks
FROM tracking_clicks
WHERE created_at >= $1 AND created_at < $2
GROUP BY tracking_link_id, day
`

type AggClicksByLinkParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type AggClicksByLinkRow struct {
	TrackingLinkID string      `json:"tracking_link_id"`
	Day            pgtype.Date `json:"day"`
	Clicks         int64       `json:"clicks"`
}

func (q *Queries) AggClicksByLink(ctx context.Context, arg AggClicksByLinkParams) ([]AggClicksByLinkRow, error) {
	rows, err := q.db.Query(ctx, aggClicksByLink, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggClicksByLinkRow
	for rows.Next() {
		var i AggClicksByLinkRow
		if err := rows.Scan(&i.TrackingLinkID, &i.Day, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggFirstPaymentsByDay = `-- name: AggFirstPaymentsByDay :many
SELECT a.partner_id, a.offer_id, (ce.occurred_at AT TIME ZONE 'Europe/Moscow')::date AS day, count(*)::bigint AS first_payments
FROM conversion_events ce
JOIN external_user_attributions a ON a.id = ce.attribution_id
WHERE ce.occurred_at >= $1 AND ce.occurred_at < $2
GROUP BY a.partner_id, a.offer_id, day
`

type AggFirstPaymentsByDayParams struct {
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	OccurredAt_2 pgtype.Timestamptz `json:"occurred_at_2"`
}

type AggFirstPaymentsByDayRow struct {
	PartnerID     pgtype.UUID `json:"partner_id"`
	OfferID       pgtype.UUID `json:"offer_id"`
	Day           pgtype.Date `json:"day"`
	FirstPayments int64       `json:"first_payments"`
}

// NOTE: despite the legacy column name, this counts EVERY deposit event
// (conversion_events row = one real money top-up, see processConfirmed),
// not first-ever payments per player. The dashboard "Deposits" cards must
// reflect the fact of top-up: a repeat deposit by an existing player brings
// income with no "first payment", so counting only firsts made income and
// deposits diverge (e.g. income today with 0 deposits).
func (q *Queries) AggFirstPaymentsByDay(ctx context.Context, arg AggFirstPaymentsByDayParams) ([]AggFirstPaymentsByDayRow, error) {
	rows, err := q.db.Query(ctx, aggFirstPaymentsByDay, arg.OccurredAt, arg.OccurredAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggFirstPaymentsByDayRow
	for rows.Next() {
		var i AggFirstPaymentsByDayRow
		if err := rows.Scan(
			&i.PartnerID,
			&i.OfferID,
			&i.Day,
			&i.FirstPayments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggFirstPaymentsByLink = `-- name: AggFirstPaymentsByLink :many
SELECT COALESCE(a.tracking_link_id, c.tracking_link_id) AS tracking_link_id,
       (ce.occurred_at AT TIME ZONE 'Europe/Moscow')::date AS day, count(*)::bigint AS first_payments
FROM conversion_events ce
JOIN external_user_attributions a ON a.id = ce.attribution_id
LEFT JOIN tracking_clicks c ON c.id = a.tracking_click_id
WHERE ce.occurred_at >= $1 AND ce.occurred_at < $2
  AND COALESCE(a.tracking_link_id, c.tracking_link_id) IS NOT NULL
GROUP BY COALESCE(a.tracking_link_id, c.tracking_link_id), day
`

type AggFirstPaymentsByLinkParams struct {
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	OccurredAt_2 pgtype.Timestamptz `json:"occurred_at_2"`
}

type AggFirstPaymentsByLinkRow struct {
	TrackingLinkID string      `json:"tracking_link_id"`
	Day            pgtype.Date `json:"day"`
	FirstPayments  int64       `json:"first_payments"`
}

// Same as AggFirstPaymentsByDay but per traffic source: counts EVERY deposit
// event (see note above), resolving the link from the attribution with the
// click as fallback.
func (q *Queries) AggFirstPaymentsByLink(ctx context.Context, arg AggFirstPaymentsByLinkParams) ([]AggFirstPaymentsByLinkRow, error) {
	rows, err := q.db.Query(ctx, aggFirstPaymentsByLink, arg.OccurredAt, arg.OccurredAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggFirstPaymentsByLinkRow
	for rows.Next() {
		var i AggFirstPaymentsByLinkRow
		if err := rows.Scan(&i.TrackingLinkID, &i.Day, &i.FirstPayments); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggIncomeByDay = `-- name: AggIncomeByDay :many
SELECT partner_id, offer_id, (created_at AT TIME ZONE 'Europe/Moscow')::date AS day, sum(amount_kopecks)::bigint AS income_kopecks
FROM commission_earnings
WHERE created_at >= $1 AND created_at < $2 AND reversed_at IS NULL
GROUP BY partner_id, offer_id, day
`

type AggIncomeByDayParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type AggIncomeByDayRow struct {
	PartnerID     string      `json:"partner_id"`
	OfferID       string      `json:"offer_id"`
	Day           pgtype.Date `json:"day"`
	IncomeKopecks int64       `json:"income_kopecks"`
}

func (q *Queries) AggIncomeByDay(ctx context.Context, arg AggIncomeByDayParams) ([]AggIncomeByDayRow, error) {
	rows, err := q.db.Query(ctx, aggIncomeByDay, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggIncomeByDayRow
	for rows.Next() {
		var i AggIncomeByDayRow
		if err := rows.Scan(
			&i.PartnerID,
			&i.OfferID,
			&i.Day,
			&i.IncomeKopecks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggIncomeByLink = `-- name: AggIncomeByLink :many
SELECT tracking_link_id, (created_at AT TIME ZONE 'Europe/Moscow')::date AS day, sum(amount_kopecks)::bigint AS income_kopecks
FROM commission_earnings
WHERE created_at >= $1 AND created_at < $2 AND reversed_at IS NULL AND tracking_link_id IS NOT NULL
GROUP BY tracking_link_id, day
`

type AggIncomeByLinkParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type AggIncomeByLinkRow struct {
	TrackingLinkID pgtype.UUID `json:"tracking_link_id"`
	Day            pgtype.Date `json:"day"`
	IncomeKopecks  int64       `json:"income_kopecks"`
}

func (q *Queries) AggIncomeByLink(ctx context.Context, arg AggIncomeByLinkParams) ([]AggIncomeByLinkRow, error) {
	rows, err := q.db.Query(ctx, aggIncomeByLink, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggIncomeByLinkRow
	for rows.Next() {
		var i AggIncomeByLinkRow
		if err := rows.Scan(&i.TrackingLinkID, &i.Day, &i.IncomeKopecks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggRegistrationsByDay = `-- name: AggRegistrationsByDay :many
SELECT partner_id, offer_id, (first_seen_at AT TIME ZONE 'Europe/Moscow')::date AS day, count(*)::bigint AS registrations
FROM external_user_attributions
WHERE first_seen_at >= $1 AND first_seen_at < $2
GROUP BY partner_id, offer_id, day
`

type AggRegistrationsByDayParams struct {
	FirstSeenAt   pgtype.Timestamptz `json:"first_seen_at"`
	FirstSeenAt_2 pgtype.Timestamptz `json:"first_seen_at_2"`
}

type AggRegistrationsByDayRow struct {
	PartnerID     pgtype.UUID `json:"partner_id"`
	OfferID       pgtype.UUID `json:"offer_id"`
	Day           pgtype.Date `json:"day"`
	Registrations int64       `json:"registrations"`
}

func (q *Queries) AggRegistrationsByDay(ctx context.Context, arg AggRegistrationsByDayParams) ([]AggRegistrationsByDayRow, error) {
	rows, err := q.db.Query(ctx, aggRegistrationsByDay, arg.FirstSeenAt, arg.FirstSeenAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggRegistrationsByDayRow
	for rows.Next() {
		var i AggRegistrationsByDayRow
		if err := rows.Scan(
			&i.PartnerID,
			&i.OfferID,
			&i.Day,
			&i.Registrations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggRegistrationsByLink = `-- name: AggRegistrationsByLink :many
SELECT COALESCE(a.tracking_link_id, c.tracking_link_id) AS tracking_link_id,
       (a.first_seen_at AT TIME ZONE 'Europe/Moscow')::date AS day, count(*)::bigint AS registrations
FROM external_user_attributions a
LEFT JOIN tracking_clicks c ON c.id = a.tracking_click_id
WHERE a.first_seen_at >= $1 AND a.first_seen_at < $2
  AND COALESCE(a.tracking_link_id, c.tracking_link_id) IS NOT NULL
GROUP BY COALESCE(a.tracking_link_id, c.tracking_link_id), day
`

type AggRegistrationsByLinkParams struct {
	FirstSeenAt   pgtype.Timestamptz `json:"first_seen_at"`
	FirstSeenAt_2 pgtype.Timestamptz `json:"first_seen_at_2"`
}

type AggRegistrationsByLinkRow struct {
	TrackingLinkID string      `json:"tracking_link_id"`
	Day            pgtype.Date `json:"day"`
	Registrations  int64       `json:"registrations"`
}

func (q *Queries) AggRegistrationsByLink(ctx context.Context, arg AggRegistrationsByLinkParams) ([]AggRegistrationsByLinkRow, error) {
	rows, err := q.db.Query(ctx, aggRegistrationsByLink, arg.FirstSeenAt, arg.FirstSeenAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggRegistrationsByLinkRow
	for rows.Next() {
		var i AggRegistrationsByLinkRow
		if err := rows.Scan(&i.TrackingLinkID, &i.Day, &i.Registrations); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggUniqueClicksByDay = `-- name: AggUniqueClicksByDay :many
SELECT a.partner_id, a.offer_id, (c.created_at AT TIME ZONE 'Europe/Moscow')::date AS day, count(DISTINCT c.ip)::bigint AS unique_clicks
FROM tracking_clicks c
JOIN tracking_links tl ON tl.id = c.tracking_link_id
JOIN partner_offer_accesses a ON a.id = tl.partner_offer_access_id
WHERE c.created_at >= $1 AND c.created_at < $2 AND c.ip IS NOT NULL
GROUP BY a.partner_id, a.offer_id, day
`

type AggUniqueClicksByDayParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type AggUniqueClicksByDayRow struct {
	PartnerID    string      `json:"partner_id"`
	OfferID      string      `json:"offer_id"`
	Day          pgtype.Date `json:"day"`
	UniqueClicks int64       `json:"unique_clicks"`
}

func (q *Queries) AggUniqueClicksByDay(ctx context.Context, arg AggUniqueClicksByDayParams) ([]AggUniqueClicksByDayRow, error) {
	rows, err := q.db.Query(ctx, aggUniqueClicksByDay, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggUniqueClicksByDayRow
	for rows.Next() {
		var i AggUniqueClicksByDayRow
		if err := rows.Scan(
			&i.PartnerID,
			&i.OfferID,
			&i.Day,
			&i.UniqueClicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggUniqueClicksByLink = `-- name: AggUniqueClicksByLink :many
SELECT tracking_link_id, (created_at AT TIME ZONE 'Europe/Moscow')::date AS day, count(DISTINCT ip)::bigint AS unique_clicks
FROM tracking_clicks
WHERE created_at >= $1 AND created_at < $2 AND ip IS NOT NULL
GROUP BY tracking_link_id, day
`

type AggUniqueClicksByLinkParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type AggUniqueClicksByLinkRow struct {
	TrackingLinkID string      `json:"tracking_link_id"`
	Day            pgtype.Date `json:"day"`
	UniqueClicks   int64       `json:"unique_clicks"`
}

func (q *Queries) AggUniqueClicksByLink(ctx context.Context, arg AggUniqueClicksByLinkParams) ([]AggUniqueClicksByLinkRow, error) {
	rows, err := q.db.Query(ctx, aggUniqueClicksByLink, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggUniqueClicksByLinkRow
	for rows.Next() {
		var i AggUniqueClicksByLinkRow
		if err := rows.Scan(&i.TrackingLinkID, &i.Day, &i.UniqueClicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAttribution = `-- name: CreateAttribution :one
INSERT INTO external_user_attributions (project_id, tracking_click_id, tracking_link_id, partner_id, offer_id, external_user_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (project_id, external_user_id) DO NOTHING
RETURNING id, project_id, tracking_click_id, tracking_link_id, partner_id, offer_id, external_user_id, first_seen_at
`

type CreateAttributionParams struct {
	ProjectID       string      `json:"project_id"`
	TrackingClickID pgtype.Int8 `json:"tracking_click_id"`
	TrackingLinkID  pgtype.UUID `json:"tracking_link_id"`
	PartnerID       pgtype.UUID `json:"partner_id"`
	OfferID         pgtype.UUID `json:"offer_id"`
	ExternalUserID  string      `json:"external_user_id"`
}

func (q *Queries) CreateAttribution(ctx context.Context, arg CreateAttributionParams) (ExternalUserAttribution, error) {
	row := q.db.QueryRow(ctx, createAttribution,
		arg.ProjectID,
		arg.TrackingClickID,
		arg.TrackingLinkID,
		arg.PartnerID,
		arg.OfferID,
		arg.ExternalUserID,
	)
	var i ExternalUserAttribution
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TrackingClickID,
		&i.TrackingLinkID,
		&i.PartnerID,
		&i.OfferID,
		&i.ExternalUserID,
		&i.FirstSeenAt,
	)
	return i, err
}

const createTrackingClick = `-- name: CreateTrackingClick :one
INSERT INTO tracking_clicks (tracking_link_id, ip, user_agent, referrer)
VALUES ($1, $2::inet, $3, $4) RETURNING id, tracking_link_id, ip, user_agent, referrer, created_at
`

type CreateTrackingClickParams struct {
	TrackingLinkID string      `json:"tracking_link_id"`
	Column2        string      `json:"column_2"`
	UserAgent      pgtype.Text `json:"user_agent"`
	Referrer       pgtype.Text `json:"referrer"`
}

func (q *Queries) CreateTrackingClick(ctx context.Context, arg CreateTrackingClickParams) (TrackingClick, error) {
	row := q.db.QueryRow(ctx, createTrackingClick,
		arg.TrackingLinkID,
		arg.Column2,
		arg.UserAgent,
		arg.Referrer,
	)
	var i TrackingClick
	err := row.Scan(
		&i.ID,
		&i.TrackingLinkID,
		&i.Ip,
		&i.UserAgent,
		&i.Referrer,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDailyLinkStatsFrom = `-- name: DeleteDailyLinkStatsFrom :exec
DELETE FROM daily_tracking_link_stats WHERE day >= $1
`

func (q *Queries) DeleteDailyLinkStatsFrom(ctx context.Context, day pgtype.Date) error {
	_, err := q.db.Exec(ctx, deleteDailyLinkStatsFrom, day)
	return err
}

const deleteDailyStatsFrom = `-- name: DeleteDailyStatsFrom :exec
DELETE FROM daily_partner_offer_stats WHERE day >= $1
`

func (q *Queries) DeleteDailyStatsFrom(ctx context.Context, day pgtype.Date) error {
	_, err := q.db.Exec(ctx, deleteDailyStatsFrom, day)
	return err
}

const eventLock = `-- name: EventLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) EventLock(ctx context.Context, hashtextextended string) error {
	_, err := q.db.Exec(ctx, eventLock, hashtextextended)
	return err
}

const getAttributionByProjectUser = `-- name: GetAttributionByProjectUser :one
SELECT id, project_id, tracking_click_id, tracking_link_id, partner_id, offer_id, external_user_id, first_seen_at
FROM external_user_attributions WHERE project_id = $1 AND external_user_id = $2
`

type GetAttributionByProjectUserParams struct {
	ProjectID      string `json:"project_id"`
	ExternalUserID string `json:"external_user_id"`
}

func (q *Queries) GetAttributionByProjectUser(ctx context.Context, arg GetAttributionByProjectUserParams) (ExternalUserAttribution, error) {
	row := q.db.QueryRow(ctx, getAttributionByProjectUser, arg.ProjectID, arg.ExternalUserID)
	var i ExternalUserAttribution
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TrackingClickID,
		&i.TrackingLinkID,
		&i.PartnerID,
		&i.OfferID,
		&i.ExternalUserID,
		&i.FirstSeenAt,
	)
	return i, err
}

const getClickWithLink = `-- name: GetClickWithLink :one
SELECT c.id, c.tracking_link_id, c.created_at,
       tl.partner_offer_access_id, tl.code,
       a.partner_id, a.offer_id
FROM tracking_clicks c
JOIN tracking_links tl ON tl.id = c.tracking_link_id
JOIN partner_offer_accesses a ON a.id = tl.partner_offer_access_id
WHERE c.id = $1
`

type GetClickWithLinkRow struct {
	ID                   int64              `json:"id"`
	TrackingLinkID       string             `json:"tracking_link_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	PartnerOfferAccessID string             `json:"partner_offer_access_id"`
	Code                 string             `json:"code"`
	PartnerID            string             `json:"partner_id"`
	OfferID              string             `json:"offer_id"`
}

func (q *Queries) GetClickWithLink(ctx context.Context, id int64) (GetClickWithLinkRow, error) {
	row := q.db.QueryRow(ctx, getClickWithLink, id)
	var i GetClickWithLinkRow
	err := row.Scan(
		&i.ID,
		&i.TrackingLinkID,
		&i.CreatedAt,
		&i.PartnerOfferAccessID,
		&i.Code,
		&i.PartnerID,
		&i.OfferID,
	)
	return i, err
}

const getConversionByEvent = `-- name: GetConversionByEvent :one
SELECT id, project_id, external_event_id, external_payment_id, external_user_id, attribution_id, amount_kopecks, currency, occurred_at, processing_note, created_at
FROM conversion_events WHERE project_id = $1 AND external_event_id = $2
`

type GetConversionByEventParams struct {
	ProjectID       string `json:"project_id"`
	ExternalEventID string `json:"external_event_id"`
}

func (q *Queries) GetConversionByEvent(ctx context.Context, arg GetConversionByEventParams) (ConversionEvent, error) {
	row := q.db.QueryRow(ctx, getConversionByEvent, arg.ProjectID, arg.ExternalEventID)
	var i ConversionEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalEventID,
		&i.ExternalPaymentID,
		&i.ExternalUserID,
		&i.AttributionID,
		&i.AmountKopecks,
		&i.Currency,
		&i.OccurredAt,
		&i.ProcessingNote,
		&i.CreatedAt,
	)
	return i, err
}

const getConversionByPayment = `-- name: GetConversionByPayment :one
SELECT id, project_id, external_event_id, external_payment_id, external_user_id, attribution_id, amount_kopecks, currency, occurred_at, processing_note, created_at
FROM conversion_events WHERE project_id = $1 AND external_payment_id = $2
`

type GetConversionByPaymentParams struct {
	ProjectID         string `json:"project_id"`
	ExternalPaymentID string `json:"external_payment_id"`
}

func (q *Queries) GetConversionByPayment(ctx context.Context, arg GetConversionByPaymentParams) (ConversionEvent, error) {
	row := q.db.QueryRow(ctx, getConversionByPayment, arg.ProjectID, arg.ExternalPaymentID)
	var i ConversionEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalEventID,
		&i.ExternalPaymentID,
		&i.ExternalUserID,
		&i.AttributionID,
		&i.AmountKopecks,
		&i.Currency,
		&i.OccurredAt,
		&i.ProcessingNote,
		&i.CreatedAt,
	)
	return i, err
}

const getDailyStats = `-- name: GetDailyStats :many
SELECT partner_id, offer_id, day, clicks, unique_clicks, registrations, first_payments, income_kopecks
FROM daily_partner_offer_stats
WHERE partner_id = $1 AND day >= $2 AND day <= $3
ORDER BY day
`

type GetDailyStatsParams struct {
	PartnerID string      `json:"partner_id"`
	Day       pgtype.Date `json:"day"`
	Day_2     pgtype.Date `json:"day_2"`
}

func (q *Queries) GetDailyStats(ctx context.Context, arg GetDailyStatsParams) ([]DailyPartnerOfferStat, error) {
	rows, err := q.db.Query(ctx, getDailyStats, arg.PartnerID, arg.Day, arg.Day_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyPartnerOfferStat
	for rows.Next() {
		var i DailyPartnerOfferStat
		if err := rows.Scan(
			&i.PartnerID,
			&i.OfferID,
			&i.Day,
			&i.Clicks,
			&i.UniqueClicks,
			&i.Registrations,
			&i.FirstPayments,
			&i.IncomeKopecks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyStatsByOffer = `-- name: GetDailyStatsByOffer :many
SELECT partner_id, offer_id, day, clicks, unique_clicks, registrations, first_payments, income_kopecks
FROM daily_partner_offer_stats
WHERE partner_id = $1 AND offer_id = $2 AND day >= $3 AND day <= $4
ORDER BY day
`

type GetDailyStatsByOfferParams struct {
	PartnerID string      `json:"partner_id"`
	OfferID   string      `json:"offer_id"`
	Day       pgtype.Date `json:"day"`
	Day_2     pgtype.Date `json:"day_2"`
}

func (q *Queries) GetDailyStatsByOffer(ctx context.Context, arg GetDailyStatsByOfferParams) ([]DailyPartnerOfferStat, error) {
	rows, err := q.db.Query(ctx, getDailyStatsByOffer,
		arg.PartnerID,
		arg.OfferID,
		arg.Day,
		arg.Day_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyPartnerOfferStat
	for rows.Next() {
		var i DailyPartnerOfferStat
		if err := rows.Scan(
			&i.PartnerID,
			&i.OfferID,
			&i.Day,
			&i.Clicks,
			&i.UniqueClicks,
			&i.Registrations,
			&i.FirstPayments,
			&i.IncomeKopecks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncomingEvent = `-- name: GetIncomingEvent :one
SELECT id, project_id, external_event_id, type, status, reason, received_at
FROM incoming_events WHERE project_id = $1 AND external_event_id = $2
`

type GetIncomingEventParams struct {
	ProjectID       string `json:"project_id"`
	ExternalEventID string `json:"external_event_id"`
}

type GetIncomingEventRow struct {
	ID              int64              `json:"id"`
	ProjectID       string             `json:"project_id"`
	ExternalEventID string             `json:"external_event_id"`
	Type            string             `json:"type"`
	Status          string             `json:"status"`
	Reason          pgtype.Text        `json:"reason"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
}

func (q *Queries) GetIncomingEvent(ctx context.Context, arg GetIncomingEventParams) (GetIncomingEventRow, error) {
	row := q.db.QueryRow(ctx, getIncomingEvent, arg.ProjectID, arg.ExternalEventID)
	var i GetIncomingEventRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalEventID,
		&i.Type,
		&i.Status,
		&i.Reason,
		&i.ReceivedAt,
	)
	return i, err
}

const historyAttributionsByLink = `-- name: HistoryAttributionsByLink :many
SELECT a.id, a.external_user_id, a.first_seen_at
FROM external_user_attributions a
WHERE a.tracking_link_id = $1
  AND a.first_seen_at >= $2 AND a.first_seen_at <= $3
ORDER BY a.first_seen_at DESC LIMIT $4
`

type HistoryAttributionsByLinkParams struct {
	TrackingLinkID pgtype.UUID        `json:"tracking_link_id"`
	FirstSeenAt    pgtype.Timestamptz `json:"first_seen_at"`
	FirstSeenAt_2  pgtype.Timestamptz `json:"first_seen_at_2"`
	Limit          int32              `json:"limit"`
}

type HistoryAttributionsByLinkRow struct {
	ID             int64              `json:"id"`
	ExternalUserID string             `json:"external_user_id"`
	FirstSeenAt    pgtype.Timestamptz `json:"first_seen_at"`
}

// a.tracking_link_id populated by 00022/00025 backfill and set on every
// insert path; filtering on it directly lets Postgres use
// attributions_link_firstseen_idx (the old COALESCE(click subquery) form
// forced a full scan of external_user_attributions).
func (q *Queries) HistoryAttributionsByLink(ctx context.Context, arg HistoryAttributionsByLinkParams) ([]HistoryAttributionsByLinkRow, error) {
	rows, err := q.db.Query(ctx, historyAttributionsByLink,
		arg.TrackingLinkID,
		arg.FirstSeenAt,
		arg.FirstSeenAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistoryAttributionsByLinkRow
	for rows.Next() {
		var i HistoryAttributionsByLinkRow
		if err := rows.Scan(&i.ID, &i.ExternalUserID, &i.FirstSeenAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const historyClicksByLink = `-- name: HistoryClicksByLink :many

SELECT c.id, c.created_at
FROM tracking_clicks c
WHERE c.tracking_link_id = $1 AND c.created_at >= $2 AND c.created_at <= $3
ORDER BY c.created_at DESC LIMIT $4
`

type HistoryClicksByLinkParams struct {
	TrackingLinkID string             `json:"tracking_link_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2    pgtype.Timestamptz `json:"created_at_2"`
	Limit          int32              `json:"limit"`
}

type HistoryClicksByLinkRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Cabinet offer history pieces.
func (q *Queries) HistoryClicksByLink(ctx context.Context, arg HistoryClicksByLinkParams) ([]HistoryClicksByLinkRow, error) {
	rows, err := q.db.Query(ctx, historyClicksByLink,
		arg.TrackingLinkID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistoryClicksByLinkRow
	for rows.Next() {
		var i HistoryClicksByLinkRow
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const historyConversionsByLink = `-- name: HistoryConversionsByLink :many
SELECT ce.id, ce.external_user_id, ce.amount_kopecks, ce.occurred_at
FROM conversion_events ce
JOIN external_user_attributions a ON a.id = ce.attribution_id
WHERE a.tracking_link_id = $1
  AND ce.occurred_at >= $2 AND ce.occurred_at <= $3
ORDER BY ce.occurred_at DESC LIMIT $4
`

type HistoryConversionsByLinkParams struct {
	TrackingLinkID pgtype.UUID        `json:"tracking_link_id"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	OccurredAt_2   pgtype.Timestamptz `json:"occurred_at_2"`
	Limit          int32              `json:"limit"`
}

type HistoryConversionsByLinkRow struct {
	ID             int64              `json:"id"`
	ExternalUserID string             `json:"external_user_id"`
	AmountKopecks  int64              `json:"amount_kopecks"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) HistoryConversionsByLink(ctx context.Context, arg HistoryConversionsByLinkParams) ([]HistoryConversionsByLinkRow, error) {
	rows, err := q.db.Query(ctx, historyConversionsByLink,
		arg.TrackingLinkID,
		arg.OccurredAt,
		arg.OccurredAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistoryConversionsByLinkRow
	for rows.Next() {
		var i HistoryConversionsByLinkRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalUserID,
			&i.AmountKopecks,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const historyEarningsByPartnerOffer = `-- name: HistoryEarningsByPartnerOffer :many
SELECT e.id, e.amount_kopecks, e.reversed_at, e.created_at
FROM commission_earnings e
WHERE e.partner_id = $1 AND e.offer_id = $2
  AND e.created_at >= $3 AND e.created_at <= $4
ORDER BY e.created_at DESC LIMIT $5
`

type HistoryEarningsByPartnerOfferParams struct {
	PartnerID   string             `json:"partner_id"`
	OfferID     string             `json:"offer_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Limit       int32              `json:"limit"`
}

type HistoryEarningsByPartnerOfferRow struct {
	ID            string             `json:"id"`
	AmountKopecks int64              `json:"amount_kopecks"`
	ReversedAt    pgtype.Timestamptz `json:"reversed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) HistoryEarningsByPartnerOffer(ctx context.Context, arg HistoryEarningsByPartnerOfferParams) ([]HistoryEarningsByPartnerOfferRow, error) {
	rows, err := q.db.Query(ctx, historyEarningsByPartnerOffer,
		arg.PartnerID,
		arg.OfferID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistoryEarningsByPartnerOfferRow
	for rows.Next() {
		var i HistoryEarningsByPartnerOfferRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountKopecks,
			&i.ReversedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertConversion = `-- name: InsertConversion :one
INSERT INTO conversion_events (project_id, external_event_id, external_payment_id, external_user_id, attribution_id, amount_kopecks, currency, occurred_at, processing_note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, project_id, external_event_id, external_payment_id, external_user_id, attribution_id, amount_kopecks, currency, occurred_at, processing_note, created_at
`

type InsertConversionParams struct {
	ProjectID         string             `json:"project_id"`
	ExternalEventID   string             `json:"external_event_id"`
	ExternalPaymentID string             `json:"external_payment_id"`
	ExternalUserID    string             `json:"external_user_id"`
	AttributionID     int64              `json:"attribution_id"`
	AmountKopecks     int64              `json:"amount_kopecks"`
	Currency          string             `json:"currency"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	ProcessingNote    pgtype.Text        `json:"processing_note"`
}

func (q *Queries) InsertConversion(ctx context.Context, arg InsertConversionParams) (ConversionEvent, error) {
	row := q.db.QueryRow(ctx, insertConversion,
		arg.ProjectID,
		arg.ExternalEventID,
		arg.ExternalPaymentID,
		arg.ExternalUserID,
		arg.AttributionID,
		arg.AmountKopecks,
		arg.Currency,
		arg.OccurredAt,
		arg.ProcessingNote,
	)
	var i ConversionEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalEventID,
		&i.ExternalPaymentID,
		&i.ExternalUserID,
		&i.AttributionID,
		&i.AmountKopecks,
		&i.Currency,
		&i.OccurredAt,
		&i.ProcessingNote,
		&i.CreatedAt,
	)
	return i, err
}

const insertIncomingEvent = `-- name: InsertIncomingEvent :one
INSERT INTO incoming_events (project_id, external_event_id, type, payload, status, reason)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, project_id, external_event_id, type, status, reason, received_at
`

type InsertIncomingEventParams struct {
	ProjectID       string      `json:"project_id"`
	ExternalEventID string      `json:"external_event_id"`
	Type            string      `json:"type"`
	Payload         []byte      `json:"payload"`
	Status          string      `json:"status"`
	Reason          pgtype.Text `json:"reason"`
}

type InsertIncomingEventRow struct {
	ID              int64              `json:"id"`
	ProjectID       string             `json:"project_id"`
	ExternalEventID string             `json:"external_event_id"`
	Type            string             `json:"type"`
	Status          string             `json:"status"`
	Reason          pgtype.Text        `json:"reason"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
}

func (q *Queries) InsertIncomingEvent(ctx context.Context, arg InsertIncomingEventParams) (InsertIncomingEventRow, error) {
	row := q.db.QueryRow(ctx, insertIncomingEvent,
		arg.ProjectID,
		arg.ExternalEventID,
		arg.Type,
		arg.Payload,
		arg.Status,
		arg.Reason,
	)
	var i InsertIncomingEventRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalEventID,
		&i.Type,
		&i.Status,
		&i.Reason,
		&i.ReceivedAt,
	)
	return i, err
}

const listConversionsByAttribution = `-- name: ListConversionsByAttribution :many
SELECT id, project_id, external_event_id, external_payment_id, external_user_id, attribution_id, amount_kopecks, currency, occurred_at, processing_note, created_at
FROM conversion_events WHERE attribution_id = $1 ORDER BY occurred_at
`

func (q *Queries) ListConversionsByAttribution(ctx context.Context, attributionID int64) ([]ConversionEvent, error) {
	rows, err := q.db.Query(ctx, listConversionsByAttribution, attributionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversionEvent
	for rows.Next() {
		var i ConversionEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ExternalEventID,
			&i.ExternalPaymentID,
			&i.ExternalUserID,
			&i.AttributionID,
			&i.AmountKopecks,
			&i.Currency,
			&i.OccurredAt,
			&i.ProcessingNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumDailyLinkStats = `-- name: SumDailyLinkStats :one
SELECT COALESCE(sum(clicks), 0)::bigint AS clicks,
       COALESCE(sum(unique_clicks), 0)::bigint AS unique_clicks,
       COALESCE(sum(registrations), 0)::bigint AS registrations,
       COALESCE(sum(first_payments), 0)::bigint AS first_payments,
       COALESCE(sum(income_kopecks), 0)::bigint AS income_kopecks
FROM daily_tracking_link_stats
WHERE tracking_link_id = $1 AND day >= $2 AND day <= $3
`

type SumDailyLinkStatsParams struct {
	TrackingLinkID string      `json:"tracking_link_id"`
	Day            pgtype.Date `json:"day"`
	Day_2          pgtype.Date `json:"day_2"`
}

type SumDailyLinkStatsRow struct {
	Clicks        int64 `json:"clicks"`
	UniqueClicks  int64 `json:"unique_clicks"`
	Registrations int64 `json:"registrations"`
	FirstPayments int64 `json:"first_payments"`
	IncomeKopecks int64 `json:"income_kopecks"`
}

func (q *Queries) SumDailyLinkStats(ctx context.Context, arg SumDailyLinkStatsParams) (SumDailyLinkStatsRow, error) {
	row := q.db.QueryRow(ctx, sumDailyLinkStats, arg.TrackingLinkID, arg.Day, arg.Day_2)
	var i SumDailyLinkStatsRow
	err := row.Scan(
		&i.Clicks,
		&i.UniqueClicks,
		&i.Registrations,
		&i.FirstPayments,
		&i.IncomeKopecks,
	)
	return i, err
}

const sumDailyLinkStatsAllTime = `-- name: SumDailyLinkStatsAllTime :one
SELECT COALESCE(sum(clicks), 0)::bigint AS clicks,
       COALESCE(sum(unique_clicks), 0)::bigint AS unique_clicks,
       COALESCE(sum(registrations), 0)::bigint AS registrations,
       COALESCE(sum(first_payments), 0)::bigint AS first_payments,
       COALESCE(sum(income_kopecks), 0)::bigint AS income_kopecks
FROM daily_tracking_link_stats
WHERE tracking_link_id = $1
`

type SumDailyLinkStatsAllTimeRow struct {
	Clicks        int64 `json:"clicks"`
	UniqueClicks  int64 `json:"unique_clicks"`
	Registrations int64 `json:"registrations"`
	FirstPayments int64 `json:"first_payments"`
	IncomeKopecks int64 `json:"income_kopecks"`
}

func (q *Queries) SumDailyLinkStatsAllTime(ctx context.Context, trackingLinkID string) (SumDailyLinkStatsAllTimeRow, error) {
	row := q.db.QueryRow(ctx, sumDailyLinkStatsAllTime, trackingLinkID)
	var i SumDailyLinkStatsAllTimeRow
	err := row.Scan(
		&i.Clicks,
		&i.UniqueClicks,
		&i.Registrations,
		&i.FirstPayments,
		&i.IncomeKopecks,
	)
	return i, err
}

const sumDailyLinkStatsByLinks = `-- name: SumDailyLinkStatsByLinks :many
SELECT tracking_link_id,
       COALESCE(sum(clicks), 0)::bigint AS clicks,
       COALESCE(sum(unique_clicks), 0)::bigint AS unique_clicks,
       COALESCE(sum(registrations), 0)::bigint AS registrations,
       COALESCE(sum(first_payments), 0)::bigint AS first_payments,
       COALESCE(sum(income_kopecks), 0)::bigint AS income_kopecks,
       COALESCE(sum(clicks) FILTER (WHERE day >= $2), 0)::bigint AS window_clicks,
       COALESCE(sum(unique_clicks) FILTER (WHERE day >= $2), 0)::bigint AS window_unique_clicks,
       COALESCE(sum(registrations) FILTER (WHERE day >= $2), 0)::bigint AS window_registrations,
       COALESCE(sum(first_payments) FILTER (WHERE day >= $2), 0)::bigint AS window_first_payments,
       COALESCE(sum(income_kopecks) FILTER (WHERE day >= $2), 0)::bigint AS window_income_kopecks
FROM daily_tracking_link_stats
WHERE tracking_link_id = ANY($1::uuid[])
GROUP BY tracking_link_id
`

type SumDailyLinkStatsByLinksParams struct {
	Column1 []string    `json:"column_1"`
	Day     pgtype.Date `json:"day"`
}

type SumDailyLinkStatsByLinksRow struct {
	TrackingLinkID      string `json:"tracking_link_id"`
	Clicks              int64  `json:"clicks"`
	UniqueClicks        int64  `json:"unique_clicks"`
	Registrations       int64  `json:"registrations"`
	FirstPayments       int64  `json:"first_payments"`
	IncomeKopecks       int64  `json:"income_kopecks"`
	WindowClicks        int64  `json:"window_clicks"`
	WindowUniqueClicks  int64  `json:"window_unique_clicks"`
	WindowRegistrations int64  `json:"window_registrations"`
	WindowFirstPayments int64  `json:"window_first_payments"`
	WindowIncomeKopecks int64  `json:"window_income_kopecks"`
}

// Batched per-source totals (all-time + windowed) for a set of links: one
// index scan per link instead of two queries per link (N+1) in ListSources.
// day_from is inclusive (start of the 30d window); rows before it count only
// towards the all-time columns.
func (q *Queries) SumDailyLinkStatsByLinks(ctx context.Context, arg SumDailyLinkStatsByLinksParams) ([]SumDailyLinkStatsByLinksRow, error) {
	rows, err := q.db.Query(ctx, sumDailyLinkStatsByLinks, arg.Column1, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumDailyLinkStatsByLinksRow
	for rows.Next() {
		var i SumDailyLinkStatsByLinksRow
		if err := rows.Scan(
			&i.TrackingLinkID,
			&i.Clicks,
			&i.UniqueClicks,
			&i.Registrations,
			&i.FirstPayments,
			&i.IncomeKopecks,
			&i.WindowClicks,
			&i.WindowUniqueClicks,
			&i.WindowRegistrations,
			&i.WindowFirstPayments,
			&i.WindowIncomeKopecks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumDailyStats = `-- name: SumDailyStats :one
SELECT COALESCE(sum(clicks), 0)::bigint AS clicks,
       COALESCE(sum(unique_clicks), 0)::bigint AS unique_clicks,
       COALESCE(sum(registrations), 0)::bigint AS registrations,
       COALESCE(sum(first_payments), 0)::bigint AS first_payments,
       COALESCE(sum(income_kopecks), 0)::bigint AS income_kopecks
FROM daily_partner_offer_stats
WHERE partner_id = $1 AND day >= $2 AND day <= $3
`

type SumDailyStatsParams struct {
	PartnerID string      `json:"partner_id"`
	Day       pgtype.Date `json:"day"`
	Day_2     pgtype.Date `json:"day_2"`
}

type SumDailyStatsRow struct {
	Clicks        int64 `json:"clicks"`
	UniqueClicks  int64 `json:"unique_clicks"`
	Registrations int64 `json:"registrations"`
	FirstPayments int64 `json:"first_payments"`
	IncomeKopecks int64 `json:"income_kopecks"`
}

func (q *Queries) SumDailyStats(ctx context.Context, arg SumDailyStatsParams) (SumDailyStatsRow, error) {
	row := q.db.QueryRow(ctx, sumDailyStats, arg.PartnerID, arg.Day, arg.Day_2)
	var i SumDailyStatsRow
	err := row.Scan(
		&i.Clicks,
		&i.UniqueClicks,
		&i.Registrations,
		&i.FirstPayments,
		&i.IncomeKopecks,
	)
	return i, err
}

const sumDailyStatsAllTime = `-- name: SumDailyStatsAllTime :one
SELECT COALESCE(sum(clicks), 0)::bigint AS clicks,
       COALESCE(sum(unique_clicks), 0)::bigint AS unique_clicks,
       COALESCE(sum(registrations), 0)::bigint AS registrations,
       COALESCE(sum(first_payments), 0)::bigint AS first_payments,
       COALESCE(sum(income_kopecks), 0)::bigint AS income_kopecks
FROM daily_partner_offer_stats
WHERE partner_id = $1
`

type SumDailyStatsAllTimeRow struct {
	Clicks        int64 `json:"clicks"`
	UniqueClicks  int64 `json:"unique_clicks"`
	Registrations int64 `json:"registrations"`
	FirstPayments int64 `json:"first_payments"`
	IncomeKopecks int64 `json:"income_kopecks"`
}

func (q *Queries) SumDailyStatsAllTime(ctx context.Context, partnerID string) (SumDailyStatsAllTimeRow, error) {
	row := q.db.QueryRow(ctx, sumDailyStatsAllTime, partnerID)
	var i SumDailyStatsAllTimeRow
	err := row.Scan(
		&i.Clicks,
		&i.UniqueClicks,
		&i.Registrations,
		&i.FirstPayments,
		&i.IncomeKopecks,
	)
	return i, err
}

const sumDailyStatsByOffer = `-- name: SumDailyStatsByOffer :one
SELECT COALESCE(sum(clicks), 0)::bigint AS clicks,
       COALESCE(sum(unique_clicks), 0)::bigint AS unique_clicks,
       COALESCE(sum(registrations), 0)::bigint AS registrations,
       COALESCE(sum(first_payments), 0)::bigint AS first_payments,
       COALESCE(sum(income_kopecks), 0)::bigint AS income_kopecks
FROM daily_partner_offer_stats
WHERE partner_id = $1 AND offer_id = $2 AND day >= $3 AND day <= $4
`

type SumDailyStatsByOfferParams struct {
	PartnerID string      `json:"partner_id"`
	OfferID   string      `json:"offer_id"`
	Day       pgtype.Date `json:"day"`
	Day_2     pgtype.Date `json:"day_2"`
}

type SumDailyStatsByOfferRow struct {
	Clicks        int64 `json:"clicks"`
	UniqueClicks  int64 `json:"unique_clicks"`
	Registrations int64 `json:"registrations"`
	FirstPayments int64 `json:"first_payments"`
	IncomeKopecks int64 `json:"income_kopecks"`
}

func (q *Queries) SumDailyStatsByOffer(ctx context.Context, arg SumDailyStatsByOfferParams) (SumDailyStatsByOfferRow, error) {
	row := q.db.QueryRow(ctx, sumDailyStatsByOffer,
		arg.PartnerID,
		arg.OfferID,
		arg.Day,
		arg.Day_2,
	)
	var i SumDailyStatsByOfferRow
	err := row.Scan(
		&i.Clicks,
		&i.UniqueClicks,
		&i.Registrations,
		&i.FirstPayments,
		&i.IncomeKopecks,
	)
	return i, err
}

const sumDailyStatsGroupedByOffer = `-- name: SumDailyStatsGroupedByOffer :many
SELECT offer_id,
       COALESCE(sum(clicks), 0)::bigint AS clicks,
       COALESCE(sum(unique_clicks), 0)::bigint AS unique_clicks,
       COALESCE(sum(registrations), 0)::bigint AS registrations,
       COALESCE(sum(first_payments), 0)::bigint AS first_payments,
       COALESCE(sum(income_kopecks), 0)::bigint AS income_kopecks
FROM daily_partner_offer_stats
WHERE partner_id = $1 AND day >= $2 AND day <= $3
GROUP BY offer_id
`

type SumDailyStatsGroupedByOfferParams struct {
	PartnerID string      `json:"partner_id"`
	Day       pgtype.Date `json:"day"`
	Day_2     pgtype.Date `json:"day_2"`
}

type SumDailyStatsGroupedByOfferRow struct {
	OfferID       string `json:"offer_id"`
	Clicks        int64  `json:"clicks"`
	UniqueClicks  int64  `json:"unique_clicks"`
	Registrations int64  `json:"registrations"`
	FirstPayments int64  `json:"first_payments"`
	IncomeKopecks int64  `json:"income_kopecks"`
}

// Per-offer totals for one partner over a period (used instead of a
// per-offer loop in ListOffers / Summary).
func (q *Queries) SumDailyStatsGroupedByOffer(ctx context.Context, arg SumDailyStatsGroupedByOfferParams) ([]SumDailyStatsGroupedByOfferRow, error) {
	rows, err := q.db.Query(ctx, sumDailyStatsGroupedByOffer, arg.PartnerID, arg.Day, arg.Day_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumDailyStatsGroupedByOfferRow
	for rows.Next() {
		var i SumDailyStatsGroupedByOfferRow
		if err := rows.Scan(
			&i.OfferID,
			&i.Clicks,
			&i.UniqueClicks,
			&i.Registrations,
			&i.FirstPayments,
			&i.IncomeKopecks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumDailyStatsOfferAllTime = `-- name: SumDailyStatsOfferAllTime :one
SELECT COALESCE(sum(clicks), 0)::bigint AS clicks,
       COALESCE(sum(unique_clicks), 0)::bigint AS unique_clicks,
       COALESCE(sum(registrations), 0)::bigint AS registrations,
       COALESCE(sum(first_payments), 0)::bigint AS first_payments,
       COALESCE(sum(income_kopecks), 0)::bigint AS income_kopecks
FROM daily_partner_offer_stats
WHERE partner_id = $1 AND offer_id = $2
`

type SumDailyStatsOfferAllTimeParams struct {
	PartnerID string `json:"partner_id"`
	OfferID   string `json:"offer_id"`
}

type SumDailyStatsOfferAllTimeRow struct {
	Clicks        int64 `json:"clicks"`
	UniqueClicks  int64 `json:"unique_clicks"`
	Registrations int64 `json:"registrations"`
	FirstPayments int64 `json:"first_payments"`
	IncomeKopecks int64 `json:"income_kopecks"`
}

func (q *Queries) SumDailyStatsOfferAllTime(ctx context.Context, arg SumDailyStatsOfferAllTimeParams) (SumDailyStatsOfferAllTimeRow, error) {
	row := q.db.QueryRow(ctx, sumDailyStatsOfferAllTime, arg.PartnerID, arg.OfferID)
	var i SumDailyStatsOfferAllTimeRow
	err := row.Scan(
		&i.Clicks,
		&i.UniqueClicks,
		&i.Registrations,
		&i.FirstPayments,
		&i.IncomeKopecks,
	)
	return i, err
}

const updateConversionNote = `-- name: UpdateConversionNote :exec
UPDATE conversion_events SET processing_note = $2 WHERE id = $1
`

type UpdateConversionNoteParams struct {
	ID             int64       `json:"id"`
	ProcessingNote pgtype.Text `json:"processing_note"`
}

func (q *Queries) UpdateConversionNote(ctx context.Context, arg UpdateConversionNoteParams) error {
	_, err := q.db.Exec(ctx, updateConversionNote, arg.ID, arg.ProcessingNote)
	return err
}

const upsertDailyLinkStats = `-- name: UpsertDailyLinkStats :one

INSERT INTO daily_tracking_link_stats (tracking_link_id, day, clicks, unique_clicks, registrations, first_payments, income_kopecks)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tracking_link_id, day) DO UPDATE
SET clicks = EXCLUDED.clicks,
    unique_clicks = EXCLUDED.unique_clicks,
    registrations = EXCLUDED.registrations,
    first_payments = EXCLUDED.first_payments,
    income_kopecks = EXCLUDED.income_kopecks
RETURNING tracking_link_id, day, clicks, unique_clicks, registrations, first_payments, income_kopecks
`

type UpsertDailyLinkStatsParams struct {
	TrackingLinkID string      `json:"tracking_link_id"`
	Day            pgtype.Date `json:"day"`
	Clicks         int32       `json:"clicks"`
	UniqueClicks   int32       `json:"unique_clicks"`
	Registrations  int32       `json:"registrations"`
	FirstPayments  int32       `json:"first_payments"`
	IncomeKopecks  int64       `json:"income_kopecks"`
}

// Per-source (tracking link) daily stats.
func (q *Queries) UpsertDailyLinkStats(ctx context.Context, arg UpsertDailyLinkStatsParams) (DailyTrackingLinkStat, error) {
	row := q.db.QueryRow(ctx, upsertDailyLinkStats,
		arg.TrackingLinkID,
		arg.Day,
		arg.Clicks,
		arg.UniqueClicks,
		arg.Registrations,
		arg.FirstPayments,
		arg.IncomeKopecks,
	)
	var i DailyTrackingLinkStat
	err := row.Scan(
		&i.TrackingLinkID,
		&i.Day,
		&i.Clicks,
		&i.UniqueClicks,
		&i.Registrations,
		&i.FirstPayments,
		&i.IncomeKopecks,
	)
	return i, err
}

const upsertDailyStats = `-- name: UpsertDailyStats :one

INSERT INTO daily_partner_offer_stats (partner_id, offer_id, day, clicks, unique_clicks, registrations, first_payments, income_kopecks)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (partner_id, offer_id, day) DO UPDATE
SET clicks = EXCLUDED.clicks,
    unique_clicks = EXCLUDED.unique_clicks,
    registrations = EXCLUDED.registrations,
    first_payments = EXCLUDED.first_payments,
    income_kopecks = EXCLUDED.income_kopecks
RETURNING partner_id, offer_id, day, clicks, unique_clicks, registrations, first_payments, income_kopecks
`

type UpsertDailyStatsParams struct {
	PartnerID     string      `json:"partner_id"`
	OfferID       string      `json:"offer_id"`
	Day           pgtype.Date `json:"day"`
	Clicks        int32       `json:"clicks"`
	UniqueClicks  int32       `json:"unique_clicks"`
	Registrations int32       `json:"registrations"`
	FirstPayments int32       `json:"first_payments"`
	IncomeKopecks int64       `json:"income_kopecks"`
}

// Daily stats (worker aggregates and cabinet reads).
func (q *Queries) UpsertDailyStats(ctx context.Context, arg UpsertDailyStatsParams) (DailyPartnerOfferStat, error) {
	row := q.db.QueryRow(ctx, upsertDailyStats,
		arg.PartnerID,
		arg.OfferID,
		arg.Day,
		arg.Clicks,
		arg.UniqueClicks,
		arg.Registrations,
		arg.FirstPayments,
		arg.IncomeKopecks,
	)
	var i DailyPartnerOfferStat
	err := row.Scan(
		&i.PartnerID,
		&i.OfferID,
		&i.Day,
		&i.Clicks,
		&i.UniqueClicks,
		&i.Registrations,
		&i.FirstPayments,
		&i.IncomeKopecks,
	)
	return i, err
}
